objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Build_Task__c.object
<CustomObject>
    <fields>
        <fullName>Continuous_Integration__c</fullName>
        <label>Continuous Integration</label>
        <referenceTo>Continuous_Integration__c</referenceTo>
        <relationshipLabel>Build Tasks</relationshipLabel>
        <relationshipName>Build_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Build Tasks</relationshipLabel>
        <relationshipName>Build_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>Duration is calculated in seconds.</description>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Validate</fullName>
                </value>
                <value>
                    <fullName>Deploy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Build Task</label>
    <nameField>
        <displayFormat>BT-{0000000}</displayFormat>
        <label>Build Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Build Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Continuous_Integration__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Continuous Integration</label>
    <nameField>
        <label>Continuous Integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Continuous Integrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Build_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Build Task</label>
        <referenceTo>Build_Task__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Deployment_Job__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Org__c</fullName>
        <label>Destination Org</label>
        <referenceTo>Destination_Org__c</referenceTo>
        <relationshipLabel>Deployment Jobs</relationshipLabel>
        <relationshipName>Deployment_Jobs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Step__c</fullName>
        <label>Step</label>
        <referenceTo>Step__c</referenceTo>
        <relationshipLabel>Deployment Jobs</relationshipLabel>
        <relationshipName>Deployment_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deployment Job</label>
    <nameField>
        <displayFormat>DJ-{00000}</displayFormat>
        <label>Deployment Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Destination_Org__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Destination Orgs</relationshipLabel>
        <relationshipName>Destination_Orgs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Destination Org</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MetaData</fullName>
                    <default>true</default>
                    <label>MetaData</label>
                </value>
                <value>
                    <fullName>Full Profiles</fullName>
                </value>
                <value>
                    <fullName>Full Permission Sets</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Translations</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Bulk Data</fullName>
                </value>
                <value>
                    <fullName>Delete MetaData</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Git MetaData</fullName>
                </value>
                <value>
                    <fullName>URL Callout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestBuildTaskEmailController.cls
@isTest
private class TestBuildTaskEmailController {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }
    static testMethod void TestFullComponent(){
        Org__c testFromOrg = testMethodUtilities.create('OrgName', 'Production', 'PASSWORD', 'SFDC_OrgId', 'SFDC_TOKEN', 'USERNAME', System.now());
		insert testFromOrg;
		Deployment__c testDeployment = testMethodUtilities.create('DEPLOYMENT_NAME',System.now(), System.now(),testFromOrg.Id,'Deploy now','Scheduled');
		insert testDeployment;
		Step__c testStep = testMethodUtilities.create('Step 1','attId','JSONString',testDeployment.Id,0,'Not started','Git MetaData');
		insert testStep;
		Destination_Org__c testDestOrg = testMethodUtilities.create(testDeployment.Id,'Draft',testFromOrg.Id);
        insert testDestOrg;
        List<Deployment_Job__c> testJobs = [select Id from Deployment_Job__c where Step__r.Deployment__c=:testDeployment.Id and Step__r.Type__c='Git MetaData'];
        system.assertEquals(1, testJobs.size(), 'the deployment job query did not return any records.');
        
        
        String attBody = '[{"l":"ERROR","m":"[ApexClass agf__ADM_AcceptanceCriterionCloner] unexpected token: \u0027(\u0027","t":""},{"l":"ERROR","m":"[ApexClass agf__ADM_AcceptanceCriterionCloner] unexpected token: \u0027(\u0027","t":""}]';
        system.debug('@@@ jobs Id: '+testJobs[0].Id+'.json');
        Attachment testAttachment = createAttachment(testDeployment.Id, testJobs[0].Id+'.json', attBody);
        insert testAttachment;
        
        attBody = '[{"t":"ApexClass","n":"TestAccountTrigger"}]';
        testAttachment = createAttachment(testStep.Id, 'MetaData', attBody);
        insert testAttachment;
        
        Continuous_Integration__c ci = new Continuous_Integration__c(Name='My CI 1', Active__c=true, Status__c='Draft');
        insert ci;
        Build_Task__c bt = new Build_Task__c(Continuous_Integration__c=ci.Id, Duration__c=1, Status__c='Pending');
        bt.Deployment__c = testDeployment.Id;
        insert bt;
        system.debug('@@@ bt 1: '+bt);
        test.startTest();
        BuildTaskEmailController.buildTaskId = null;
        BuildTaskEmailController con = new BuildTaskEmailController();
        con.getErrorList();
        con.getBuildTaskList();
        system.assertEquals('Build task record not found.', BuildTaskEmailController.statusMessage);
        system.assertEquals('Build task record not found.', BuildTaskEmailController.buildTaskMessage);
        BuildTaskEmailController.buildTaskId = bt.Id;
        system.debug('@@ bt 2: '+bt);
        system.debug('@@ BuildTaskEmailController.buildTaskId: '+BuildTaskEmailController.buildTaskId);
        con.getErrorList();
        con.getBuildTaskList();
        test.stopTest();
        system.assertEquals('', BuildTaskEmailController.statusMessage);
        system.assertEquals(2, BuildTaskEmailController.errorDetails.size());
        system.assertEquals('ERROR', BuildTaskEmailController.errorDetails[0].l);
        system.assertEquals('[ApexClass agf__ADM_AcceptanceCriterionCloner] unexpected token: \u0027(\u0027', BuildTaskEmailController.errorDetails[0].m);
        system.assertEquals('', BuildTaskEmailController.errorDetails[0].t);
        system.assertEquals('', BuildTaskEmailController.buildTaskMessage);
        system.assertEquals(1, BuildTaskEmailController.buildTaskDetails.size());
        system.assertEquals('ApexClass', BuildTaskEmailController.buildTaskDetails[0].t);
		system.assertEquals('TestAccountTrigger', BuildTaskEmailController.buildTaskDetails[0].n);
    }
    static testMethod void testComparable(){
        BuildTaskEmailController.sortType = null;
        BuildTaskEmailController con = new BuildTaskEmailController();
        BuildTaskEmailController.BuildTaskContent btc1 = new BuildTaskEmailController.BuildTaskContent();
        btc1.n = 'OpportunityTrigger';
        btc1.t = 'ApexTrigger';
        BuildTaskEmailController.buildTaskDetails = new List<BuildTaskEmailController.BuildTaskContent>();
        BuildTaskEmailController.buildTaskDetails.add(btc1);
        BuildTaskEmailController.BuildTaskContent btc2 = new BuildTaskEmailController.BuildTaskContent();
        btc2.n = 'Account';
        btc2.t = 'Workflow';
        BuildTaskEmailController.buildTaskDetails.add(btc2);
        BuildTaskEmailController.buildTaskDetails.sort();
        system.assertEquals('Account', BuildTaskEmailController.buildTaskDetails[0].n);
        
        BuildTaskEmailController.sortType = 'type';
        BuildTaskEmailController.buildTaskDetails.sort();
        system.assertEquals('OpportunityTrigger', BuildTaskEmailController.buildTaskDetails[0].n);
    }
    static testMethod void NoBuildTaskRecordFound(){
        test.startTest();
        BuildTaskEmailController.buildTaskId = null;
        BuildTaskEmailController con = new BuildTaskEmailController();
        List<BuildTaskEmailController.ErrorContent> result1 = con.getErrorList();
        List<BuildTaskEmailController.BuildTaskContent> result2 = con.getBuildTaskList();
        String resultId = BuildTaskEmailController.getBuildTaskId();
        test.stopTest();
        system.assertEquals('Build task record not found.', BuildTaskEmailController.buildTaskMessage);
        system.assertEquals('Build task record not found.', BuildTaskEmailController.statusMessage);
        system.assertEquals(null, resultId);
    }
    static testMethod void NoBuildTasksException(){
        Continuous_Integration__c ci = new Continuous_Integration__c(Name='My CI 1', Active__c=true, Status__c='Draft');
        insert ci;
        Build_Task__c bt = new Build_Task__c(Continuous_Integration__c=ci.Id, Duration__c=1, Status__c='Pending');
        insert bt;
        test.startTest();
        BuildTaskEmailController.buildTaskId = bt.Id;
        BuildTaskEmailController con = new BuildTaskEmailController();
        List<BuildTaskEmailController.ErrorContent> result1 = con.getErrorList();
        List<BuildTaskEmailController.BuildTaskContent> result2 = con.getBuildTaskList();
        test.stopTest();
        String expected = 'Using a Build Task Id no records were found. Please make sure this build task ('+bt.Id+') has a Deployment, you have access to it and has not been deleted.';
        system.assertEquals(expected, BuildTaskEmailController.buildTaskMessage);
        system.assertEquals(expected, BuildTaskEmailController.statusMessage);
    }
    static testMethod void NoDeploymentJobsFound(){
        Deployment__c testDeployment = testMethodUtilities.create('DEPLOYMENT_NAME', System.now(), System.now(), null, 'Deploy now', 'Scheduled');
        insert testDeployment;
        Continuous_Integration__c ci = new Continuous_Integration__c(Name='My CI 1', Active__c=true, Status__c='Draft');
        insert ci;
        Build_Task__c bt = new Build_Task__c(Continuous_Integration__c=ci.Id, Duration__c=1, Status__c='Pending');
        bt.Deployment__c = testDeployment.Id;
		insert bt;
        test.startTest();
        BuildTaskEmailController.buildTaskId = bt.Id;
        BuildTaskEmailController con = new BuildTaskEmailController();
        List<BuildTaskEmailController.ErrorContent> result1 = con.getErrorList();
        List<BuildTaskEmailController.BuildTaskContent> result2 = con.getBuildTaskList();
        test.stopTest();
        system.assertEquals('No deployment jobs could be found.', BuildTaskEmailController.buildTaskMessage);
        system.assertEquals('No deployment jobs could be found.', BuildTaskEmailController.statusMessage);
    }
    static testMethod void NoAttachmentsFound(){
        Org__c testFromOrg = testMethodUtilities.create('OrgName', 'Production', 'PASSWORD', 'SFDC_OrgId', 'SFDC_TOKEN', 'USERNAME', System.now());
		insert testFromOrg;
		Deployment__c testDeployment = testMethodUtilities.create('DEPLOYMENT_NAME',System.now(), System.now(),testFromOrg.Id,'Deploy now','Scheduled');
		insert testDeployment;
        
        Step__c testStep = testMethodUtilities.create('Step 1','attId','JSONString',testDeployment.Id,0,'Not started','Git MetaData');
		insert testStep;
		Destination_Org__c testDestOrg = testMethodUtilities.create(testDeployment.Id,'Draft',testFromOrg.Id);
        insert testDestOrg;
        List<Deployment_Job__c> testJobs = [select Id from Deployment_Job__c where Step__r.Deployment__c=:testDeployment.Id and Step__r.Type__c='Git MetaData'];
        system.assertEquals(1, testJobs.size());
        
        Continuous_Integration__c ci = new Continuous_Integration__c(Name='My CI 1', Active__c=true, Status__c='Draft');
        insert ci;
        Build_Task__c bt = new Build_Task__c(Continuous_Integration__c=ci.Id, Duration__c=1, Status__c='Pending');
        bt.Deployment__c = testDeployment.Id;
        insert bt;
        
        test.startTest();
        BuildTaskEmailController.buildTaskId = bt.Id;
        BuildTaskEmailController con = new BuildTaskEmailController();
        con.getErrorList();
        con.getBuildTaskList();
        test.stopTest();
        system.assertEquals('No error attachment was found', BuildTaskEmailController.statusMessage);
        system.assertEquals(0, BuildTaskEmailController.errorDetails.size());
        system.assertEquals('No selected metadata attachment was found', BuildTaskEmailController.buildTaskMessage);
        system.assertEquals(0, BuildTaskEmailController.buildTaskDetails.size());
    }
    static testMethod void AttachmentTooBig(){
    	Org__c testFromOrg = testMethodUtilities.create('OrgName', 'Production', 'PASSWORD', 'SFDC_OrgId', 'SFDC_TOKEN', 'USERNAME', System.now());
		insert testFromOrg;
		Deployment__c testDeployment = testMethodUtilities.create('DEPLOYMENT_NAME',System.now(), System.now(),testFromOrg.Id,'Deploy now','Scheduled');
		insert testDeployment;
		Step__c testStep = testMethodUtilities.create('Step 1','attId','JSONString',testDeployment.Id,0,'Not started','Git MetaData');
		insert testStep;
		Destination_Org__c testDestOrg = testMethodUtilities.create(testDeployment.Id,'Draft',testFromOrg.Id);
        insert testDestOrg;
        List<Deployment_Job__c> testJobs = [select Id from Deployment_Job__c where Step__r.Deployment__c=:testDeployment.Id and Step__r.Type__c='Git MetaData'];
        system.assertEquals(1, testJobs.size());
        
        //Now create attachment against deployment.
        String attBody = '{"l":"ERROR","m":"[ApexClass agf__ADM_AcceptanceCriterionCloner] unexpected token: \u0027(\u0027","t":""},{"l":"ERROR","m":"[ApexClass agf__ADM_AcceptanceCriterionCloner] unexpected token: \u0027(\u0027","t":""},';
        String attBody2 = '{"t":"ApexClass","n":"TestAccountTrigger"},"t":"ApexClass","n":"TestAccountTrigger"},"t":"ApexClass","n":"TestAccountTrigger"},"t":"ApexClass","n":"TestAccountTrigger"},"t":"ApexClass","n":"TestAccountTrigger"},';
        for(Integer i=0; i<=11; i++){
            attBody += attBody;
            attBody2 += attBody2;
        }
        attBody = attBody.substring(0, attBody.length()-1); //removes last comma.
        attBody2 = attBody2.substring(0, attBody2.length()-1);
        Attachment testAttachment = createAttachment(testDeployment.Id, testJobs[0].Id+'.json', '['+attBody+']');
        insert testAttachment;
        List<Attachment> attr = [select Id, BodyLength from Attachment where Id=:testAttachment.Id];
        system.assert(attr[0].BodyLength>BuildTaskEmailController.MAX_BODY_LENGTH);
        
        Attachment testAttachment2 = createAttachment(testStep.Id, 'MetaData', '['+attBody2+']');
        insert testAttachment2;
        
        Continuous_Integration__c ci = new Continuous_Integration__c(Name='My CI 1', Active__c=true, Status__c='Draft');
        insert ci;
        Build_Task__c bt = new Build_Task__c(Continuous_Integration__c=ci.Id, Duration__c=1, Status__c='Pending');
        bt.Deployment__c = testDeployment.Id;
        insert bt;
        
        test.startTest();
        BuildTaskEmailController.buildTaskId = bt.Id;
        BuildTaskEmailController con = new BuildTaskEmailController();
        con.getErrorList();
        con.getBuildTaskList();
        test.stopTest();
        system.assertEquals('The maximum file size for the error list attachment has been exceeded. To avoid reaching the Salesforce Heapsize limits, please review the deployment in Salesforce.', BuildTaskEmailController.statusMessage);
        system.assertEquals(0, BuildTaskEmailController.errorDetails.size());
        system.assertEquals('The maximum file size for the build list attachment has been exceeded. To avoid reaching the Salesforce Heapsize limits, please review the deployment in Salesforce.', BuildTaskEmailController.buildTaskMessage);
        system.assertEquals(0, BuildTaskEmailController.buildTaskDetails.size());
    }
    private static Attachment createAttachment(String parentId, String name, String body){
		Attachment a = new Attachment(parentId=parentId, name=name);
		a.Body = Blob.valueOf(body);
		return a;
	}
}