objects/Apex_Test_Result__c.object
<CustomObject>
    <description>This object stores the results of scheduled Apex Tests executed through Copado Deployer.</description>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Apex Test Results</relationshipLabel>
        <relationshipName>Apex_Test_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Test Result</label>
    <nameField>
        <displayFormat>Test-{0000}</displayFormat>
        <label>Apex Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Custom_Domain__c</fullName>
        <inlineHelpText>Eg: https://company.my.salesforce.com</inlineHelpText>
        <label>Custom Domain</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Disable_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this checkbox will not validate the org credentials when the record is saved or viewed.</inlineHelpText>
        <label>Disable Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Oauth_Signature__c</fullName>
        <description>This value is automatically set and updated by Copado.</description>
        <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
        <label>Oauth Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Frequency__c</fullName>
        <description>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</description>
        <inlineHelpText>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</inlineHelpText>
        <label>Test Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_Developer_Hub_Org__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Developer Hub Org</label>
        <type>Checkbox</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EditOrg.cls
public with sharing class EditOrg {
    public Org__c org {get; set;}
    public String dumypass {get; set;}
    public string metadata_url {get; set;}
    public boolean showUserPass {get; set;}

    public List<String> sel {get; set;}
    private List<String> metadataTypes;
    public List<SelectOption> types;
    public List<SelectOption> selectedTypes {get; set;}

    public Boolean hasTestResultAttachment {get; set;}
    public String resAttId {get; set;}
    public boolean isShareable {get; set;}
    public boolean scaAccess {get; set;}
    public boolean complianceScanResultAccess {get; set;}
    public Boolean showError {get; set;}
    public Boolean showOptions {get; set;}
    public Boolean complianceScanRequestAccess {get; set;}
    public Boolean isScratchOrg {get;set;}

    public EditOrg(apexpages.standardController std) {
        // Add ALL the fields of the sobject to the list of queried fields, to avoid " SObject row was retrieved via SOQL without querying..."
        if (!Test.isRunningTest()) std.addFields(new List<String>(Schema.SObjectType.Org__c.fields.getMap().keySet()));
        if (!Test.isRunningTest()) std.addFields(new List<String> {Settings.ns + 'Environment__r.Name', Settings.ns + 'is_Developer_Hub_Org__c'});

        showOptions = true;
        showError = false;
        scaAccess = FeatureAccessHelper.isSCAFeatureAccessible();
        complianceScanRequestAccess = LicenseHelper.actionIsLicenseEnabled('requestComplianceScan');
        complianceScanResultAccess = FeatureAccessHelper.isComplianceScanResultAccessible();
        hasTestResultAttachment = false;
        dumypass = '********';
        isLicenseEnabled();
        if (std.getId() != null) {
            org = utilities.getOrgById(std.getId());
        } else {
            org = new Org__c();
        }
        showUserPass = (org.password__c != null && org.oauth_signature__c == null) || Apexpages.currentPage().getParameters().get('showUserPass') == 'true';
        setUrls();

        isScratchOrg = String.isNotBlank(org.Org_Type__c) && org.Org_Type__c.startsWithIgnoreCase('Scratch Org');

        //****** selected types
        selectedTypes = new List<SelectOption>();
        sel = new List<String>();
        if (org.Metadata_Types__c != null) {
            for (String t : org.Metadata_Types__c.split(',')) {
                selectedTypes.add(new SelectOption(t, t));
                sel.add(t);
            }
        }
        sel.sort();

        //check apex test feature
        if (org.Test_Frequency__c != null && org.Test_Frequency__c != 'None' && !FeatureHelper.isFeatureEnabled('Apex Test') ) {
            org.Test_Frequency__c.addError(Label.FEATURE_NOT_SUPPORTED + ': Apex Test');
        }

        Map<String, Schema.SObjectType> tokens = Schema.getGlobalDescribe();
        isShareable = tokens.containsKey('Org__Share');

        getTestResultAttachment();
    }

    public void getTestResultAttachment() {
        List<Apex_Test_Result__c> res = [select id from Apex_Test_Result__c where Org__c = :org.Id order by createddate desc limit 1];
        if (res.size() == 0)return;
        List<Attachment> atts = [select Id from Attachment where Name = 'ApexTestResult' and ParentId = :res.get(0).Id];
        if (atts.size() > 0) {
            this.hasTestResultAttachment = true;
            resAttId = atts.get(0).Id;
            //result = ApexTestResultCompController.buildApexResultsFromAttachment(resAtt.Id, null);
        }
    }

    public List<String> getMetadataTypes() {
        return MetadataTypesHelper.getMetadataTypesByOrgId(org.Id);
    }



    public List<SelectOption> getTypes() {

        return MetadataTypesHelper.getTypeOptionsByOrgId(org.Id, sel);

    }

    public void setTypes(List<SelectOption> l) {
        types = l;
    }



    public PageReference save() {
        //check apex test feature
        if (org.Test_Frequency__c != null && org.Test_Frequency__c != 'None' && !FeatureHelper.isFeatureEnabled('Apex Test') ) {
            org.Test_Frequency__c.addError(Label.FEATURE_NOT_SUPPORTED + ': Apex Test');
            return null;
        }

        //recover metadata types to save
        org.Metadata_Types__c = MetadataTypesHelper.joinOptions(selectedTypes);

        if (showUserPass == true && org.password__c != null)org.oauth_signature__c = null; //blank oauth
        Utilities.Secure_DML(org, Utilities.DML_Action.UPS, schema.Sobjecttype.Org__c);
        return new apexpages.standardController(org).view();
    }
    public PageReference addUserPass() {
        org.oauth_signature__c = null;
        showUserPass = true;
        PageReference pr = new apexpages.standardController(org).edit();
        pr.getParameters().put('showUserPass', 'true');
        return pr;
    }
    public PageReference doOauth() {
        String urlParameters = '?orgId=' + EncodingUtil.urlEncode(org.Id, 'UTF-8') + '&url=' + EncodingUtil.urlEncode([select API_URL__c from User where id = :userinfo.getUserId()].API_URL__c, 'UTF-8');
        if (org.Org_Type__c == 'Sandbox' || (String.isNotBlank(org.Org_Type__c) && org.Org_Type__c.startsWithIgnoreCase('Scratch Org'))) urlParameters += '&sandbox=true';
        if (org.Org_Type__c == 'Custom Domain') urlParameters += '&domain=' + EncodingUtil.urlEncode(org.Custom_Domain__c, 'UTF-8');
        urlParameters += '&copadoOrgId=' + EncodingUtil.urlEncode(userinfo.getOrganizationId(), 'UTF-8');
        urlParameters += '&copadoUserId=' + EncodingUtil.urlEncode(userinfo.getUserId(), 'UTF-8');
        urlParameters += '&signature=' + EncodingUtil.urlEncode(DeployAPI.encryptAPIKey(userinfo.getOrganizationId() + userinfo.getUserId()), 'UTF-8');
        String herokuServer = settings.Server_URL;
        String urlOauth = herokuServer + '/Authorize/sforceLogin' + urlParameters;
        PageReference pr = new PageReference(urlOauth);
        system.debug(pr);
        return pr;
    }
    public void setUrls() {
        //TODO: move this to external util method in order to use it in other classes
        String urlParameters = '';

        if (String.isNotBlank(org.Metadata_Types__c)) {
            urlParameters += '&filter=' + EncodingUtil.urlEncode(org.Metadata_Types__c, 'UTF-8');
        }

        String herokuServer = settings.Server_URL;
        String urlBase = herokuServer + '/json/v1/';
        if (org.Id == null)return;
        metadata_url = urlBase + 'metadata/' + EncodingUtil.urlEncode(org.Id, 'UTF-8') + '?dates=format' + urlParameters ;
    }
    public PageReference validate(){
        if(OrgTriggerHelper.isScheduled(org) && !FeatureHelper.isFeatureEnabled('Apex Test')){
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error,Label.FEATURE_NOT_SUPPORTED+': Apex Test'));
            return null;
        }
        if(org.id != null && !org.Disable_Validation__c && !isScratchOrg){
            org = utilities.getOrgById(org.id);
            if(org.oauth_signature__c == null && org.password__c == null){
                Apexpages.addMessage(new apexpages.Message(apexpages.severity.info,Label.ADD_AUTHENTICATION));
                return null;
            }
            else{
                if (!DeployAPI.validateOrg(org.Id)){
                    Apexpages.addMessage(new apexpages.Message(apexpages.severity.error,Label.WRONG_CREDENTIALS));
                    return null;
                }
                else{
                    Apexpages.addMessage(new apexpages.Message(apexpages.severity.CONFIRM,Label.OK_CREDENTIALS));
                }
            }
            if(org.Test_Frequency__c!=null && org.Test_Frequency__c!='None'){
                Org__c copadoOrg = DeployAPI.getCustomerOrg();
                if(copadoOrg ==null){
                    Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, Label.CUSTOMER_ORG_NOT_EXISTS));
                    return null;
                }
                if(!DeployAPI.validateOrg(copadoOrg.id)){
                    Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, Label.CUSTOMER_ORG_NOT_VALIDATED));
                }
            }
        }

        return null;
    }

    public PageReference runAllTest() {
        if (!FeatureHelper.isFeatureEnabled('Apex Test')) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, Label.FEATURE_NOT_SUPPORTED + ': Apex Test'));
            return null;
        }
        if (!DeployAPI.validateOrg(org.Id)) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, Label.WRONG_CREDENTIALS));
            return null;
        }
        try {
            DeployAPI.testNow(org.id);
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.confirm, Label.TEST_REQUESTED));
        } catch (Exception e) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, '' + e.getMessage()));
        }
        return null;
    }
    public PageReference orgCodeAnalysis() {
        if (!FeatureHelper.isFeatureEnabled('Apex Test')) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, Label.FEATURE_NOT_SUPPORTED + ': Static Code Analysis'));
            return null;
        }
        if (!DeployAPI.validateOrg(org.Id)) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, Label.WRONG_CREDENTIALS));
            return null;
        }
        try {
            DeployAPI.orgCodeAnalysis(org.id);
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.confirm, Label.STATIC_CODE_ANALYSIS_REQUESTED));
        } catch (Exception e) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error, '' + e.getMessage()));
        }
        return null;
    }

    public PageReference orgComplianceScan() {
        if (!FeatureHelper.isFeatureEnabled('Compliance Hub')) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.ERROR, Label.FEATURE_NOT_SUPPORTED + ': Compliance Hub'));
            return null;
        }

        if (!LicenseHelper.isCCHEnabled()) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.ERROR, Label.CCH_LICENSE_NOT_ENABLED));
            return null;
        }

        if (!DeployAPI.validateOrg(org.Id)) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.ERROR, Label.WRONG_CREDENTIALS));
            return null;
        }

        try {
            DeployAPI.orgComplianceScan(org.Id);
            ApexPages.getMessages().clear();
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.CONFIRM, Label.COMPLIANCE_SCAN_REQUESTED));
        } catch (Exception e) {
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.ERROR, e.getMessage()));
        }

        return null;
    }

    public void isLicenseEnabled() {
        if (!LicenseHelper.actionIsLicenseEnabled('viewEditOrgCredential')) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CAD_License_Restriction));
            showError = true;
            showOptions = false;
        }
        return;
    }

    public PageReference gotoDxOperations(){
        PageReference pRef = Page.DXOperation;
        if(String.isNotBlank(org.Id)){
            pRef.getParameters().put('id',org.Id);
        }
        pRef.setRedirect(true);
        return pRef;
    }

}