objects/Apex_Test_Result__c.object
<CustomObject>
    <description>This object stores the results of scheduled Apex Tests executed through Copado Deployer.</description>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Apex Test Results</relationshipLabel>
        <relationshipName>Apex_Test_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Test Result</label>
    <nameField>
        <displayFormat>Test-{0000}</displayFormat>
        <label>Apex Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Has_Apex_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value automatically updated by Copado whenever there are Apex Classes added or committed in the User Story.</description>
        <inlineHelpText>Value automatically updated by Copado whenever there are Apex Classes added or committed in the User Story.</inlineHelpText>
        <label>Has Apex Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Minimum_Apex_Code_Coverage__c</fullName>
        <defaultValue>0.75</defaultValue>
        <description>Minimum Apex Code Coverage required. If this value is lower than the value set in the User Story&apos;s Environment, the Environment&apos;s value will be automatically applied.</description>
        <inlineHelpText>Minimum Apex Code Coverage required. If this value is lower than the value set in the User Story&apos;s Environment, the Environment&apos;s value will be automatically applied.</inlineHelpText>
        <label>Minimum Apex Code Coverage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoryApexTestResultsExtension.cls
public with sharing class UserStoryApexTestResultsExtension {

    private final User_Story__c userStory;
    public String attId {get;set;}
    public Boolean hasAttachment {get;set;}
    
    public static final String[] USERSTORY_FIELDS = new String[] {'Id','Name', 'Org_Credential__c', 'Org_Credential__r.Error__c', 'Org_Credential__r.Validated_Date__c', 'Minimum_Apex_Code_Coverage__c', 'Has_Apex_Code__c'};
    
    public UserStoryApexTestResultsExtension(ApexPages.StandardController stdController) {
        hasAttachment = false;
        if (!Test.isRunningTest())stdController.addFields(USERSTORY_FIELDS);
        this.userStory = (User_Story__c)stdController.getRecord();
        
        if(userStory.Org_Credential__c == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'This user story does not have a source org. Please add a Source Org to the User Story and try again.'));
            return;
        }
        
        getAttachment();
        if(userStory.Org_Credential__r.Error__c != null || userStory.Org_Credential__r.Validated_Date__c == null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'The selected org is not validated.'));
        }
        if(hasAttachment == false){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'This user story has no Apex Test Results. Press the \'Run Tests\' button.'));
        }
    }
    public void getAttachment(){
        List<Apex_Test_Result__c> res = [select id from Apex_Test_Result__c where Org__c = :userStory.Org_Credential__c order by createddate desc limit 1];
        if (res.size()==0)return;
        List<Attachment> atts = [select Id from Attachment where Name ='ApexTestResult' and ParentId=:res.get(0).Id order by LastModifiedDate DESC];
        if(atts.size()> 0){
            this.hasAttachment = true;
            attId = atts.get(0).Id;
        }
    }
}