objects/AuxiliaryObject__c.object
<CustomObject>
    <description>This object is used as a helper to create lookup fields to various objects so that they may be used in e.g. AJAX lookups.</description>
    <fields>
        <fullName>Selenium_Test_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selenium Test Group</label>
        <referenceTo>Selenium_Test_Group__c</referenceTo>
        <relationshipLabel>AuxiliaryObjects</relationshipLabel>
        <relationshipName>AuxiliaryObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selenium_Test_Run__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Selenium Test Run</label>
        <referenceTo>Selenium_Test_Run__c</referenceTo>
        <relationshipLabel>AuxiliaryObjects</relationshipLabel>
        <relationshipName>AuxiliaryObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AuxiliaryObject</label>
    <nameField>
        <label>AuxiliaryObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AuxiliaryObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Group__c.object
<CustomObject>
    <label>Selenium Test Group</label>
    <nameField>
        <label>Selenium Test Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Run__c.object
<CustomObject>
    <fields>
        <fullName>Selenium_Test_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field should not be populated.  The value is automatically maintained.</inlineHelpText>
        <label>Selenium Test Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Selenium_Test_Group__c.Manage_Test_Runs_manually__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Selenium_Test_Group__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Selenium Test Run</label>
    <nameField>
        <label>Selenium Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassAddRunsToGroup.cls
public with sharing class MassAddRunsToGroup {
    public List<Selenium_Test_Run__c> runs;
    public AuxiliaryObject__c dummy {get;set;}
    public apexpages.standardsetcontroller con;
    public MassAddRunsToGroup(apexpages.standardsetcontroller std){
        con = std;
        runs = (List<Selenium_Test_Run__c>)std.getSelected();
        System.debug('MassAddRunsToGroup selected... '+runs.size());
        dummy = new AuxiliaryObject__c ();
    }
    public PageReference cancel(){
        return con.cancel();
    }
    public PageReference add(){
        List<Selenium_Test_Run__c> dos = new List<Selenium_Test_Run__c>(); 
        for (Selenium_Test_Run__c o: runs){
            dos.add( new Selenium_Test_Run__c(Id=o.Id, Selenium_Test_Group__c = dummy.Selenium_Test_Group__c) );
        }
        System.debug('MassAddRunsToGroup updating... '+dos.size());
        if(dos.size()>0){
            Database.SaveResult[] res = Database.update(dos, false);
            boolean err = false;
            for(Database.SaveResult r:res){
                if(!r.isSuccess()){
                    err = true;
                    apexpages.addMessage(new Apexpages.Message(apexpages.severity.error, r.getErrors()[0].getMessage()));
                }
            }
            if(err)return null;
        }
        else{
            apexpages.addMessage(new Apexpages.Message(apexpages.severity.error, Label.SELECT_AT_LEAST_ONE_RECORD));
            return null;
        }
        return new PageReference('/' + dummy.Selenium_Test_Group__c);
    }
}