objects/Compliance_Finding__c.object
<CustomObject>
    <description>This object stores the individual findings of a Compliance Scan.  It is a junction object between the Compliance Scan and the Compliance Rule for which the findings have been found.</description>
    <fields>
        <fullName>Compliance_Scan_Result__c</fullName>
        <label>Compliance Scan Result</label>
        <referenceTo>Compliance_Scan_Result__c</referenceTo>
        <relationshipLabel>Compliance Findings</relationshipLabel>
        <relationshipName>Compliance_Findings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Compliance Finding</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Compliance Finding Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Compliance_Scan_Result__c.object
<CustomObject>
    <description>This object stores the results of a compliance scan</description>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Git_Snapshot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Snapshot</label>
        <referenceTo>Git_Backup__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed - No Findings</fullName>
                </value>
                <value>
                    <fullName>Completed - Findings detected</fullName>
                </value>
                <value>
                    <fullName>Completed - Resolved</fullName>
                </value>
                <value>
                    <fullName>Under Investigation</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compliance Scan Result</label>
    <nameField>
        <displayFormat>Scan Result - {000000000}</displayFormat>
        <label>Scan Result Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Scan Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Compliance_Scan_Date__c</fullName>
        <label>Last Compliance Scan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Compliance_Scan_Date__c</fullName>
        <label>Last Compliance Scan Date</label>
        <type>DateTime</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <description>Status of the most recent Compliance Scan of the Branch specified in the Git Snapshot.</description>
        <inlineHelpText>Status of the most recent Compliance Scan of the Branch specified in the Git Snapshot.</inlineHelpText>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Compliance_Scan_Date__c</fullName>
        <description>Date of the last Compliance Scan of the Branch specified in the Git Snapshot.</description>
        <inlineHelpText>Date of the last Compliance Scan of the Branch specified in the Git Snapshot.</inlineHelpText>
        <label>Last Compliance Scan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <description>Status of the most recent Compliance Scan of the Org.</description>
        <inlineHelpText>Status of the most recent Compliance Scan of the Org.</inlineHelpText>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Compliance_Scan_Date__c</fullName>
        <label>Last Compliance Scan Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <description>Current status of the User Story Compliance scan.</description>
        <inlineHelpText>Current status of the User Story Compliance scan.</inlineHelpText>
        <label>Compliance Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed - Findings detected</fullName>
                </value>
                <value>
                    <fullName>Completed - No Findings</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed - Resolved</fullName>
                </value>
                <value>
                    <fullName>Under Investigation</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Compliance_Scan_Date__c</fullName>
        <description>Latest Compliance Scan execution date.</description>
        <inlineHelpText>Latest Compliance Scan execution date.</inlineHelpText>
        <label>Last Compliance Scan Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ComplianceScanResultTriggerHelper.cls
public without sharing class ComplianceScanResultTriggerHelper {

	public static Map<Id, Compliance_Scan_Result__c> scanResultSeverityFindingsMap;
	public static Map<Id, Compliance_Scan_Result__c> scanResultActionFindingsMap;
	public static Map<Id, Org__c> orgMap;
    public static Map<Id, Environment__c> envMap;
    public static Map<Id, User_Story__c> userStoryMap;
    public static Map<Id, Git_Backup__c> gitBackupMap;
    public static Map<Id, Deployment__c> deploymentMap; 
	
	public static void prepareData(List<SObject> records){
		orgMap = new Map<Id, Org__c>();
        envMap = new Map<Id, Environment__c>();
        userStoryMap = new Map<Id, User_Story__c>();
        gitBackupMap = new Map<Id, Git_Backup__c>();
        deploymentMap = new Map<Id, Deployment__c>();
		
        Set<Id> orgIds = new Set<Id>();
        Set<Id> envIds = new Set<Id>();
        Set<Id> userStoryIds = new Set<Id>();
        Set<Id> gitBackupIds = new Set<Id>();
        Set<Id> deploymentIds = new Set<Id>();
        Set<Id> scanResultIds = new Set<Id>();

    	for(SObject so : records) {
    		Compliance_Scan_Result__c scanResult = (Compliance_Scan_Result__c)so;
            scanResultIds.add(scanResult.Id);

            if(scanResult.Org_Credential__c != null) {
            	orgIds.add(scanResult.Org_Credential__c);
            }
            if(scanResult.Environment__c != null) {
            	envIds.add(scanResult.Environment__c);
            }
            if(scanResult.User_Story__c != null) {
            	userStoryIds.add(scanResult.User_Story__c);
            }
            if(scanResult.Git_Snapshot__c != null) {
            	gitBackupIds.add(scanResult.Git_Snapshot__c);
            }
            if(scanResult.Deployment__c != null) {
            	deploymentIds.add(scanResult.Deployment__c);
            }
    	}

        if(!Trigger.isDelete) {
            orgMap = new Map<Id, Org__c>([SELECT Id, Compliance_Status__c, Environment__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r ORDER BY CreatedDate DESC LIMIT 1) FROM Org__c WHERE Id IN :orgIds]);
            for(Org__c org : orgMap.values()) {
                envIds.add(org.Environment__c);
            }
        	envMap = new Map<Id, Environment__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r ORDER BY CreatedDate DESC LIMIT 1) FROM Environment__c WHERE Id IN :envIds]);
            userStoryMap = new Map<Id, User_Story__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r ORDER BY CreatedDate ASC LIMIT 1) FROM User_Story__c WHERE Id IN :userStoryIds]);
            gitBackupMap = new Map<Id, Git_Backup__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r ORDER BY CreatedDate DESC LIMIT 1) FROM Git_Backup__c WHERE Id IN :gitBackupIds]);
            deploymentMap = new Map<Id, Deployment__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r ORDER BY CreatedDate DESC LIMIT 1) FROM Deployment__c WHERE Id IN :deploymentIds]);
        } else {
            orgMap = new Map<Id, Org__c>([SELECT Id, Compliance_Status__c, Environment__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r WHERE Id NOT IN :scanResultIds ORDER BY CreatedDate DESC LIMIT 1) FROM Org__c WHERE Id IN :orgIds]);
            for(Org__c org : orgMap.values()) {
                envIds.add(org.Environment__c);
            }
            envMap = new Map<Id, Environment__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r WHERE Id NOT IN :scanResultIds ORDER BY CreatedDate DESC LIMIT 1) FROM Environment__c WHERE Id IN :envIds]);
            userStoryMap = new Map<Id, User_Story__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r WHERE Id NOT IN :scanResultIds ORDER BY CreatedDate DESC LIMIT 1) FROM User_Story__c WHERE Id IN :userStoryIds]);
            gitBackupMap = new Map<Id, Git_Backup__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r WHERE Id NOT IN :scanResultIds ORDER BY CreatedDate DESC LIMIT 1) FROM Git_Backup__c WHERE Id IN :gitBackupIds]);
            deploymentMap = new Map<Id, Deployment__c>([SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c, (SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Results__r WHERE Id NOT IN :scanResultIds ORDER BY CreatedDate DESC LIMIT 1) FROM Deployment__c WHERE Id IN :deploymentIds]);
        }        
    }

	public static void prepareSummaryData(List<SObject> records) {
    	System.debug('prepareSummaryData');
        Set<Id> scanResultIds = new Set<Id>();
    	for(SObject so : records) {
            scanResultIds.add(so.Id);
        }

        scanResultSeverityFindingsMap = new Map<Id, Compliance_Scan_Result__c>();
        scanResultActionFindingsMap = new Map<Id, Compliance_Scan_Result__c>();
    	scanResultSeverityFindingsMap = new Map<Id, Compliance_Scan_Result__c>([SELECT Id, Highest_Severity__c, (SELECT Id, Compliance_Rule__r.Severity__c FROM Compliance_Findings__r ORDER BY Compliance_Rule__r.Severity__c LIMIT 1) FROM Compliance_Scan_Result__c WHERE Id IN :scanResultIds]);
    	scanResultActionFindingsMap = new Map<Id, Compliance_Scan_Result__c>([SELECT Id, Highest_Rule_Action__c, (SELECT Id, Compliance_Rule__r.Action__c FROM Compliance_Findings__r ORDER BY Compliance_Rule__r.Action__c LIMIT 1) FROM Compliance_Scan_Result__c WHERE Id IN :scanResultIds]);
    }

	public static void updateComplianceFields(Compliance_Scan_Result__c scanResult) {
        System.debug('### updateComplianceFields');
        System.debug('### scanResult: '+scanResult);
		if(scanResult.Org_Credential__c != null && orgMap.get(scanResult.Org_Credential__c) != null) {
            Org__c org = orgMap.get(scanResult.Org_Credential__c);
            if(orgMap.get(scanResult.Org_Credential__c).Compliance_Scan_Results__r.size() > 0) {
                if(org.Last_Compliance_Scan_Date__c != orgMap.get(scanResult.Org_Credential__c).Compliance_Scan_Results__r[0].CreatedDate) {
                    org.Last_Compliance_Scan_Date__c = orgMap.get(scanResult.Org_Credential__c).Compliance_Scan_Results__r[0].CreatedDate;
                }
                if(org.Compliance_Status__c != orgMap.get(scanResult.Org_Credential__c).Compliance_Scan_Results__r[0].Status__c) {
                    org.Compliance_Status__c = orgMap.get(scanResult.Org_Credential__c).Compliance_Scan_Results__r[0].Status__c;
                }
            } else {
                org.Last_Compliance_Scan_Date__c = null;
                org.Compliance_Status__c = '';
            }
            Utilities.Secure_DML(org, Utilities.DML_Action.UPD, schema.Sobjecttype.Org__c);
        }

        if(scanResult.Environment__c != null && envMap.get(scanResult.Environment__c) != null) {
            Environment__c env = envMap.get(scanResult.Environment__c);
            if(envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r.size() > 0) {
                System.debug('### *** env.Last_Compliance_Scan_Date__c: '+env.Last_Compliance_Scan_Date__c);
                System.debug('### *** envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r[0].CreatedDate: '+envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r[0].CreatedDate);
                if(env.Last_Compliance_Scan_Date__c != envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r[0].CreatedDate) {
                    env.Last_Compliance_Scan_Date__c = envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r[0].CreatedDate;
                }
                if(env.Compliance_Status__c != envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r[0].Status__c) {
                    env.Compliance_Status__c = envMap.get(scanResult.Environment__c).Compliance_Scan_Results__r[0].Status__c;
                }
            } else {
                env.Last_Compliance_Scan_Date__c = null;
                env.Compliance_Status__c = '';
            }
            Utilities.Secure_DML(env, Utilities.DML_Action.UPD, schema.Sobjecttype.Environment__c);
        }

		if(scanResult.User_Story__c != null && userStoryMap.get(scanResult.User_Story__c) != null) {			
            User_Story__c userStory = userStoryMap.get(scanResult.User_Story__c);
            if(userStoryMap.get(scanResult.User_Story__c).Compliance_Scan_Results__r.size() > 0) {
                if(userStory.Last_Compliance_Scan_Date__c != userStoryMap.get(scanResult.User_Story__c).Compliance_Scan_Results__r[0].CreatedDate) {
                    userStory.Last_Compliance_Scan_Date__c = userStoryMap.get(scanResult.User_Story__c).Compliance_Scan_Results__r[0].CreatedDate;
                }
                if(userStory.Compliance_Status__c != userStoryMap.get(scanResult.User_Story__c).Compliance_Scan_Results__r[0].Status__c) {
                    userStory.Compliance_Status__c = userStoryMap.get(scanResult.User_Story__c).Compliance_Scan_Results__r[0].Status__c;
                }
            } else {
                userStory.Last_Compliance_Scan_Date__c = null;
                userStory.Compliance_Status__c = '';
            }
            Utilities.Secure_DML(userStory, Utilities.DML_Action.UPD, schema.Sobjecttype.User_Story__c);
		}

		if(scanResult.Git_Snapshot__c != null && gitBackupMap.get(scanResult.Git_Snapshot__c) != null) {            
            Git_Backup__c gitBackup = gitBackupMap.get(scanResult.Git_Snapshot__c);
            if(gitBackupMap.get(scanResult.Git_Snapshot__c).Compliance_Scan_Results__r.size() > 0) {
                if(gitBackup.Last_Compliance_Scan_Date__c != gitBackupMap.get(scanResult.Git_Snapshot__c).Compliance_Scan_Results__r[0].CreatedDate) {
                    gitBackup.Last_Compliance_Scan_Date__c = gitBackupMap.get(scanResult.Git_Snapshot__c).Compliance_Scan_Results__r[0].CreatedDate;
                }
                if(gitBackup.Compliance_Status__c != gitBackupMap.get(scanResult.Git_Snapshot__c).Compliance_Scan_Results__r[0].Status__c) {
                    gitBackup.Compliance_Status__c = gitBackupMap.get(scanResult.Git_Snapshot__c).Compliance_Scan_Results__r[0].Status__c;
                }
            } else {
                gitBackup.Last_Compliance_Scan_Date__c = null;
                gitBackup.Compliance_Status__c = '';
            }
            Utilities.Secure_DML(gitBackup, Utilities.DML_Action.UPD, schema.Sobjecttype.Git_Backup__c); 
		}

        if(scanResult.Deployment__c != null && deploymentMap.get(scanResult.Deployment__c) != null) {
            Deployment__c deployment = deploymentMap.get(scanResult.Deployment__c);

            if(deploymentMap.get(scanResult.Deployment__c).Compliance_Scan_Results__r.size() > 0) {
                if(deployment.Last_Compliance_Scan_Date__c != deploymentMap.get(scanResult.Deployment__c).Compliance_Scan_Results__r[0].CreatedDate) {
                    deployment.Last_Compliance_Scan_Date__c = deploymentMap.get(scanResult.Deployment__c).Compliance_Scan_Results__r[0].CreatedDate;
                } 
                if(deployment.Compliance_Status__c != deploymentMap.get(scanResult.Deployment__c).Compliance_Scan_Results__r[0].Status__c) {
                    deployment.Compliance_Status__c = deploymentMap.get(scanResult.Deployment__c).Compliance_Scan_Results__r[0].Status__c;
                } 
            } else {
                deployment.Last_Compliance_Scan_Date__c = null;
                deployment.Compliance_Status__c = '';
            }
            Utilities.Secure_DML(deployment, Utilities.DML_Action.UPD, schema.Sobjecttype.Deployment__c);    
        }
	}

	public static void updateComplianceScanSummaryFields(Compliance_Scan_Result__c scanResult) {
		System.debug('### Compliance Scan Result: '+scanResult);
		if(scanResultSeverityFindingsMap.get(scanResult.Id) != null && scanResultSeverityFindingsMap.get(scanResult.Id).Compliance_Findings__r.size() > 0) {
			String highestSeverity = scanResultSeverityFindingsMap.get(scanResult.Id).Compliance_Findings__r[0].Compliance_Rule__r.Severity__c;
			System.debug('### HighestSeverity: '+highestSeverity);
			scanResult.Highest_Severity__c = highestSeverity;
		}
		if(scanResultActionFindingsMap.get(scanResult.Id) != null && scanResultActionFindingsMap.get(scanResult.Id).Compliance_Findings__r.size() > 0) {
			String highestRuleAction = scanResultActionFindingsMap.get(scanResult.Id).Compliance_Findings__r[0].Compliance_Rule__r.Action__c;
			System.debug('### HighestRuleAction: '+highestRuleAction);
			scanResult.Highest_Rule_Action__c = highestRuleAction;
		}
	}
}