objects/Compliance_Finding__c.object
<CustomObject>
    <description>This object stores the individual findings of a Compliance Scan.  It is a junction object between the Compliance Scan and the Compliance Rule for which the findings have been found.</description>
    <fields>
        <fullName>Compliance_Scan_Result__c</fullName>
        <label>Compliance Scan Result</label>
        <referenceTo>Compliance_Scan_Result__c</referenceTo>
        <relationshipLabel>Compliance Findings</relationshipLabel>
        <relationshipName>Compliance_Findings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Compliance Finding</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Compliance Finding Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Findings</pluralLabel>
    <recordTypes>
        <fullName>Copado</fullName>
        <active>true</active>
        <description>This record type is used for scan findings produced by Copado.</description>
        <label>Copado</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Compliance_Scan_Result__c.object
<CustomObject>
    <description>This object stores the results of a compliance scan</description>
    <fields>
        <fullName>Deployment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Git_Snapshot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Snapshot</label>
        <referenceTo>Git_Backup__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed - No Findings</fullName>
                </value>
                <value>
                    <fullName>Completed - Findings detected</fullName>
                </value>
                <value>
                    <fullName>Completed - Resolved</fullName>
                </value>
                <value>
                    <fullName>Under Investigation</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compliance Scan Result</label>
    <nameField>
        <displayFormat>Scan Result - {000000000}</displayFormat>
        <label>Scan Result Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Scan Results</pluralLabel>
    <recordTypes>
        <fullName>Copado</fullName>
        <active>true</active>
        <description>This record type is used for scan results produced by Copado.</description>
        <label>Copado</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <label>Compliance Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <defaultValue>&quot;master&quot;</defaultValue>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <description>Status of the most recent Compliance Scan of the Branch specified in the Git Snapshot.</description>
        <inlineHelpText>Status of the most recent Compliance Scan of the Branch specified in the Git Snapshot.</inlineHelpText>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Compliance_Status__c</fullName>
        <description>Status of the most recent Compliance Scan of the Org.</description>
        <inlineHelpText>Status of the most recent Compliance Scan of the Org.</inlineHelpText>
        <label>Compliance Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestComplianceScanResultTriggerHandler.cls
@isTest
private class TestComplianceScanResultTriggerHandler {

	@testSetup static void setupData() {
		TestUtilities.enableLicenses(2, 0, 0, 0, 2);
	}

	@isTest static void testUpdateScanResult() {
		TestUtilities.assignLicense(UserInfo.getUserName(), true, false, false, false, true);
        String ns = '';
        if([select id,name, namespacePrefix from apexclass where name='CopadoSetupController' and namespaceprefix='copado'].size()==1){
            ns = 'copado__';
        }
		Git_Repository__c gitRepo = new Git_Repository__c(name = 'gitRepo');
		insert gitRepo;

		Environment__c envUAT = new Environment__c(Name = 'UAT Environment', Type__c = 'Sandbox');
		insert envUAT;

		Org__c orgUAT = CMTestMethodUtilities.createOrg('UAT Org', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), envUAT.Id);
		insert orgUAT;

		Git_Backup__c gitSnapshotUAT = new Git_Backup__c(Git_Repository__c = gitRepo.id, Org__c = orgUAT.id, Branch__c = 'master');
		insert gitSnapshotUAT;

		User_Story__c userStory1 = CMTestMethodUtilities.createUserStory('userStory1 UAT');
		userStory1.Org_Credential__c = orgUAT.Id;
		insert userStory1;

		Deployment__c deploymentUAT = new Deployment__c(name = 'test Deploypment', From_Org__c = orgUAT.Id);
		insert deploymentUAT;

		Compliance_Scan_Result__c scanResultUserStory = new Compliance_Scan_Result__c(Status__c = 'Completed - Findings detected', Environment__c = envUAT.Id, User_Story__c = userStory1.Id, Org_Credential__c = orgUAT.Id, Git_Snapshot__c = gitSnapshotUAT.Id, Deployment__c = deploymentUAT.Id);
		insert scanResultUserStory;

		scanResultUserStory = [SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultUserStory.Id];
		Test.setCreatedDate(scanResultUserStory.Id, Datetime.now().addDays(-2));

		Test.startTest();

		envUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Environment__c WHERE Id = :envUAT.Id];
		System.assertEquals('Completed - Findings detected', envUAT.Compliance_Status__c);
		System.assertEquals(scanResultUserStory.CreatedDate, envUAT.Last_Compliance_Scan_Date__c);

		orgUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Org__c WHERE Id = :orgUAT.Id];
		System.assertEquals('Completed - Findings detected', orgUAT.Compliance_Status__c);
		System.assertEquals(scanResultUserStory.CreatedDate, orgUAT.Last_Compliance_Scan_Date__c);

		userStory1 = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM User_Story__c WHERE Id = :userStory1.Id];
		System.assertEquals('Completed - Findings detected', userStory1.Compliance_Status__c);
		System.assertEquals(scanResultUserStory.CreatedDate, userStory1.Last_Compliance_Scan_Date__c);

		gitSnapshotUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Git_Backup__c WHERE Id = :gitSnapshotUAT.Id];
		System.assertEquals('Completed - Findings detected', gitSnapshotUAT.Compliance_Status__c);
		System.assertEquals(scanResultUserStory.CreatedDate, gitSnapshotUAT.Last_Compliance_Scan_Date__c);

		deploymentUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Deployment__c WHERE Id = :deploymentUAT.Id];
		System.assertEquals('Completed - Findings detected', deploymentUAT.Compliance_Status__c);
		System.assertEquals(scanResultUserStory.CreatedDate, deploymentUAT.Last_Compliance_Scan_Date__c);

		System.debug('### INSERT ScanResultDeployment');

		Compliance_Scan_Result__c scanResultDeployment = new Compliance_Scan_Result__c(Status__c = 'In Progress', Environment__c = envUAT.Id, Org_Credential__c = orgUAT.Id, Deployment__c = deploymentUAT.Id);
		insert scanResultDeployment;
		scanResultDeployment = [SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultDeployment.Id];

		System.debug('### UPDATE ScanResultUserStory');

		scanResultUserStory.Status__c = 'Completed - Resolved';
		update scanResultUserStory;
		scanResultUserStory = [SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultUserStory.Id];

		System.debug('### scanResultUserStory: ' + scanResultUserStory);
		System.debug('### scanResultDeployment: ' + scanResultDeployment);

		envUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Environment__c WHERE Id = :envUAT.Id];
		System.assertEquals('In Progress', envUAT.Compliance_Status__c);
		System.assertEquals(envUAT.Last_Compliance_Scan_Date__c, scanResultDeployment.CreatedDate);

		orgUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Org__c WHERE Id = :orgUAT.Id];
		System.assertEquals(orgUAT.Last_Compliance_Scan_Date__c, scanResultDeployment.CreatedDate);
		System.assertEquals('In Progress', orgUAT.Compliance_Status__c);

		userStory1 = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM User_Story__c WHERE Id = :userStory1.Id];
		System.assertEquals(userStory1.Last_Compliance_Scan_Date__c, scanResultUserStory.CreatedDate);
		System.assertEquals('Completed - Resolved', userStory1.Compliance_Status__c);

		gitSnapshotUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Git_Backup__c WHERE Id = :gitSnapshotUAT.Id];
		System.assertEquals(gitSnapshotUAT.Last_Compliance_Scan_Date__c, scanResultUserStory.CreatedDate);
		System.assertEquals('Completed - Resolved', gitSnapshotUAT.Compliance_Status__c);

		deploymentUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Deployment__c WHERE Id = :deploymentUAT.Id];
		System.assertEquals(deploymentUAT.Last_Compliance_Scan_Date__c, scanResultDeployment.CreatedDate);
		System.assertEquals('In Progress', deploymentUAT.Compliance_Status__c);

		Test.stopTest();
	}

	@isTest static void testDeleteScanResult() {
		TestUtilities.assignLicense(UserInfo.getUserName(), true, false, false, false, true);
		Git_Repository__c gitRepo = new Git_Repository__c(name = 'gitRepo');
		insert gitRepo;

		Environment__c envUAT = new Environment__c(Name = 'UAT Environment', Type__c = 'Sandbox');
		insert envUAT;

		Org__c orgUAT = CMTestMethodUtilities.createOrg('UAT Org', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), envUAT.Id);
		insert orgUAT;

		Git_Backup__c gitSnapshotUAT = new Git_Backup__c(Git_Repository__c = gitRepo.id, Org__c = orgUAT.id, Branch__c = 'master');
		insert gitSnapshotUAT;

		User_Story__c userStory1 = CMTestMethodUtilities.createUserStory('userStory1 UAT');
		userStory1.Org_Credential__c = orgUAT.Id;
		insert userStory1;

		Deployment__c deploymentUAT = new Deployment__c(name = 'test Deploypment', From_Org__c = orgUAT.Id);
		insert deploymentUAT;

		Compliance_Scan_Result__c scanResultUserStory = new Compliance_Scan_Result__c(Status__c = 'Completed - Findings detected', Environment__c = envUAT.Id, User_Story__c = userStory1.Id, Org_Credential__c = orgUAT.Id, Git_Snapshot__c = gitSnapshotUAT.Id, Deployment__c = deploymentUAT.Id);
		insert scanResultUserStory;
		scanResultUserStory = [SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultUserStory.Id];
		Test.setCreatedDate(scanResultUserStory.Id, Datetime.now().addDays(-2));

		Compliance_Scan_Result__c scanResultDeployment = new Compliance_Scan_Result__c(Status__c = 'Completed - Resolved', Environment__c = envUAT.Id, Org_Credential__c = orgUAT.Id, Deployment__c = deploymentUAT.Id);
		insert scanResultDeployment;
		scanResultDeployment = [SELECT Id, CreatedDate, Status__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultDeployment.Id];

		Test.startTest();

		envUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Environment__c WHERE Id = :envUAT.Id];
		System.assertEquals('Completed - Resolved', envUAT.Compliance_Status__c);

		orgUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Org__c WHERE Id = :orgUAT.Id];
		System.assertEquals('Completed - Resolved', orgUAT.Compliance_Status__c);

		userStory1 = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM User_Story__c WHERE Id = :userStory1.Id];
		System.assertEquals('Completed - Findings detected', userStory1.Compliance_Status__c);

		gitSnapshotUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Git_Backup__c WHERE Id = :gitSnapshotUAT.Id];
		System.assertEquals('Completed - Findings detected', gitSnapshotUAT.Compliance_Status__c);

		deploymentUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Deployment__c WHERE Id = :deploymentUAT.Id];
		System.assertEquals('Completed - Resolved', deploymentUAT.Compliance_Status__c);

		System.debug('### DELETE ScanResultDeployment');
		delete scanResultDeployment;

		envUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Environment__c WHERE Id = :envUAT.Id];
		System.assertEquals('Completed - Findings detected', envUAT.Compliance_Status__c);

		orgUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Org__c WHERE Id = :orgUAT.Id];
		System.assertEquals('Completed - Findings detected', orgUAT.Compliance_Status__c);

		userStory1 = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM User_Story__c WHERE Id = :userStory1.Id];
		System.assertEquals('Completed - Findings detected', userStory1.Compliance_Status__c);

		gitSnapshotUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Git_Backup__c WHERE Id = :gitSnapshotUAT.Id];
		System.assertEquals('Completed - Findings detected', gitSnapshotUAT.Compliance_Status__c);

		deploymentUAT = [SELECT Id, Compliance_Status__c, Last_Compliance_Scan_Date__c FROM Deployment__c WHERE Id = :deploymentUAT.Id];
		System.assertEquals('Completed - Findings detected', deploymentUAT.Compliance_Status__c);

		delete scanResultUserStory;
		undelete scanResultDeployment;

		Test.stopTest();

	}

	@isTest static void testUpdateScanResultSummaryFields() {
		TestUtilities.assignLicense(UserInfo.getUserName(), true, false, false, false, true);
        String ns = '';
        if([select id,name, namespacePrefix from apexclass where name='CopadoSetupController' and namespaceprefix='copado'].size()==1){
            ns = 'copado__';
        }

		Environment__c envUAT = new Environment__c(Name = 'UAT Environment', Type__c = 'Sandbox');
		insert envUAT;
		Org__c orgUAT = CMTestMethodUtilities.createOrg('UAT Org', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), envUAT.Id);
		insert orgUAT;

		Compliance_Scan_Result__c scanResultOrg = new Compliance_Scan_Result__c(Status__c = 'Completed - Findings detected', Environment__c = envUAT.Id, Org_Credential__c = orgUAT.Id);
		insert scanResultOrg;

		Map<String, String> severityPle = new Map<String, String>();
		for (Schema.PicklistEntry ple : Schema.getGlobalDescribe().get(ns+'Compliance_Rule__c').getDescribe().fields.getMap().get(ns+'Severity__c').getDescribe().getPicklistValues()) {
			severityPle.put(ple.getValue(), ple.getValue());
		}

		Map<String, String> actionPle = new Map<String, String>();
		for (Schema.PicklistEntry ple : Schema.getGlobalDescribe().get(ns+'Compliance_Rule__c').getDescribe().fields.getMap().get(ns+'Action__c').getDescribe().getPicklistValues()) {
			actionPle.put(ple.getValue(), ple.getValue());
		}
		Compliance_Rule__c rule1 = new Compliance_Rule__c(Name = 'Rule A', Severity__c = severityPle.get('Medium'), Action__c = actionPle.get('Continue with alert'));
		insert rule1;
		Compliance_Rule__c rule2 = new Compliance_Rule__c(Name = 'Rule A', Severity__c = severityPle.get('Critical'), Action__c = actionPle.get('Document Only'));
		insert rule2;

		Compliance_Finding__c findingRule1 = new Compliance_Finding__c(Compliance_Rule__c = rule1.Id, Compliance_Scan_Result__c = scanResultOrg.Id);
		insert findingRule1;

		scanResultOrg = [SELECT Id, Highest_Severity__c, Highest_Rule_Action__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultOrg.Id];
		System.assertEquals('Medium', scanResultOrg.Highest_Severity__c);
		System.assertEquals('Continue with alert', scanResultOrg.Highest_Rule_Action__c);

		Compliance_Finding__c findingRule2 = new Compliance_Finding__c(Compliance_Rule__c = rule2.Id, Compliance_Scan_Result__c = scanResultOrg.Id);
		insert findingRule2;

		scanResultOrg = [SELECT Id, Highest_Severity__c, Highest_Rule_Action__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultOrg.Id];
		System.assertEquals('Critical', scanResultOrg.Highest_Severity__c);
		System.assertEquals('Continue with alert', scanResultOrg.Highest_Rule_Action__c);

		delete findingRule1;
		scanResultOrg = [SELECT Id, Highest_Severity__c, Highest_Rule_Action__c FROM Compliance_Scan_Result__c WHERE Id = :scanResultOrg.Id];
		System.assertEquals('Critical', scanResultOrg.Highest_Severity__c);
		System.assertEquals('Document Only', scanResultOrg.Highest_Rule_Action__c);
	}
}