objects/Compliance_Finding__c.object
<CustomObject>
    <description>This object stores the individual findings of a Compliance Scan.  It is a junction object between the Compliance Scan and the Compliance Rule for which the findings have been found.</description>
    <fields>
        <fullName>Compliance_Rule__c</fullName>
        <label>Compliance Rule</label>
        <referenceTo>Compliance_Rule__c</referenceTo>
        <relationshipName>Compliance_Incidences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Compliance_Scan_Result__c</fullName>
        <label>Compliance Scan Result</label>
        <referenceTo>Compliance_Scan_Result__c</referenceTo>
        <relationshipLabel>Compliance Findings</relationshipLabel>
        <relationshipName>Compliance_Findings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <formula>TEXT(Compliance_Rule__r.Severity__c)</formula>
        <label>Severity</label>
        <type>Text</type>
    </fields>
    <label>Compliance Finding</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Compliance Finding Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Findings</pluralLabel>
    <recordTypes>
        <fullName>Copado</fullName>
        <active>true</active>
        <description>This record type is used for scan findings produced by Copado.</description>
        <label>Copado</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Compliance_Rule__c.object
<CustomObject>
    <description>This object stores the compliance rule definition.</description>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Compliance_Action</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Compliance_Severity</valueSetName>
        </valueSet>
    </fields>
    <label>Compliance Rule</label>
    <nameField>
        <label>Compliance Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compliance Rules</pluralLabel>
    <recordTypes>
        <fullName>Copado</fullName>
        <active>true</active>
        <description>Use this record type to define scan rules run by Copado.</description>
        <label>Copado</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Compliance_Scan_Result__c.object
<CustomObject>
    <description>This object stores the results of a compliance scan</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Compliance Scan Results</relationshipLabel>
        <relationshipName>Compliance_Scan_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Completed - No Findings</fullName>
                </value>
                <value>
                    <fullName>Completed - Findings detected</fullName>
                </value>
                <value>
                    <fullName>Completed - Resolved</fullName>
                </value>
                <value>
                    <fullName>Under Investigation</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compliance Scan Result</label>
    <nameField>
        <displayFormat>Scan Result - {000000000}</displayFormat>
        <label>Scan Result Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Scan Results</pluralLabel>
    <recordTypes>
        <fullName>Copado</fullName>
        <active>true</active>
        <description>This record type is used for scan results produced by Copado.</description>
        <label>Copado</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestComplianceFindingTriggerHandler.cls
@isTest
private class TestComplianceFindingTriggerHandler {
	@testSetup static void setupData() {
		TestUtilities.enableLicenses(2, 0, 0, 0, 2);
	}
	@isTest static void testComplianceFindings() {
		TestUtilities.assignLicense(UserInfo.getUserName(), true, false, false, false, true);
        String ns = '';
        if([select id,name, namespacePrefix from apexclass where name='CopadoSetupController' and namespaceprefix='copado'].size()==1){
            ns = 'copado__';
        }
        system.debug(ns);
		Environment__c envUAT = new Environment__c(Name='UAT Environment',Type__c='Sandbox');
        insert envUAT;
        Org__c orgUAT = CMTestMethodUtilities.createOrg('UAT Org', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), envUAT.Id);
        insert orgUAT;

        Compliance_Scan_Result__c scanResultOrg = new Compliance_Scan_Result__c(Status__c = 'Completed - Findings detected', Environment__c = envUAT.Id, Org_Credential__c = orgUAT.Id);
		insert scanResultOrg;
		List<Schema.PicklistEntry> severityPle = Schema.getGlobalDescribe().get(ns+'Compliance_Rule__c').getDescribe().fields.getMap().get(ns+'Severity__c').getDescribe().getPicklistValues();
		List<Schema.PicklistEntry> actionPle = Schema.getGlobalDescribe().get(ns+'Compliance_Rule__c').getDescribe().fields.getMap().get(ns+'Action__c').getDescribe().getPicklistValues();
		Compliance_Rule__c rule1 = new Compliance_Rule__c(Name = 'Rule A', Severity__c = severityPle[0].getValue(), Action__c = actionPle[0].getValue());
		insert rule1;
		Compliance_Rule__c rule2 = new Compliance_Rule__c(Name = 'Rule A', Severity__c = severityPle[1].getValue(), Action__c = actionPle[1].getValue());
		insert rule2;

		Compliance_Finding__c findingRule1 = new Compliance_Finding__c(Compliance_Rule__c = rule1.Id, Compliance_Scan_Result__c = scanResultOrg.Id);
		insert findingRule1;
		System.assertEquals(true, findingRule1.Id != null);
		update findingRule1;
		delete findingRule1;
		undelete findingRule1;
    }
}