objects/Compliance_Finding__c.object
<CustomObject>
    <description>This object stores the individual findings of a Compliance Scan.  It is a junction object between the Compliance Scan and the Compliance Rule for which the findings have been found.</description>
    <fields>
        <fullName>Compliance_Scan_Result__c</fullName>
        <label>Compliance Scan Result</label>
        <referenceTo>Compliance_Scan_Result__c</referenceTo>
        <relationshipLabel>Compliance Findings</relationshipLabel>
        <relationshipName>Compliance_Findings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Compliance Finding</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Compliance Finding Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Findings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Compliance_Scan_Result__c.object
<CustomObject>
    <description>This object stores the results of a compliance scan</description>
    <label>Compliance Scan Result</label>
    <nameField>
        <displayFormat>Scan Result - {000000000}</displayFormat>
        <label>Scan Result Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Scan Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ComplianceFindingTriggerHelper.cls
public with sharing class ComplianceFindingTriggerHelper {
	
	public static void updateComplianceScanResults() {
		Set<Id> scanResultIds = new Set<Id>();

		if(Trigger.New != null) {
			for(SObject so : Trigger.New) {
				Compliance_Finding__c finding = (Compliance_Finding__c)so;
	            scanResultIds.add(finding.Compliance_Scan_Result__c);
	        }
		}

		if(Trigger.isDelete) {
			for(SObject so : Trigger.Old) {
				Compliance_Finding__c finding = (Compliance_Finding__c)so;
	            scanResultIds.add(finding.Compliance_Scan_Result__c);
	        }
		}

		List<Compliance_Scan_Result__c> scanResults = [SELECT Id FROM Compliance_Scan_Result__c WHERE Id IN :scanResultIds];
		System.debug('### Compliance Scan Results to Update:'+scanResults);
		Utilities.Secure_DML(scanResults, Utilities.DML_Action.UPD, schema.Sobjecttype.Compliance_Scan_Result__c);
	}
}