objects/Copado_Notification__c.object
<CustomObject>
    <description>Used for Copado Notifications using the Streaming API.</description>
    <fields>
        <fullName>Matching_Key__c</fullName>
        <label>Matching Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>ParentId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isFinished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finished</label>
        <type>Checkbox</type>
    </fields>
    <label>Copado Notification</label>
    <nameField>
        <label>CopadoNotification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Copado Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <defaultValue>&quot;master&quot;</defaultValue>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestCreateUSScratchOrg.cls
/**
 * Created by ferhatozsavran on 2/28/18.
 */

@isTest
private class  TestCreateUSScratchOrg {

    @testSetup static void setup() {
        // Create common test records
        insert TestUtilities.getTestSettings();
        TestUtilities.assignLicense(UserInfo.getUserName(), true, true, true, true, true);
        TestUtilities.createAllDXTestData();
    }

    @isTest static void createUserStoryScratchOrg(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.CreateUserStoryScratchOrg;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);

        User_Story__c us = [Select Id,Name, Org_Credential__c From User_Story__c Where User_Story_Title__c =: 'Error on dx operation 2'];
        pageRef.getParameters().put('Id', us.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(us);

        //Instantiate and construct the controller class of DX Operation page.
        CreateUserStoryScratchOrgController controller = new CreateUserStoryScratchOrgController(sc);

        controller.getMyComponentController();

        ScratchOrgController socController = new ScratchOrgController();
        socController.componentMode = 'wizard';
        socController.showTemplateButtons = false;
        socController.showButtons = true;
        socController.pageController = controller;
        socController.controllerKey = 'ScratchOrgTemplate';

        controller.nextStep(); // it will return because dev hub org id is not selected

        socController.orgTemplate.orgName = 'FO test';

        Org__c devHubOrg = [Select Id From Org__c Where Name =: 'Dev Hub 1'];
        socController.devHubOrgId = devHubOrg.Id;

        controller.nextStep();
        controller.previousStep();
        controller.nextStep();

        //Instantiate and construct the controller class of component.
        ScratchOrgMetadataController somcController = new ScratchOrgMetadataController();
        somcController.componentMode = 'wizard';
        somcController.showTemplateButtons = false;
        somcController.showButtons = true;
        somcController.pageController = controller;
        somcController.controllerKey = 'ScratchOrgMetadata';
        somcController.typeName = 'branch';
        somcController.showPatchOptions = false;

        //Select git repository and populate grid panel
        Git_Repository__c gr = [Select Id, Name From Git_Repository__c Where Name =: 'git 1'];
        somcController.repoId = gr.Id;
        somcController.repoName = gr.Name;

        //Select git snapshot from grid panel and populate branch name parameter at dxoperation controller
        Git_Backup__c gb = [Select Id, Branch__c From Git_Backup__c Where Git_Repository__c =: gr.Id];

        //Select branch and render artifact panels
        ApexPages.currentPage().getParameters().put('nextStepParam', gb.Branch__c);

        controller.nextStep();
        system.assertEquals('COMPLETE',controller.definition);
        controller.previousStep();
        controller.nextStep();

        ScratchOrgCompletionController soccController = new ScratchOrgCompletionController();
        soccController.componentMode = 'wizard';
        soccController.showTemplateButtons = false;
        soccController.showButtons = true;
        soccController.pageController = controller;
        soccController.controllerKey = 'ScratchOrgCompletion';

        soccController.createFullScratchOrg();
        ApexPages.currentPage().getParameters().put('csvPerm', '');
        //soccController.getSelectedPermissionSets();

        Test.startTest();
        MockHttpResponseGenerator fakeResponse = new MockHttpResponseGenerator(200,'Complete','{"example":"test"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        controller.nextStep();

        //run the event listener job for create org job
        ApexPages.currentPage().getParameters().put('jobFinished', 'true');
        ApexPages.currentPage().getParameters().put('jobSuccess', 'true');
        ApexPages.currentPage().getParameters().put('jobMessage', '');
        ApexPages.currentPage().getParameters().put('jobType', CopadoNotificationHelper.DX_CREATE_FULL_ORG);
        controller.jobStatusNotification();
        Test.stopTest();

        soccController.showDeploymentFlow = true;
        soccController.deploymentFlowOperations();
    }

    @isTest static void scratchOrgOpen(){
        //Use the PageReference Apex class to instantiate a page
        PageReference pageRef = Page.ScratchOrgOpen;

        //In this case, the Visualforce page named 'DXOperation' is the starting point of this test method.
        Test.setCurrentPage(pageRef);

        Org__c orgScratch = [Select Id, Environment__c From Org__c Where Name =: 'Scratch Org 1'];

        Copado_Notification__c cn = new Copado_Notification__c();
        cn.Type__c = CopadoNotificationHelper.DX_OPEN_ORG;
        cn.OwnerId = UserInfo.getUserId();
        cn.isFinished__c = false;
        cn.ParentId__c = orgScratch.Id;
        cn.Matching_Key__c = 'testmatching';
        insert cn;

        pageRef.getParameters().put('id',orgScratch.Id);

        //Instantiate and construct the controller class of DX Operation page.
        ScratchOrgOpen sooController = new ScratchOrgOpen();

        system.assertEquals(null,sooController.copadoJobFinished);

        //Open scratch org
        Test.startTest();
        MockHttpResponseGenerator fakeResponseCopadoId = new MockHttpResponseGenerator(200,'Complete','{"test":"123456789012345678"}',null);
        Test.setMock(HttpCalloutMock.class, fakeResponseCopadoId);
        sooController.rScratchOrgJob();
        Test.stopTest();
    }
}