objects/Copado_Smart_Help__mdt.object
<CustomObject>
    <fields>
        <fullName>Base_Page__c</fullName>
        <label>Base Page</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GitCommitChanges</fullName>
                    <default>true</default>
                    <label>GitCommitChanges</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Triggering_Action__c</fullName>
        <label>Triggering Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Copado Metadata Grid selection</fullName>
                    <default>true</default>
                    <label>Copado Metadata Grid selection</label>
                </value>
                <value>
                    <fullName>Always show</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Triggering_Value__c</fullName>
        <label>Triggering Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Copado Smart Help</label>
    <pluralLabel>Copado Smart Helps</pluralLabel>
</CustomObject>

classes/TestCopadoSmartHelpController.cls
@isTest
private class TestCopadoSmartHelpController {
	static testMethod void testTips() {
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
		User u = new User(Alias = 'standt', Email = 'myTester@testorg.com',
		                  EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
		                  LocaleSidKey = 'en_US', ProfileId = p.Id, Show_Copado_Tips__c = true,
		                  TimeZoneSidKey = 'America/Los_Angeles', UserName = 'myTester@testorg.com');

		System.runAs(u) {
			CopadoSmartHelpController handler = new CopadoSmartHelpController();
			handler.setTypeList();
			System.assertEquals(0,handler.helpList.size());
			handler.vfPageName = 'GitCommitChanges';
			List<Copado_Smart_Help__mdt> alwaysList = new List<Copado_Smart_Help__mdt>([SELECT
		                                   Base_Page__c,
		                                   DeveloperName,
		                                   Help_Text__c,
		                                   Id,
		                                   Label,
		                                   Triggering_Action__c,
		                                   Triggering_Value__c
		                                   FROM Copado_Smart_Help__mdt
		                                   WHERE Base_Page__c = : handler.vfPageName AND Triggering_Action__c = 'Always Show']);
			handler.tipType = 'Report';

			handler.setHelpList();
			System.assertEquals(alwaysList.size(),handler.helpList.size());
			List<Copado_Smart_Help__mdt> gridList = new List<Copado_Smart_Help__mdt>([SELECT
		                                   Base_Page__c,
		                                   DeveloperName,
		                                   Help_Text__c,
		                                   Id,
		                                   Label,
		                                   Triggering_Action__c,
		                                   Triggering_Value__c
		                                   FROM Copado_Smart_Help__mdt
		                                   WHERE Base_Page__c = : handler.vfPageName AND Triggering_Action__c != 'Always Show'
		                                           AND DeveloperName NOT IN: handler.removedTips AND Triggering_Value__c = : handler.tipType
		                                                   ORDER BY Triggering_Value__c]);

			handler.setTypeList();
			System.assertEquals(alwaysList.size() + gridList.size(),handler.helpList.size());
			if(!gridList.isEmpty()){
				handler.removeTip();
				handler.tipKey = gridList[0].DeveloperName;
				handler.removeTip();
				System.assertEquals(alwaysList.size() + gridList.size() -1,handler.helpList.size());
			} else{
				handler.removeTip();
			}
		}
	}
}