objects/Copado_License__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enable_CCM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable CCM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Copado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Copado</label>
        <type>Checkbox</type>
    </fields>
    <label>Copado License</label>
</CustomObject>

objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
        <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <defaultValue>&quot;master&quot;</defaultValue>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Git_Snapshot_Permissions__c</fullName>
        <label>Git Snapshot Permissions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Allow Snapshots &amp; Commits</fullName>
                    <default>true</default>
                    <label>Allow Snapshots &amp; Commits</label>
                </value>
                <value>
                    <fullName>Allow Snapshots Only</fullName>
                </value>
                <value>
                    <fullName>Allow Commits Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Frequency__c</fullName>
        <description>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</description>
        <inlineHelpText>Continuous Integration feature. Run all Apex Test methods and save the results in the Apex Test Result object to create email alerts or reports. This feature is very powerful along with Git Backups to detect recent failing changes automatically.</inlineHelpText>
        <label>Test Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCopadoSetupController.cls
@isTest
private class TestCopadoSetupController {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }

    static testMethod void test() {
        //user creation
        User u = new User(
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
                FirstName = 'first',
                LastName = 'last',
                Email = 'puser000@test.com',
                Username = 'puser000@test.com' + System.currentTimeMillis(),
                CompanyName = 'TEST',
                Title = 'title',
                Alias = 'alias',
                TimeZoneSidKey = 'America/Los_Angeles',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US'
        );
        insert u;

        List<Org__c> orgCredentialList = new List<Org__c>();
        //add this org
        Org__c o = testMethodUtilities.create('this org', 'Production/Developer', '', '', '', '', System.now());
        orgCredentialList.add(o);
        //add a 2nd org
        Org__c o2 = testMethodUtilities.create('org2', 'Production/Developer', '', '', '', '', System.now());
        orgCredentialList.add(o2);
        //add a 3rd org
        Org__c o3 = testMethodUtilities.create('org3', 'Production/Developer', '', '', '', '', System.now());
        orgCredentialList.add(o3);

        insert orgCredentialList;

        //add a git repository
        Git_Repository__c g = testMethodUtilities.create('git 1','test un','test pw','https://git.com');
        insert g;

        //add a git snapshot
        Git_Backup__c s = testMethodUtilities.create('my first git snapshot', 'master', '', g, Date.today(), o);
        insert s;

        Deployment_Flow__c df = new Deployment_Flow__c();
        df.Name = 'Deployment Flow';
        df.Active__c = true;
        insert df;

        Copado_License__c lc = Copado_License__c.getInstance();
        lc.SetupOwnerId = u.Id;
        lc.Enable_CCM__c = true;
        lc.Enable_Copado__c = false;
        upsert lc;

        ApexPages.currentPage().getParameters().put('setOauth',o.Id);

        CopadoSetupController con = new CopadoSetupController();

        //retrieving the org credentials
        con.getExistingOrgCredentials();
        System.assertEquals(3,con.orgCredentialMap.size());

        //refreshing the org credential panels
        con.refreshOrgCredentialList();

        //creating new org credentials
        con.orgCredentials.Name = 'New Org';
        con.orgCredentials.Org_Type__c = 'Production/Developer';
        con.orgCredentials.Test_Frequency__c = 'Daily';
        con.createOrgCredentials();
        con.getExistingOrgCredentials();
        System.assertEquals(4,con.orgCredentialMap.size());

        //set oauth authentication
        con.doOauth();

        //get current user`s api key
        con.getAPIKey();

        //get git repos
        con.getGitRepos();

        //get git snapshots depend on the selected git repos
        con.selectedGitRepositories = 'none';
        con.getsGitSnapshots();  // it will cover if condition
        con.selectedGitRepositories = g.Id;
        con.getsGitSnapshots(); // it will cover else condition

        //open new git snapshot form
        con.openGitSnapshotForm();

        //creating new git snapshot
        con.createGitSnapshot(); // returned becuase name is null
        System.assertEquals(null,con.gitSnapshot.Name);
        con.gitSnapshot.Name = 'Git Snapshot';
        con.createGitSnapshot(); // returned because branch is null
        System.assertEquals(null,con.gitSnapshot.Branch__c);
        con.gitSnapshot.Branch__c = 'master';
        con.createGitSnapshot(); // returned because permission is null
        System.assertEquals(null,con.gitSnapshot.Git_Snapshot_Permissions__c);
        con.gitSnapshot.Git_Snapshot_Permissions__c = 'Allow Commit Only';
        con.createGitSnapshot(); // returned because org credential is null
        System.assertEquals(null,con.gitSnapshot.Org__c);
        con.gitSnapshot.Org__c = o.Id;
        con.createGitSnapshot(); // inserted git snapshot successfully

        //get deployment flows
        con.getDeploymentFlows();

        //get deployment flow steps depend on selected deployment flow
        con.selectedDeploymentFlow = 'none';
        con.getsDeploymentFlowSteps(); // covers if condition

        //open new deployment flow form
        con.openDeploymentFlowForm();

        //create new deployment flow
        con.createDeploymentFlow(); // returned becuase name is null
        System.assertEquals(null,con.deploymentFlow.Name);
        con.deploymentFlow.Name = 'New Deployment Flow';
        con.createDeploymentFlow(); // inserted deployment flow successfully

        //get deployment flow steps depend on selected deployment flow to cover else condition
        con.selectedDeploymentFlow = df.Id;
        con.getsDeploymentFlowSteps(); // covers else

        //open new deployment flow step to create new one
        con.openDeploymentFlowStepForm();

        //insert deployment flow step
        con.createDeploymentFlowSteps();

        //close deployment flow form
        con.closeDeploymentFlowForm();

        //close deployment flow step form
        con.closeDeploymentFlowStepsForm();

        //close git snapshot form
        con.closeGitSnapshotForm();
    }
}