objects/Copado_License__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enable_CAD__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable CAD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_CCH__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable CCH</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_CCM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable CCM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_CST__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable CST</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Copado__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Copado</label>
        <type>Checkbox</type>
    </fields>
    <label>Copado License</label>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Git_Snapshot_Permissions__c</fullName>
        <label>Git Snapshot Permissions</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Allow Snapshots &amp; Commits</fullName>
                    <default>true</default>
                    <label>Allow Snapshots &amp; Commits</label>
                </value>
                <value>
                    <fullName>Allow Snapshots Only</fullName>
                </value>
                <value>
                    <fullName>Allow Commits Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the backup only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestEditBackupExtension.cls
@isTest
public class TestEditBackupExtension {
    @testSetup static void setupData() {
        TestUtilities.getTestSettingsMultilicense();
    }
    
    @isTest static void testSuccess() {
        Copado_License__c license = Copado_License__c.getInstance();
        license.Enable_CCM__c=FALSE;
        license.Enable_Copado__c=TRUE;
        license.Enable_CST__c=FALSE;
        license.Enable_CAD__c=FALSE;
        license.Enable_CCH__c=FALSE;
        insert license;
        
        Git_Repository__c gitRepo = testMethodUtilities.create('%$£GFDS!P@Copado_test2','Username','PASSWORD','http://www.bitbucket.org/');
        insert gitRepo;
        Org__c org = testMethodUtilities.create('OrgName','Production','PASSWORD','SFDC_OrgId2','SFDC_TOKEN','USERNAME', System.now());
        org.Metadata_Types__c = 'ApexClass,ApexPage';
        insert org;
        List<String> types = new List<String>();
		types.add('ApexClass');
		types.add('ApexPage');
		MetadataTypesHelper.metadataTypes = types;
        
        // Start with null Git Backup
        Git_Backup__c gitBackup = new Git_Backup__c();        
        PageReference pref = Page.EditGitBackup;
	    pref.getParameters().put('id',null);
	    Test.setCurrentPage(pref);
        
        EditBackupExtension ext = new EditBackupExtension(new ApexPages.StandardController(gitBackup));
	    ext.backup = testMethodUtilities.create('DemoBackup', 'master', 'None', gitRepo, null, org);
        ext.setTypes(ext.GetTypes());
        System.assertEquals(2,ext.types.size());
        System.assertEquals(2,ext.GetMetadataTypes().size());
        System.assertEquals(2,ext.GetTypes().size());
        System.assertEquals(4,ext.GetFrequencyOptions().size());
        ext.init();
        ext.reRender();
        
        ext.orgChanged();
        ext.backup.Org__c = org.Id;
        
		pref = ext.save();
		System.assert(pref.getUrl() != Page.editOrg.getUrl());
    }
    @isTest static void testError() {
        Copado_License__c license = Copado_License__c.getInstance();
        license.Enable_CCM__c=FALSE;
        license.Enable_Copado__c=TRUE;
        license.Enable_CST__c=FALSE;
        license.Enable_CAD__c=FALSE;
        license.Enable_CCH__c=FALSE;
        insert license;

        TestUtilities.insertUser('TestEditBackupExtension_Error@test.com','System Administrator');
        User user  = [Select Id, Name From User Where Username = 'TestEditBackupExtension_Error@test.com' Limit 1];
        license.SetupOwnerId = user.Id;
        update license;
        System.runAs(user)
        {
        
            Git_Repository__c gitRepo = testMethodUtilities.create('%$£GFDS!P@Copado_test2','Username','PASSWORD','http://www.bitbucket.org/');
            insert gitRepo;
            Org__c org = testMethodUtilities.create('OrgName','Production','PASSWORD','SFDC_OrgId2','SFDC_TOKEN','USERNAME', System.now());
            insert org;
            
            // Start with null Git Backup
            Git_Backup__c gitBackup = new Git_Backup__c();        
            PageReference pref = Page.EditGitBackup;
    	    pref.getParameters().put('id',null);
    	    Test.setCurrentPage(pref);
            
            EditBackupExtension ext = new EditBackupExtension(new ApexPages.StandardController(gitBackup));
    	    ext.backup = testMethodUtilities.create('DemoBackup', 'master', 'Daily', gitRepo, null, org);
            
            Test.startTest();
            TestUtilities.exceedCopadoLicenses();
            pref = ext.save();

            //TODO: refactor. license exeeded cannot be tested like this since LMO featue management.
            //System.assert(testMethodUtilities.hasMessage(Label.LICENSES_EXCEEDED));
            //TestUtilities.enableLicenses(2, 2, 2);

            ext.backup.Git_Snapshot_Permissions__c = 'Allow Commits Only';

    		pref = ext.save();
    		System.assert(testMethodUtilities.hasMessage(Label.COMMIT_ONLY_SNAPSHOTS_CANNOT_BE_SCHEDULED));
            Test.stopTest();
        }
        
    }
    @isTest static void testExistingGitBackup() {
        testMethodUtilities.upsertOrgwideSettings();
        Copado_License__c license = Copado_License__c.getInstance();
        license.Enable_CCM__c=FALSE;
        license.Enable_Copado__c=TRUE;
        license.Enable_CST__c=FALSE;
        license.Enable_CAD__c=FALSE;
        license.Enable_CCH__c=FALSE;
        insert license;

        
       	Git_Repository__c gitRepo = testMethodUtilities.create('%$£GFDS!P@Copado_test2','Username','PASSWORD','http://www.bitbucket.org/');
        insert gitRepo;
        Org__c org = testMethodUtilities.create('OrgName','Production','PASSWORD','SFDC_OrgId2','SFDC_TOKEN','USERNAME', System.now());
        org.Metadata_Types__c = 'ApexClass,ApexPage,StaticResource';
        insert org;
        Org__c org2 = testMethodUtilities.create('OrgName2','Production','PASSWORD2','SFDC_OrgId3','SFDC_TOKEN','USERNAME2', System.now());
        insert org2;
        
        Git_Backup__c gitBackup = testMethodUtilities.create('backupname', 'branchName', 'Daily', gitRepo, null, org);
        gitBackup.Metadata_Types__c = 'ApexClass,ApexPage,StaticResource';
        insert gitBackup;
        
        Test.startTest();
	    PageReference pref = Page.EditGitBackup;
	    pref.getParameters().put('id',gitBackup.Id);
	    Test.setCurrentPage(pref);
        
	    EditBackupExtension ext = new EditBackupExtension(new ApexPages.StandardController(gitBackup));
		System.assert(ext.backup != null);
        System.assertEquals(3,ext.selectedTypes.size());
        System.assert(ext.isStaticResourcesSelected);

		gitBackup.Metadata_Types__c = null;
        update gitBackup;
        PageReference pref2 = Page.EditGitBackup;
	    pref2.getParameters().put('id',gitBackup.Id);
	    Test.setCurrentPage(pref2);
        
	    EditBackupExtension ext2 = new EditBackupExtension(new ApexPages.StandardController(gitBackup));
        System.assert(ext2.isStaticResourcesSelected);         
        Test.stopTest();
    }
}