objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Deployments</relationshipLabel>
        <relationshipName>Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Commits</relationshipLabel>
        <relationshipName>Git_Org_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Deployment Flow.</inlineHelpText>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Promoted_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>Promotion__c</fullName>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Promoted User Stories</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Promotions</relationshipLabel>
        <relationshipName>Promoted_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promoted User Story</label>
    <nameField>
        <label>Promoted User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promoted User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The selected Project should be linked to an active Deployment Flow</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will provide the ability to deploy User Stories within a Release.</description>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Base_Branch__c</fullName>
        <description>All user story feature branches are created out of the main branch of the Deployment Flow. If a Release base branch is specified, all feature branches of user stories linked to the Release will be created out of the base branch.</description>
        <inlineHelpText>All user story feature branches are created out of the main branch of the Deployment Flow. If a Release base branch is specified, all feature branches of user stories linked to the Release will be created out of the base branch.</inlineHelpText>
        <label>Base Branch</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Base_Branch__c</fullName>
        <description>Git branch which the feature branch is created from. This value is updated when committing in the user story and by default, it will be the main branch of the Deployment Flow or the base branch of the Release linked to the user story.</description>
        <inlineHelpText>Git branch which the feature branch is created from. This value is updated when committing in the user story and by default, it will be the main branch of the Deployment Flow or the base branch of the Release linked to the user story.e user story.</inlineHelpText>
        <label>Base Branch</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestUserStoryExt.cls
@isTest
public class TestUserStoryExt {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }
	static testMethod void testDeploymentFlow(){   
        insert TestUtilities.getTestSettings();
        Project__c testProject = CMTestMethodUtilities.createProject('My Project');
        Environment__c envDev1 = CMTestMethodUtilities.createEnvironment('Dev1', 'SFDC_OrgId');
        Environment__c envDev2 = CMTestMethodUtilities.createEnvironment('Dev2', 'SFDC_OrgId2');
        Environment__c envInt = CMTestMethodUtilities.createEnvironment('Int', 'SFDC_OrgId3');
        Environment__c envUAT = CMTestMethodUtilities.createEnvironment('UAT', 'SFDC_OrgId4');
        Environment__c envProd = CMTestMethodUtilities.createEnvironment('Prod', 'SFDC_OrgId5');
        insert new List<Environment__c>{envDev1, envDev2, envInt, envUAT, envProd};

        Org__c orgDev1 = CMTestMethodUtilities.createOrg('OrgDev1', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), envDev1.Id);
        Org__c orgDev2 = CMTestMethodUtilities.createOrg('OrgDev2', 'Sandbox', null, 'SFDC_OrgId2', null, null, system.now(), envDev2.Id);
        Org__c orgInt = CMTestMethodUtilities.createOrg('OrgInt', 'Sandbox', null, 'SFDC_OrgId3', null, null, system.now(), envInt.Id);
        Org__c orgUAT = CMTestMethodUtilities.createOrg('OrgUAT', 'Sandbox', null, 'SFDC_OrgId4', null, null, system.now(), envUAT.Id);
        Org__c orgProd = CMTestMethodUtilities.createOrg('OrgProd', 'Production', null, 'SFDC_OrgId5', null, null, system.now(), envProd.Id);
        insert new List<Org__c>{orgDev1, orgDev2, orgInt, orgUAT, orgProd};
        
        Deployment_Flow__c flow = CMTestMethodUtilities.createCCMFlow('Standard flow', true);
        insert flow;
        Deployment_Flow_Step__c dfs1 = CMTestMethodUtilities.createFlowStep(envDev1.Id, envInt.Id, flow.Id);
        Deployment_Flow_Step__c dfs2 = CMTestMethodUtilities.createFlowStep(envDev2.Id, envInt.Id, flow.Id);
        Deployment_Flow_Step__c dfs3 = CMTestMethodUtilities.createFlowStep(envInt.Id, envUAT.Id, flow.Id);
        Deployment_Flow_Step__c dfs4 = CMTestMethodUtilities.createFlowStep(envUAT.Id, envProd.Id, flow.Id);
        insert new List<Deployment_Flow_Step__c>{dfs1, dfs2, dfs3, dfs4};

        testProject.Deployment_Flow__c = flow.Id;
        insert testProject;

        Release__c release = CMTestMethodUtilities.createRelease('Release1');
        release.Project__c = testProject.Id;
        release.Base_Branch__c = 'int';
        insert release;
        
        User_Story__c userStory = CMTestMethodUtilities.createUserStory('MyStory1');
        userStory.Project__c = testProject.Id;
        insert userStory;
                
        Test.startTest();
        UserStoryExt ext = new UserStoryExt(new ApexPages.StandardController(userStory));
        System.assertEquals(false, ext.hasActiveDeploymentFlow);
        System.assertEquals(0, ext.visualFlowSteps.size());
        UserStoryExt.getisChatterEnabled();
        
        userStory.Environment__c = envDev1.Id;
        userStory.Org_Credential__c = orgDev1.Id;
        update userStory;
        UserStoryExt ext2 = new UserStoryExt(new ApexPages.StandardController(userStory));
        System.assertEquals(true, ext2.hasActiveDeploymentFlow);
        System.assertEquals(4, ext2.visualFlowSteps.size());

        Promotion__c promotionDev1ToInt = CMTestMethodUtilities.createPromotion(testProject.Id, envDev1.Id);
        promotionDev1ToInt.Status__c = 'Completed';
        insert promotionDev1ToInt;
        Promoted_User_Story__c promotedUserStory1 = new Promoted_User_Story__c(User_Story__c = userStory.Id, Promotion__c = promotionDev1ToInt.Id);
        insert promotedUserStory1;
        userStory.Environment__c = envInt.Id;
        userStory.Org_Credential__c = orgInt.Id;
        update userStory;
        UserStoryExt ext3 = new UserStoryExt(new ApexPages.StandardController(userStory));
        System.assertEquals(true, ext3.hasActiveDeploymentFlow);
        System.assertEquals(4, ext3.visualFlowSteps.size());

        userStory.Environment__c = envUAT.Id;
        userStory.Org_Credential__c = orgUAT.Id;
        userStory.Project__c = null;
        userStory.Release__c = release.Id;
        update userStory;
        UserStoryExt ext4 = new UserStoryExt(new ApexPages.StandardController(userStory));
        System.assertEquals(true, ext4.hasActiveDeploymentFlow);
        // The size is only 2 since there is no Promotion from Int to UAT
        System.assertEquals(2, ext4.visualFlowSteps.size());

        Promotion__c promotionIntToUAT = CMTestMethodUtilities.createPromotion(testProject.Id, envInt.Id);
        promotionIntToUAT.Status__c = 'Completed';
        insert promotionIntToUAT;
        Promoted_User_Story__c promotedUserStory2 = new Promoted_User_Story__c(User_Story__c = userStory.Id, Promotion__c = promotionIntToUAT.Id);
        insert promotedUserStory2;
        userStory.Base_Branch__c = 'master';
        update userStory;
        UserStoryExt ext5 = new UserStoryExt(new ApexPages.StandardController(userStory));
        // Since there is a Promotion from Int to UAT, the path is complete from Dev1 to Prod
        System.assertEquals(4, ext5.visualFlowSteps.size());
        System.assertEquals(true, ext5.hasActiveDeploymentFlow);
        System.assertEquals(true, testMethodUtilities.hasMessage(Label.USER_STORY_BASE_BRANCH_CONFLICT));

        Test.stopTest();
    }
    static testMethod void testValidationDeployment(){
        insert TestUtilities.getTestSettings();
        Project__c testProject = CMTestMethodUtilities.createProject('My Project');
        Environment__c envDev1 = CMTestMethodUtilities.createEnvironment('Dev1', 'SFDC_OrgId');
        Environment__c envInt = CMTestMethodUtilities.createEnvironment('Int', 'SFDC_OrgId3');
        insert new List<Environment__c>{envDev1, envInt};

        Org__c orgDev1 = CMTestMethodUtilities.createOrg('OrgDev1', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), envDev1.Id);
        Org__c orgInt = CMTestMethodUtilities.createOrg('OrgInt', 'Sandbox', null, 'SFDC_OrgId3', null, null, system.now(), envInt.Id);
        insert new List<Org__c>{orgDev1, orgInt};
        
        Deployment_Flow__c flow = CMTestMethodUtilities.createCCMFlow('Standard flow', true);
        insert flow;
        Deployment_Flow_Step__c dfs1 = CMTestMethodUtilities.createFlowStep(envDev1.Id, envInt.Id, flow.Id);
        insert new List<Deployment_Flow_Step__c>{dfs1};

        testProject.Deployment_Flow__c = flow.Id;
        insert testProject;

        Release__c release = CMTestMethodUtilities.createRelease('Release1');
        release.Project__c = testProject.Id;
        insert release;
        
        User_Story__c userStory = CMTestMethodUtilities.createUserStory('MyStory1');
        insert userStory;     

        UserStoryExt ext1 = new UserStoryExt(new ApexPages.StandardController(userStory));

        ext1.validateUserStory();
        System.assertEquals(false, ext1.enablePoller);
        ext1.waitForDeployment();
        System.assertEquals(false, ext1.enablePoller);
        System.assertEquals(false, ext1.showHideMsg);
        ext1.getIsPollerEnabled();
        System.assertEquals(false, ext1.enablePoller);

        userStory.Project__c = testProject.Id;
        userStory.Environment__c = envDev1.Id;
        userStory.Org_Credential__c = orgDev1.Id;
        update userStory;     

        UserStoryExt ext2 = new UserStoryExt(new ApexPages.StandardController(userStory));

        String uri = '/json/v1/promote/_someId_?sid=_sessionId_&url=_endPoint_&deploy=true&deploymentName=PromotedStory-test&checkOnly=false&singleStep=false&testLevel=NoTestRun';
        Test.setMock(HttpCalloutMock.class, new testHttpCalloutMock('{}', null));

        ext2.validateUserStory();
        System.assertEquals(true, ext2.enablePoller);
        ext2.waitForDeployment();
        System.assertEquals(true, ext2.enablePoller);
        System.assertEquals(false, ext2.showHideMsg);        
        ext2.getIsPollerEnabled();
        System.assertEquals(true, ext2.enablePoller);

        Promoted_User_Story__c pus = [SELECT Id, Promotion__c FROM Promoted_User_Story__c WHERE User_Story__c = :userStory.Id LIMIT 1];
        System.assertEquals(true, pus != null);
        Deployment__c deployment1 = testMethodUtilities.create('DEPLOYMENT_NAME',System.now(), System.now(), orgDev1.Id, 'Deploy now', 'Scheduled');
        deployment1.Promotion__c = pus.Promotion__c;
        insert deployment1;
        System.assertEquals(true, deployment1.Id != null);

        ext2.waitForDeployment();
        System.assertEquals(true, ext2.enablePoller);
        System.assertEquals(true, ext2.showHideMsg); 
        ext2.getIsPollerEnabled();
        System.assertEquals(true, ext2.enablePoller);

        userStory = [SELECT Id, Last_Validation_Deployment__c FROM User_Story__c WHERE Id = :userStory.Id];
        System.assertEquals(deployment1.Id, userStory.Last_Validation_Deployment__c);       
    }

    static testMethod void testRelatedAlerts() {
        insert TestUtilities.getTestSettings();
        User_Story__c userStory = CMTestMethodUtilities.createUserStory('MyStory1');
        insert userStory;

        User_Story_Metadata__c usm = new User_Story_Metadata__c(
                Metadata_API_Name__c = 'Test__c',
                Status__c = Label.BACK_PROMOTED,
                User_Story__c = userStory.Id,
                Name = 'Test__c');
        insert usm;

        Org__c org = new Org__c(Name = 'Fake Org Test');
        insert org;
        Git_Org_Commit__c com = new Git_Org_Commit__c(Status__c = 'No changes', Org__c = org.Id);
        insert com;
        User_Story_Commit__c usc = new User_Story_Commit__c(User_Story__c = userStory.Id, Snapshot_Commit__c = com.Id);
        insert usc;

        Test.startTest();
        UserStoryExt ext1 = new UserStoryExt(new ApexPages.StandardController(userStory));
        System.assertEquals(true, testMethodUtilities.hasMessage(Label.BACK_PROMOTED_METADATA));
        System.assertEquals(true, testMethodUtilities.hasMessage(Label.COMMIT_NO_CHANGES));
        Test.stopTest();
    }
}