objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
        <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <fields>
        <fullName>Git_Provider__c</fullName>
        <description>Copado generates specific links to the Git Repository, its branches and commits based on the selected Git Provider.</description>
        <inlineHelpText>Copado generates specific links to the Git Repository, its branches and commits based on the selected Git Provider.</inlineHelpText>
        <label>Git Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Github</fullName>
                </value>
                <value>
                    <fullName>Bitbucket</fullName>
                </value>
                <value>
                    <fullName>GitLab</fullName>
                </value>
                <value>
                    <fullName>Microsoft Team Service</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pull_Request_Base_URL__c</fullName>
        <inlineHelpText>Base URL of your Repository, e.g.: https://github.com/[COMPANY]/[REPOSITORY]/ https://bitbucket.org/[COMPANY]/[REPOSITORY]/ https://gitlab.org/[COMPANY]/[REPOSITORY]/</inlineHelpText>
        <label>Pull Request Base URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Deployment Flow.</inlineHelpText>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Stop Indexing Metadata</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_API_Name__c</fullName>
        <label>Metadata API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Icon__c</fullName>
        <formula>IMAGE(
CASE(TEXT(Status__c),

&apos;Potential Conflict&apos;, &apos;/resource/&apos; &amp; IF($Setup.Settings__c.Namespace__c=&apos;none&apos;,&apos;&apos;,if(isblank($Setup.Settings__c.Namespace__c),&apos;copado__&apos;,$Setup.Settings__c.Namespace__c)) &amp; &apos;Statics/img/icons/warning16.png&apos;,

&apos;Back Promoted&apos;, &apos;/resource/&apos; &amp; IF($Setup.Settings__c.Namespace__c=&apos;none&apos;,&apos;&apos;,if(isblank($Setup.Settings__c.Namespace__c),&apos;copado__&apos;,$Setup.Settings__c.Namespace__c)) &amp; &apos;Statics/img/icons/warning16.png&apos;,

&apos;Conflict Resolved&apos;, &apos;/resource/&apos; &amp; IF($Setup.Settings__c.Namespace__c=&apos;none&apos;,&apos;&apos;,if(isblank($Setup.Settings__c.Namespace__c),&apos;copado__&apos;,$Setup.Settings__c.Namespace__c)) &amp; &apos;Statics/img/icons/confirm16.png&apos;,

&apos;Under Review&apos;, &apos;/resource/&apos; &amp; IF($Setup.Settings__c.Namespace__c=&apos;none&apos;,&apos;&apos;,if(isblank($Setup.Settings__c.Namespace__c),&apos;copado__&apos;,$Setup.Settings__c.Namespace__c)) &amp; &apos;Statics/img/icons/loading.gif&apos;,

&apos;On Hold&apos;, &apos;/resource/&apos; &amp; IF($Setup.Settings__c.Namespace__c=&apos;none&apos;,&apos;&apos;,if(isblank($Setup.Settings__c.Namespace__c),&apos;copado__&apos;,$Setup.Settings__c.Namespace__c)) &amp; &apos;Statics/img/icons/warning16.png&apos;,

&apos;/s.gif&apos;),

TEXT(Status__c)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status Icon</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Conflict</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Conflict Resolved</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Back Promoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserStoryMetadataExt.cls
public with sharing class UserStoryMetadataExt {
    public User_Story_Metadata__c usMetadata {get; set;}
    public List<User_Story_Metadata__c> usMetadatas {get; set;}
    private ApexPages.Standardcontroller controller {get; set;}
    public Map<String, User_Story_Metadata__c> usmMap {get; set;}
    public Map<String,pullConfig> usConfigMap {get;set;}
    public PullConfig latestPull {get;set;} 

    public UserStoryMetadataExt(ApexPages.StandardController stdController) {
        controller = stdController;
        retrieveMetadata();
    }

    public void retrieveMetadata() {
        usmMap = new Map<String, User_Story_Metadata__c>();
        try{
        usMetadata = [SELECT Id, Name, User_Story__r.Name, User_Story__r.Project__r.Deployment_Flow__c, User_Story__r.Release__r.Project__r.Deployment_Flow__c, Status__c, Status_Icon__c, Metadata_API_Name__c, User_Story__c, User_Story__r.Environment__c, User_Story__r.User_Story_Title__c, LastModifiedDate 
        FROM User_Story_Metadata__c WHERE Id = :controller.getId() AND User_Story__r.Stop_Indexing_Metadata__c != true LIMIT 1];
            }catch(Exception e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, 'This user story has been marked to stop indexing metadata.')); //To do: Change This for a Custom label. Patchable
            }

        if (usMetadata == null) {
            usMetadata = new User_Story_Metadata__c();
        }
        usMetadatas = new List<User_Story_Metadata__c>();
        for (User_Story_Metadata__c usm : [SELECT Name, User_Story__r.Name, User_Story__r.Project__r.Deployment_Flow__c, User_Story__r.Release__r.Project__r.Deployment_Flow__c, Status_Icon__c, Metadata_API_Name__c, Status__c, LastModifiedDate, User_Story__c, User_Story__r.Environment__c, User_Story__r.User_Story_Title__c 
            FROM User_Story_Metadata__c WHERE Id != :usMetadata.Id AND Metadata_API_Name__c = :usMetadata.Metadata_API_Name__c AND User_Story__r.Stop_Indexing_Metadata__c != true]) {
            usMetadatas.add(usm);
            usmMap.put(usm.Id, usm);
        }
    }
    public PageReference preparePullRequest() {
        if(usConfigMap == null){
            usConfigMap = new Map<String,pullConfig>();
        }
        String compareUS = ApexPages.currentPage().getParameters().get('compareUS');
        System.debug(loggingLevel.Error, '*** compareUS: ' + compareUS);
        System.debug(loggingLevel.Error, '*** usmMap.containsKey(compareUS): ' + usmMap.containsKey(compareUS));
        if (String.isBlank(compareUS) || !usmMap.containsKey(compareUS)) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, 'Nothing to compare.'));
            return null;
        } else {
            // comment
            if(usConfigMap.containsKey(compareUS)) {
                latestPull = usConfigMap.get(compareUS);
                System.debug(loggingLevel.Error, '*** latestPull: ' + latestPull);
                return null;
            }

            String baseDF, compareDF;
            if (String.isBlank(usMetadata.User_Story__r.Project__c) && String.isBlank(usMetadata.User_Story__r.Release__c)) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, LABEL.BASE_US_PROJECT_OR_RELEASE));
                return null;
            } else if (String.isBlank(usMetadata.User_Story__r.Project__r.Deployment_Flow__c) && String.isBlank(usMetadata.User_Story__r.Release__r.Project__r.Deployment_Flow__c)) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, LABEL.BASE_US_DEPLOYMENT_FLOW));
                return null;
            } else {
                baseDF = !String.isBlank(usMetadata.User_Story__r.Project__r.Deployment_Flow__c) ? usMetadata.User_Story__r.Project__r.Deployment_Flow__c : usMetadata.User_Story__r.Release__r.Project__r.Deployment_Flow__c;
            }
            User_Story_Metadata__c tempUS = usmMap.get(compareUS);
            if (String.isBlank(tempUS.User_Story__r.Project__c) && String.isBlank(tempUS.User_Story__r.Release__c)) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, LABEL.COMPAIRING_US_PROJECT_OR_RELEASE));
                return null;
            } else if (String.isBlank(tempUS.User_Story__r.Project__r.Deployment_Flow__c) && String.isBlank(tempUS.User_Story__r.Release__r.Project__r.Deployment_Flow__c)) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING, LABEL.COMPAIRING_US_DEPLOYMENT_FLOW));
                return null;
            } else {
                compareDF = !String.isBlank(tempUS.User_Story__r.Project__r.Deployment_Flow__c) ? tempUS.User_Story__r.Project__r.Deployment_Flow__c : tempUS.User_Story__r.Release__r.Project__r.Deployment_Flow__c;
            }

            if (baseDF != compareDF) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, LABEL.BASE_COMPARING_US_FLOW));
                return null;
            } else {
                List<String> extraFields = new List<String>();
                extraFields.add(Settings.ns+'Git_Repository__r.Pull_Request_Base_URL__c');
                extraFields.add(Settings.ns+'Git_Repository__r.Git_Provider__c');
                GlobalUtilities.deploymentFlowDetails flowDetails = GlobalUtilities.getDeploymentFlowDetails(baseDF, String.join(extraFields,', '));
                if (flowDetails.flow.Active__c) {
                    if (String.isBlank(flowDetails.flow.Git_Repository__r.Pull_Request_Base_URL__c) || String.isBlank(flowDetails.flow.Git_Repository__r.Git_Provider__c) ) {
                        ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, LABEL.PULLREQUEST_BASE_URL_AND_TYPE));
                        return null;
                    }else{
                        latestPull = new PullConfig(flowDetails.flow.Git_Repository__r.Git_Provider__c,flowDetails.flow.Git_Repository__r.Pull_Request_Base_URL__c,'feature/'+usMetadata.User_Story__r.Name, 'feature/'+tempUS.User_Story__r.Name);
                        System.debug(loggingLevel.Error, '*** latestPull2: ' + latestPull);
                        usConfigMap.put(compareUS,latestPull);
                        return null;
                    }
                } else {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, LABEL.FLOW_NEEDS_TO_BE_ACTVE));
                    return null;
                }
            }
            return null;
        }
    }
    public class PullConfig{
        public String gitType {get;set;}
        public String pullURL {get;set;}
        public String base {get;set;}
        public String compare {get;set;}

        public pullConfig(String gitType, String pullURL, String base, String compare){
            this.gitType = gitType;
            this.pullURL = pullURL;
            this.base = base;
            this.compare = compare;
        }
    }
    public List<SelectOption> getStatuses() {
        List<SelectOption> options = new List<SelectOption>();

        Schema.DescribeFieldResult statusDescribe = User_Story_Metadata__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> statuses = statusDescribe.getPicklistValues();

        for ( Schema.PicklistEntry f : statuses) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }

    private String Status = '';
    public String metadataId = '';

    public void updateStatuses() {
        metadataId = usMetadata.Id;
        updateStatus();
        for (User_Story_Metadata__c usm : usMetadatas) {
            metadataId = usm.Id;
            updateStatus();
        }
        // Saved for Copado v9.0 retrieveMetadata();
    }
    public PageReference updateStatus() {
        Status = Apexpages.currentPage().getParameters().get('Status');
        Boolean isSingleUpdate = false;
        if (metadataId == '') {
            metadataId = Apexpages.currentPage().getParameters().get('metadataId');
            isSingleUpdate = true;
        }

        if (usmMap.get(metadataId) != null) {
            usmMap.get(metadataId).Status__c = Status;
            update usmMap.get(metadataId);
        } else if (String.valueOf(usMetadata.Id) == metadataId) {
            usMetadata.Status__c = Status;
            update usMetadata;
        }

        // Saved for Copado v9.0 if(isSingleUpdate)retrieveMetadata();
        metadataId = '';

        return null;
    }
    /**
     * Overrides standard delete function
     * @return Pagereference
     * @see Utilities
     */
    public PageReference deleteJob() {
        if (usMetadata.id != null) {

            PageReference retPage;
            if (usMetadata.User_Story__c != null) {
                retPage = new PageReference('/' + usMetadata.User_Story__c);
            } else {
                retPage = new PageReference('/home/home.jsp');
            }
            retPage.setRedirect(true);
            try {
                Utilities.Secure_DML(usMetadata, Utilities.DML_Action.DEL, schema.Sobjecttype.User_Story_Metadata__c);
                return retPage;
            } catch (Exception e) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, Label.ERROR + ' : ' + e.getMessage()));
                return null;
            }

        }
        return null;
    }


}