objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
        <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Validations__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, Deployment Flow Steps best practices validations will be disabled.</description>
        <inlineHelpText>If checked, Deployment Flow Steps best practices validations will be disabled.</inlineHelpText>
        <label>Disable Validations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Equal_Branch_Environment_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, Environment names must equal their corresponding Branches in the Deployment Flow Steps.</description>
        <inlineHelpText>If checked, Environment names must equal their corresponding Branches in the Deployment Flow Steps.</inlineHelpText>
        <label>Enforce branch/env naming convention</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Branch__c</fullName>
        <description>Main branch of the selected Git Repository (e.g. master).</description>
        <inlineHelpText>Main branch of the selected Git Repository (e.g. master).</inlineHelpText>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestDeploymentFlowStepTrigger.cls
@isTest
public class TestDeploymentFlowStepTrigger {
    @testSetup static void setupData() {
        TestUtilities.getAllMultilicense();
    }
    @testSetup static void setupDataDML() {
        TestUtilities.assignLicense(UserInfo.getUserName(),true, true, true, true, true);
    }
    @isTest static void BranchMgmtEnabled(){
        Git_Repository__c gr = new Git_Repository__c(Name='test');
        insert gr;
        
        Deployment_Flow__c df = new Deployment_Flow__c(Name='test', Active__c=true, Main_Branch__c='master', Git_Repository__c=gr.Id,Disable_Validations__c = true);
        insert df;
    }
    static testMethod void testInsertion(){
        Feature__c f = new Feature__c(Name='Branch Management', Enabled__c=true, Quantity__c=5);
        insert f;
        Feature__c f2 = new Feature__c(Name='Git Backup', Enabled__c=true);
   		insert f2;
        
        Git_Repository__c gr = new Git_Repository__c(Name='test');
        insert gr;
        
        Deployment_Flow__c df = new Deployment_Flow__c(Name='test', Active__c=true, Main_Branch__c='master', Git_Repository__c=gr.Id);
        insert df;

        List<Environment__c> Le = new List<Environment__c>();
        for (Integer i=0;i<6;i++) {
            Environment__c e = new Environment__c (Name = 'Env' + i);
            Le.add(e);
        }
        insert Le;
        
        List<Org__c> Lo = new List<Org__c>();
        for (Integer i=0;i<6;i++) {
            Org__c o = new Org__c (Name = 'Org' + i, Environment__c = Le[i].Id);
            Lo.add(o);
        }
        insert Lo;
        
        List<Deployment_Flow_Step__c> inserts = new List<Deployment_Flow_Step__c>();
        inserts.add(new Deployment_Flow_Step__c(Deployment_Flow__c=df.Id, Branch__c='dev1', Source_Environment__c=Le[0].Id, Destination_Environment__c=Le[1].Id));
        inserts.add(new Deployment_Flow_Step__c(Deployment_Flow__c=df.Id, Branch__c='dev2', Source_Environment__c=Le[1].Id, Destination_Environment__c=Le[2].Id));
        
        Test.startTest();
        try{
        	insert inserts;
            system.assert(true, 'Insert successful.');
        }
        catch(DmlException e){
            system.assert(false, 'Should not have had an exception during insert of flow step.' + e.getMessage());
        }    
        Test.stopTest();
    }
    static testMethod void testUpdate(){
        Git_Repository__c gr = new Git_Repository__c(Name='test');
        insert gr;
        
        Deployment_Flow__c df = new Deployment_Flow__c(Name='test', Active__c=true, Main_Branch__c='master', Git_Repository__c=gr.Id, Disable_Validations__c = true);
        insert df;

        List<Environment__c> Le = new List<Environment__c>();
        for (Integer i=0;i<6;i++) {
            Environment__c e = new Environment__c (Name = 'Env' + i);
            Le.add(e);
        }
        insert Le;
        
        List<Org__c> Lo = new List<Org__c>();
        for (Integer i=0;i<6;i++) {
            Org__c o = new Org__c (Name = 'Org' + i, Environment__c = Le[i].Id);
            Lo.add(o);
        }
        insert Lo;
        
        List<Deployment_Flow_Step__c> inserts = new List<Deployment_Flow_Step__c>();
        inserts.add(new Deployment_Flow_Step__c(Deployment_Flow__c=df.Id, Branch__c='dev1', Source_Environment__c=Le[0].Id, Destination_Environment__c=Le[1].Id));
        inserts.add(new Deployment_Flow_Step__c(Deployment_Flow__c=df.Id, Source_Environment__c=Le[1].Id, Destination_Environment__c=Le[2].Id));
        insert inserts;
    }
    
    static testMethod void validationsTest () {

        Feature__c f = new Feature__c(Name='Branch Management', Enabled__c=true, Quantity__c=5);
        insert f;
        Feature__c f2 = new Feature__c(Name='Git Backup', Enabled__c=true);
        insert f2;
        
        Git_Repository__c gr = new Git_Repository__c(Name='test');
        insert gr;
        
        Deployment_Flow__c df = new Deployment_Flow__c(Name='test', Active__c=true, Main_Branch__c='master', Git_Repository__c=gr.Id);
        insert df;

        List<Environment__c> Le = new List<Environment__c>();
        for (Integer i=0;i<6;i++) {
            Environment__c e = new Environment__c (Name = 'Env' + i);
            Le.add(e);
        }
        insert Le;
        
        List<Org__c> Lo = new List<Org__c>();
        for (Integer i=0;i<6;i++) {
            Org__c o = new Org__c (Name = 'Org' + i, Environment__c = Le[i].Id);
            Lo.add(o);
        }
        insert Lo;
        
        Deployment_Flow_Step__c df1 = new Deployment_Flow_Step__c(
                Deployment_Flow__c=df.Id, Branch__c='dev1', Source_Environment__c=Le[0].Id, Destination_Environment__c=Le[2].Id);
        Deployment_Flow_Step__c df2 = new Deployment_Flow_Step__c(
                Deployment_Flow__c=df.Id, Branch__c='dev2', Source_Environment__c=Le[1].Id, Destination_Environment__c=Le[2].Id);

        insert df1;
        insert df2;
        
        Test.startTest();

        df1.Branch__c = '';
        try{
            update df1;
            update df2;
            system.assert(false, 'Should have failed due to missing branch name.');
        }
        catch(DmlException e){
            Boolean expectedExceptionThrown = e.getMessage().contains(Label.ALL_FLOW_STEPS_WITH_BRANCH_NAME)?true:false;
            system.debug('Actual Message thrown 1: '+e.getMessage());
            System.AssertEquals(expectedExceptionThrown, true);
        } 

        df1.Branch__c = 'dev1';
        df1.Source_Environment__c = null;
        try{
            update df1;
            update df2;
            system.assert(false, 'Should have failed due to missing Environment.');
        }
        catch(DmlException e){
            Boolean expectedExceptionThrown = e.getMessage().contains(Label.MUST_HAVE_SOURCE_AND_DESTINATION)?true:false;
            system.debug('Actual Message thrown 1: '+e.getMessage());
            System.AssertEquals(expectedExceptionThrown, true);
        }  

        df1.Branch__c = 'dev2';
        df1.Source_Environment__c = Le[0].Id;
        try{
            update df1;
            update df2;
            system.assert(false, 'Should have failed due to repeated branch name.');
        }
        catch(DmlException e){
            Boolean expectedExceptionThrown = e.getMessage().contains(Label.REPEATED_BRANCH_NAME)?true:false;
            system.debug('Actual Message thrown 1: '+e.getMessage());
            System.AssertEquals(expectedExceptionThrown, true);
        }  
        
        df1.Branch__c = 'dev1';
        df1.Source_Environment__c = Le[1].Id;
        try{
            update df1;
            update df2;
            system.assert(false, 'Should have failed due to repeated source Environment.');
        }
        catch(DmlException e){
            Boolean expectedExceptionThrown = e.getMessage().contains(Label.REPEATED_SOURCE_ENVIRONMENT)?true:false;
            system.debug('Actual Message thrown 1: '+e.getMessage());
            System.AssertEquals(expectedExceptionThrown, true);
        } 
        
        df1.Branch__c = 'Env0';
        df1.Source_Environment__c = Le[0].Id;
        df2.Branch__c = 'Env1';
        update df1;
        update df2;
        df.Equal_Branch_Environment_Name__c = true;
        update df;
        df1.Branch__c = 'dev1';
        df1.Source_Environment__c = Le[0].Id;
        try{
            update df1;
            update df2;
            system.assert(false, 'Should have failed due to a mismatch between Environment and Branch names.');
        }
        catch(DmlException e){
            Boolean expectedExceptionThrown = e.getMessage().contains(Label.BRANCH_AND_SOURCE_ENVIRONMENT_EQUALS)?true:false;
            system.debug('Actual Message thrown 1: '+e.getMessage());
            System.AssertEquals(expectedExceptionThrown, true);
        } 

        Test.stopTest();
    } 
}