objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Branch__c</fullName>
        <description>Main branch of the selected Git Repository (e.g. master).</description>
        <inlineHelpText>Main branch of the selected Git Repository (e.g. master).</inlineHelpText>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <defaultValue>&quot;master&quot;</defaultValue>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URI__c</fullName>
        <description>HTTPS or SSH URL to connect to the Git Repository.</description>
        <inlineHelpText>HTTPS or SSH URL to connect to the Git Repository.</inlineHelpText>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Deployment Flow.</inlineHelpText>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Base_Branch__c</fullName>
        <description>All user story feature branches are created out of the main branch of the Deployment Flow. If a Release base branch is specified, all feature branches of user stories linked to the Release will be created out of the base branch.</description>
        <inlineHelpText>All user story feature branches are created out of the main branch of the Deployment Flow. If a Release base branch is specified, all feature branches of user stories linked to the Release will be created out of the base branch.</inlineHelpText>
        <label>Base Branch</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Base_Branch__c</fullName>
        <description>Git branch which the feature branch is created from. This value is updated when committing in the user story and by default, it will be the main branch of the Deployment Flow or the base branch of the Release linked to the user story.</description>
        <inlineHelpText>Git branch which the feature branch is created from. This value is updated when committing in the user story and by default, it will be the main branch of the Deployment Flow or the base branch of the Release linked to the user story.e user story.</inlineHelpText>
        <label>Base Branch</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoryCommitIntermediaryExt.cls
public with sharing class UserStoryCommitIntermediaryExt {
    public User_Story__c userStory {get;set;}
    public ApexPages.Standardcontroller controller {get;set;}
    
    public List<Git_Backup__c> snapshots {get;set;}
    public Boolean showOptions {get;set;}
    public Boolean showError {get;set;}
    public Boolean showCreateDXBranchButton {get;set;}
    public String snapshotId {get;set;}
    public String repoId {get;set;}
    public String orgId {get;set;}
    public String targetPage{get;set;}
    public GlobalUtilities.deploymentFlowDetails flowDetails {get;set;}

    public String mainBranch {get;set;}
    
    public static final String[] FIELDS = new String[] {'Id','Name','Org_Credential__c', 'Environment__c', 'Org_Credential__r.Environment__c','Org_Credential__r.Org_Type__c', 'Base_Branch__c', 'Release__r.Base_Branch__c','Project__r.Deployment_Flow__r.Git_Repository__c','Release__r.Project__r.Deployment_Flow__r.Git_Repository__c'};
    
    public UserStoryCommitIntermediaryExt(ApexPages.StandardController stdController) {
        snapshotId = '';
        mainBranch = '';
        showOptions = false;
        showError = false;
        showCreateDXBranchButton = false;
        controller = stdController;
        targetPage = ApexPages.currentPage().getParameters().get('targetPage')!=null?ApexPages.currentPage().getParameters().get('targetPage'):'GitCommitChanges';
        if (!Test.isRunningTest()) {
            stdController.addFields(FIELDS);
        }
        this.userStory = (User_Story__c)stdController.getRecord();
        if(this.userStory==null){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.USER_STORY_COMMIT_NO_USER_STORY));
        } else {
            getOptions();
        }
    }
    public void getOptions(){ 
        snapshots = new List<Git_Backup__c>();

        if(LicenseHelper.isLicensesExceeded()) {           
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.LICENSES_EXCEEDED));
            showError = true;
            showOptions = false;//Defult false
            return;
        }

        if(!LicenseHelper.actionIsLicenseEnabled('commitFiles')){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CAD_License_Restriction));
            showError = true;
            showOptions = false;//Defult false
            return;
        }
        if(!FeatureHelper.isChangeChangeManagementEnabled()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.FEATURE_NOT_SUPPORTED));
            showError = true;
            showOptions = false;//Defult false
            return;
        }

        flowDetails = GlobalUtilities.getUserStoryDeploymentFlowDetails(userStory.Id, '');
        System.debug('flowDetails: '+flowDetails);
        if(flowDetails.isCBMFlow) {

            // Get Main Branch of Deployment Flow
            mainBranch = flowDetails.flow.Main_Branch__c != null ? flowDetails.flow.Main_Branch__c : '';
            System.debug('### userStory Base Branch: '+userStory.Base_Branch__c);
            System.debug('### release Base Branch: '+userStory.Release__r.Base_Branch__c);
            if(String.isNotEmpty(userStory.Base_Branch__c)) {
                mainBranch = userStory.Base_Branch__c;
            } else if(String.isNotEmpty(userStory.Release__r.Base_Branch__c)) {
                mainBranch = userStory.Release__r.Base_Branch__c;
            }
            System.debug('### mainBranch: '+mainBranch);

            if(!Schema.SObjectType.Deployment_Flow__c.fields.Git_Repository__c.isAccessible() ||
                !Schema.SObjectType.Deployment_Flow__c.fields.Main_Branch__c.isAccessible() ||
                !Schema.SObjectType.Deployment_Flow_Step__c.fields.Branch__c.isAccessible() ||
                !Schema.SObjectType.Deployment_Flow_Step__c.fields.Source_Environment__c.isAccessible() ||
                !Schema.SObjectType.Deployment_Flow_Step__c.fields.Destination_Environment__c.isAccessible() ||
                !Schema.SObjectType.Git_Repository__c.fields.Name.isAccessible() ||
                !Schema.SObjectType.Git_Repository__c.fields.URI__c.isAccessible() ||
                !Schema.SObjectType.Git_Repository__c.fields.Username__c.isAccessible() ||
                !Schema.SObjectType.Git_Repository__c.fields.Password__c.isAccessible() ||
                !Schema.SObjectType.Git_Backup__c.fields.Org__c.isAccessible() ||
                !Schema.SObjectType.Git_Backup__c.fields.Git_Repository__c.isAccessible() ||
                !Schema.SObjectType.Git_Backup__c.fields.Frequency__c.isAccessible() ||
                !Schema.SObjectType.Git_Backup__c.fields.Git_Snapshot_Permissions__c.isAccessible() ||
                !Schema.SObjectType.Git_Backup__c.fields.Branch__c.isAccessible()) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.MISSING_PERMISSIONS_CBM_FLOW));
                showError = true;
                showOptions = false;
                return;
            }
        }

        // Check if Flow is Active
        if(flowDetails.flow == null || !flowDetails.flow.Active__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.PROMOTION_FLOW_INACTIVE));
            showError = true;
            showOptions = false;
            return;
        }

        // Check if Commits are allowed
        if(flowDetails.flow != null && flowDetails.flow.Block_Commits__c) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.DEPLOYMENT_FLOW_COMMITS_BLOCKED));
            showError = true;
            showOptions = false;
            return;
        }

        if(String.isBlank(userStory.Environment__c)){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.USER_STORY_COMMIT_NO_ENVIRONMENT));
            showError = true;
            showOptions = false;
            return;
        }
       
       snapshots = [select Id, Name, Org__c, Git_Repository__c, Git_Repository__r.Name, Org__r.Name, Org__r.OwnerId, Org__r.Environment__c, Branch__c, Frequency__c, Git_Snapshot_Permissions__c from Git_Backup__c where (Git_Snapshot_Permissions__c='' or Git_Snapshot_Permissions__c!='Allow Snapshots Only') and Org__r.Environment__c=:userStory.Environment__c limit 100];
       if(userStory != null && snapshots.size()==0 && userStory.Org_Credential__r.Org_Type__c == 'Scratch Org'){
            //If no snapshot and it's Scratch Org, we look for the attachmet to see if scratch org was created from ArtifactUMP if so, we allow users to create it
            List<Attachment> attList = [SELECT Body FROM Attachment WHERE ParentId =: userStory.Org_Credential__c AND  Name = : SfdxAPIHelper.DX_METADATA_SOURCES LIMIT 1];
            if(attList.size()>0){
                Map<String, Object> deserializedJsonMap = (Map<String, Object>) JSON.deserializeUntyped(attList.get(0).Body.toString());
                String mSourceType = deserializedJsonMap.containsKey('metadataSourceType') ? String.ValueOf(deserializedJsonMap.get('metadataSourceType')) : '';
                String mSource = deserializedJsonMap.containsKey('metadataSource') ? String.ValueOf(deserializedJsonMap.get('metadataSource')) : '';
                //String pBranchCreated = deserializedJsonMap.containsKey('projectBranchCreated') ? String.ValueOf(deserializedJsonMap.get('projectBranchCreated')) : '';
                if (String.isNotBlank(mSource) &&  String.isNotBlank(mSourceType)  /*&&  String.isNotBlank(pBranchCreated) && pBranchCreated != 'true'  */&& mSourceType == 'artifactUMP') {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'DX Project has not been created would you like to create it?'));
                    showCreateDXBranchButton = true;
                    showError = true;
                    showOptions = false;
                    return;
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.USER_STORY_COMMIT_NO_SNAPSHOT_FOUND));
                    showError = true;
                    showOptions = false;
                    return;
                }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.USER_STORY_COMMIT_NO_SNAPSHOT_FOUND));
                showError = true;
                showOptions = false;
                return;
            }
        }else if(snapshots.size()==0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.USER_STORY_COMMIT_NO_SNAPSHOT_FOUND));
            showError = true;
            showOptions = false;
            return;
        }

        if(snapshots.size()==1){
            showError = false;
            showOptions = false;
            snapshotId = snapshots[0].Id;
            orgId = snapshots[0].Org__c;
            repoId = snapshots[0].Git_Repository__c;
            return;
        }
        if(snapshots.size()>1){
            showError = false;
            showOptions = true;
            return;
        }
    }
    
    //FL: manually fix Copado-auto-merge where 402 code wons over 438
    public String getAdditionalParams() {
        PageReference pr = new PageReference('/');
        for(String k : ApexPages.currentPage().getParameters().keySet()) {
            pr.getParameters().put(k, ApexPages.currentPage().getParameters().get(k));
        }
        pr.getParameters().remove('id');
        String pr1 = pr.getUrl().replace('/?', '').replace('/%3f', '').replace('/%3F', '');
        System.debug('pr1='+pr1);
        return pr1.length()>0 ? pr1+'&' : '';
    }

    public PageReference createDXBranch(){
        String depFlowGitRepoId = '';
        if (userStory.Project__r.Deployment_Flow__r.Git_Repository__c != null) {
            depFlowGitRepoId = userStory.Project__r.Deployment_Flow__r.Git_Repository__c;
        } else if (userStory.Release__r.Project__r.Deployment_Flow__r.Git_Repository__c != null) {
            depFlowGitRepoId = userStory.Release__r.Project__r.Deployment_Flow__r.Git_Repository__c;
        }
        SfdxAPI.createProjectBranch(userStory.Org_Credential__c,depFlowGitRepoId);
        return null;
    }

    public PageReference jobStatusNotification() {
        Boolean jobFinished = ApexPages.currentPage().getParameters().get('jobFinished') == 'true' ? true : false;
        Boolean jobSuccess = ApexPages.currentPage().getParameters().get('jobSuccess') == 'true' ? true : false;
        String jobMessage = ApexPages.currentPage().getParameters().get('jobMessage');
        String jobType = ApexPages.currentPage().getParameters().get('jobType');

        if (jobFinished && jobSuccess && String.isNotBlank(jobType)) {
            if (jobType == CopadoNotificationHelper.DX_CREATE_PROJECT_BRANCH) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, Label.Scratch_Org_Created_Success));
                PageReference p =  ApexPages.currentPage();
                p.getParameters().clear();
                p.getParameters().put('Id',userStory.Id);
                p.setRedirect(true);
                return p;
            }
        } else if (jobFinished && !jobSuccess && String.isNotBlank(jobMessage)) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, jobMessage));
        }
        return null;
    }

}