objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
        <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Main_Branch__c</fullName>
        <description>Main branch of the selected Git Repository (e.g. master).</description>
        <inlineHelpText>Main branch of the selected Git Repository (e.g. master).</inlineHelpText>
        <label>Main Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Static_Code_Analysis_Settings__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Static Code Analysis settings used whenever the analysis is run in Environments or User Stories linked to the Deployment Flow.</description>
        <inlineHelpText>Static Code Analysis settings used whenever the analysis is run in Environments or User Stories linked to the Deployment Flow.</inlineHelpText>
        <label>Static Code Analysis Settings</label>
        <referenceTo>Static_Code_Analysis_Settings__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Git branch linked to the source environment.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Deployment Flow.</inlineHelpText>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Static_Code_Analysis_Settings__c.object
<CustomObject>
    <label>Static Code Analysis Settings</label>
    <nameField>
        <label>Static Code Analysis Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Static Code Analysis Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUserStoryCodeAnalysisRequest.cls
@isTest
private class TestUserStoryCodeAnalysisRequest {
    @testSetup static void setupData() {
        TestUtilities.getAllMultilicense();
    }
    static void setupDataDML() {
        testMethodUtilities.upsertOrgwideSettings();
        TestUtilities.assignLicense(UserInfo.getUserName(), true, false, false, false, true);
        TestUtilities.insertUser('user1-TestUserStoryCodeAnalysisRequest@test-copado.org','System Administrator');
        TestUtilities.assignLicense('user1-TestUserStoryCodeAnalysisRequest@test-copado.org', false, false, false, true, false);
    }
	static testMethod void testPMDusRequest(){
        setupDataDML();
		Static_Code_Analysis_Settings__c scas = new Static_Code_Analysis_Settings__c();
	    Utilities.Secure_DML(scas, Utilities.DML_Action.INS, schema.Sobjecttype.Static_Code_Analysis_Settings__c); 

        Feature__c f = new Feature__c(Name='Branch Management', Enabled__c=true, Quantity__c=5);
        Utilities.Secure_DML(f, Utilities.DML_Action.INS, schema.Sobjecttype.Feature__c);
        Feature__c f2 = new Feature__c(Name='Git Backup', Enabled__c=true);
   		Utilities.Secure_DML(f2, Utilities.DML_Action.INS, schema.Sobjecttype.Feature__c);
   		Feature__c f3 = new Feature__c(Name='Apex Test', Enabled__c=true);
        Utilities.Secure_DML(f3, Utilities.DML_Action.INS, schema.Sobjecttype.Feature__c);
        
        Git_Repository__c gr = new Git_Repository__c(Name='test');
        Utilities.Secure_DML(gr, Utilities.DML_Action.INS, schema.Sobjecttype.Git_Repository__c);
        
        Deployment_Flow__c df = new Deployment_Flow__c(Name='test', Active__c=true, Main_Branch__c='master', Git_Repository__c=gr.Id, Static_Code_Analysis_Settings__c=scas.Id);
        Utilities.Secure_DML(df, Utilities.DML_Action.INS, schema.Sobjecttype.Deployment_Flow__c);

        Project__c p = new Project__c(Name='Test Project',Deployment_Flow__c=df.Id);
        Utilities.Secure_DML(p, Utilities.DML_Action.INS, schema.Sobjecttype.Project__c);

        List<Environment__c> Le = new List<Environment__c>();
        for (Integer i=0;i<6;i++) {
            Environment__c e = new Environment__c (Name = 'Env' + i);
            Le.add(e);
        }
        Utilities.Secure_DML(Le, Utilities.DML_Action.INS, schema.Sobjecttype.Environment__c);
        
        List<Org__c> Lo = new List<Org__c>();
        for (Integer i=0;i<6;i++) {
            Org__c o = new Org__c (Name = 'Org' + i, Environment__c = Le[i].Id);
            Lo.add(o);
        }
        Utilities.Secure_DML(Lo, Utilities.DML_Action.INS, schema.Sobjecttype.Org__c);

        User_Story__c us = new User_Story__c(Project__c = p.Id, Org_Credential__c = Lo[0].Id);
        Utilities.Secure_DML(us, Utilities.DML_Action.INS, schema.Sobjecttype.User_Story__c);

        String attBody = '[{"t":"ApexClass","n":"TestAccountTrigger"}]';
        Attachment testAttachment = createAttachment(us.Id, 'MetaData', attBody);
        Utilities.Secure_DML(testAttachment, Utilities.DML_Action.INS, schema.Sobjecttype.Attachment);

        attBody = '[{"t":"ApexClass","n":"AccountTriggerHelper"},{"t":"ApexClass","n":"MockClass"}]';
        testAttachment = createAttachment(us.Id, 'Git MetaData', attBody);
        Utilities.Secure_DML(testAttachment, Utilities.DML_Action.INS, schema.Sobjecttype.Attachment);

        attBody = '[{"t":"ApexClass","n":"MockClass"}]';
        testAttachment = createAttachment(us.Id, 'Delete MetaData', attBody);
        Utilities.Secure_DML(testAttachment, Utilities.DML_Action.INS, schema.Sobjecttype.Attachment);
        
        List<Deployment_Flow_Step__c> inserts = new List<Deployment_Flow_Step__c>();
        inserts.add(new Deployment_Flow_Step__c(Deployment_Flow__c=df.Id, Branch__c='dev1', Source_Environment__c=Le[0].Id, Destination_Environment__c=Le[1].Id));
        inserts.add(new Deployment_Flow_Step__c(Deployment_Flow__c=df.Id, Branch__c='dev2', Source_Environment__c=Le[1].Id, Destination_Environment__c=Le[2].Id));
        Utilities.Secure_DML(inserts, Utilities.DML_Action.INS, schema.Sobjecttype.Deployment_Flow_Step__c);
        
        DeployAPI con = new DeployAPI();
		String b = '{"status":"OK"}';
	    Test.setMock(HttpCalloutMock.class, new testHttpCalloutMock(b, null));

		Test.startTest();
		UserStoryCodeAnalysisRequestController uscarc = new UserStoryCodeAnalysisRequestController(new ApexPages.StandardController(us));
		uscarc.requestCodeScan();
        System.assert(testMethodUtilities.hasMessage(Label.USER_STORY_ANALYSIS_REQUESTED));
	    Test.stopTest();
	    boolean bbb=true;system.assertEquals(true,bbb);
	}

    static testMethod void testPMDusRequestErrors(){
        setupDataDML();
        Static_Code_Analysis_Settings__c scas = new Static_Code_Analysis_Settings__c();
        insert scas;

        Feature__c feature = new Feature__c(Name='Branch Management', Enabled__c=true, Quantity__c=5);
        insert feature;
        Feature__c feature2 = new Feature__c(Name='Git Backup', Enabled__c=true);
        insert feature2;
        Feature__c feature3 = new Feature__c(Name='Apex Test', Enabled__c=true);
        insert feature3;
        
        Git_Repository__c gitRepo = new Git_Repository__c(Name='test');
        insert gitRepo;
        
        Deployment_Flow__c flow = new Deployment_Flow__c(Name='test', Active__c=true, Main_Branch__c='master', Git_Repository__c=gitRepo.Id, Static_Code_Analysis_Settings__c=scas.Id);
        insert flow;

        Project__c project = new Project__c(Name='Test Project',Deployment_Flow__c=flow.Id);
        insert project;

        List<Environment__c> Le = new List<Environment__c>();
        for (Integer i=0;i<6;i++) {
            Environment__c e = new Environment__c (Name = 'Env' + i);
            Le.add(e);
        }
        insert Le;
        
        List<Org__c> Lo = new List<Org__c>();
        for (Integer i=0;i<6;i++) {
            Org__c o = new Org__c (Name = 'Org' + i, Environment__c = Le[i].Id);
            Lo.add(o);
        }
        insert Lo;

        User_Story__c us = new User_Story__c(Project__c = project.Id, Org_Credential__c = Lo[0].Id);
        insert us;

        User user = [SELECT Id FROM User WHERE username ='user1-TestUserStoryCodeAnalysisRequest@test-copado.org'];
        System.runAs(user) {
            Test.startTest();
            UserStoryCodeAnalysisRequestController uscarc = new UserStoryCodeAnalysisRequestController(new ApexPages.StandardController(us));
            uscarc.requestCodeScan();
            System.assert(testMethodUtilities.hasMessage(Label.CAD_LICENSE_RESTRICTION));
            Test.stopTest();
        }
    }

	private static Attachment createAttachment(String parentId, String name, String body){
		Attachment a = new Attachment(parentId=parentId, name=name);
		a.Body = Blob.valueOf(body);
		return a;
	}
}