objects/Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <inlineHelpText>When this need to be deployed</inlineHelpText>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Destination_Org__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Destination Orgs</relationshipLabel>
        <relationshipName>Destination_Orgs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>To Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Deployments To</relationshipLabel>
        <relationshipName>Deployments_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Destination Org</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Disable_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this checkbox will not validate the org credentials when the record is saved or viewed.</inlineHelpText>
        <label>Disable Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Oauth_Signature__c</fullName>
        <description>This value is automatically set and updated by Copado.</description>
        <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
        <label>Oauth Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>Deployment__c</referenceTo>
        <relationshipLabel>Steps</relationshipLabel>
        <relationshipName>Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MetaData</fullName>
                    <default>true</default>
                    <label>MetaData</label>
                </value>
                <value>
                    <fullName>Full Profiles</fullName>
                </value>
                <value>
                    <fullName>Full Permission Sets</fullName>
                </value>
                <value>
                    <fullName>Users</fullName>
                </value>
                <value>
                    <fullName>Translations</fullName>
                </value>
                <value>
                    <fullName>Data</fullName>
                </value>
                <value>
                    <fullName>Bulk Data</fullName>
                </value>
                <value>
                    <fullName>Delete MetaData</fullName>
                </value>
                <value>
                    <fullName>Custom Settings</fullName>
                </value>
                <value>
                    <fullName>Apex</fullName>
                </value>
                <value>
                    <fullName>Git MetaData</fullName>
                </value>
                <value>
                    <fullName>URL Callout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Step</label>
    <nameField>
        <label>Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CopadoAPI.cls
/**
 * Service class to implement the service layer of copado deployments
 *
 * This class works as a services to be called from Rest interface CopadoAPIRest as well as from APEX by 
 * this package in self or a final user by CopadoAPI.listDeployments()
 *
 * @author: Martin
 */
public class CopadoAPI {

	public static final String DEPLOY_TYPE_ALL = 'ALL';
	public static final String DEPLOY_TYPE_OUTSANDING = 'OUTSTANDING';
	/**
	 * This method will retrive all Deployments
	 */
	public static Deployment__c[] listDeployments(){
		return [select id,name, status__c, from_Org__c from Deployment__c order by createddate desc];
	}

	/**
	 * TODO: complete comments
	 *
	 * @param 
	 */
	public static Deployment__c getDeployment(String deploymentId){
		//TODO: check with FEDE if we realy need to retrive the whole related info of a deploy ???
		return [select id,name, status__c, from_Org__c, date__c, (select id,name,order__c, status__c, type__c from Steps__r), (select id,name,status__c, to_org__c, to_org__r.name from Destination_Orgs__r), (select id,name,createddate from Attachments order by createddate desc) from Deployment__c where id=:deploymentId];
	}

	/**
	 * This method will create all Deployments
	 */
	public static void createDeployment(Deployment__c deployment){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void updateDeployment(Deployment__c deployment){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void removeDeployment(String deploymentId){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void removeDestinationOrg(String deploymentId, String destinationOrg){
		Utilities.Secure_DML([select id from Destination_Org__c where Deployment__c =:deploymentId and To_Org__c = :destinationOrg] , 
			Utilities.DML_Action.DEL, schema.Sobjecttype.Destination_Org__c);
	}

	/**
	 * The org destinations by deployment Id
	 */
	public static Destination_Org__c[] getDestinationsOrg(String deploymentId){
		return Utilities.getDestinationOrgsByDeploymentId(deploymentId);

		//TODO add validation and helty flags to destination
        //if (!DeployAPI.validateOrg(org.Id)){
        //
        /*if(org.id != null && !org.Disable_Validation__c){
            org = utilities.getOrgById(org.id);
            if(org.oauth_signature__c == null && org.password__c == null){
                Apexpages.addMessage(new apexpages.Message(apexpages.severity.info,Label.ADD_AUTHENTICATION));
                return null;
            }
            else{
                if (!DeployAPI.validateOrg(org.Id)){
                	*/
	}

	/**
	 * TODO: complete comments
	 */
	public static Destination_Org__c addDestinationOrg(String deploymentId, String destinationOrg){

		return (Destination_Org__c)Utilities.Secure_DML(new Destination_Org__c(
				To_Org__c = destinationOrg,
				Deployment__c = deploymentId
			), Utilities.DML_Action.INS, Schema.SObjectType.Destination_Org__c);
	}

	
	/**
	 * This method will retrive all Deployments
	 */
	public static Step__c[] listSteps(String deploymentId){
		return Utilities.getStepsByDeploymentId(deploymentId);
	}

	/**
	 * This method will create all Deployments
	 */
	public static void createStep(String deploymentId, Step__c step){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void updateStep(String deploymentId, Step__c step, String items){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void removeStep(String stepId){
		Utilities.Secure_DML(Utilities.getStepById(stepId), Utilities.DML_Action.DEL, schema.Sobjecttype.Step__c);
	}

	/**
	 * TODO: complete comments
	 */
	public static void scheduleDeployment(String deploymentId, Datetime deployTime){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void deploy(String deploymentId, String type){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void cancelDeploy(String deploymentId){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getDeployHistory(String deploymentId){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getDeployHistoryLog(String deploymentId){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getStepHistory(String stepId){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getStepHistoryDetail(String stepId){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getJobsByDeployment(String deploymentId, String status){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getJobsByStep(String stepId, String status){
		//TODO
	}

	/**
	 * TODO: complete comments
	 */
	public static void getDeployStatus(String deploymentId){
		//TODO
	}



}