objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, all Branch Management features will be enabled in the Deployment Flow.</description>
        <inlineHelpText>If checked, all Branch Management features will be enabled in the Deployment Flow.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Epic__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Epic</label>
    <nameField>
        <displayFormat>E{0000000}</displayFormat>
        <label>Epic Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Default_Credential__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If selected, this will be the preferred Org credential for Promotion deployments</inlineHelpText>
        <label>Default Credential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Deployment Flow.</inlineHelpText>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sprint__c.object
<CustomObject>
    <description>If a project is broken down into multiple sprints this object should be used.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</description>
        <inlineHelpText>Current environment of the User Story. This value is added automatically by Copado based on the selected Org Credential.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Epic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Epic containing the User Story.</description>
        <inlineHelpText>Epic containing the User Story.</inlineHelpText>
        <label>Epic</label>
        <referenceTo>Epic__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sprint where the User Story is planned.</description>
        <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Team which will tackle the User Story.</description>
        <inlineHelpText>Team which will tackle the User Story.</inlineHelpText>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkManagerTest.cls
/*
*   WorkManager Unit Tests
*   Created by: jgaviria@copa.do
*   Description: Unit Test for WorkManager Controller
*/
@isTest
private class WorkManagerTest {
    @testSetup static void setupTestData(){
        TestUtilities.getAllMultilicense();
    }
    static void setupTestDataDML(){
        testMethodUtilities.upsertOrgwideSettings();
        profile p = [select id from Profile where name = 'System Administrator'];
        User user1 = new User(firstname = 'Future', lastname = 'User',
            alias = 'xyz1', 
            email = 'copado-test-1@test.org',
            emailencodingkey = 'UTF-8', 
            languagelocalekey='en_US', 
            localesidkey='en_US', 
            profileid = p.Id, 
            timezonesidkey = 'America/Los_Angeles',
            username = 'copado-test-1+SCA1@test.org'
            );
        insert(user1);

        TestUtilities.assignLicense(UserInfo.getUserName(), true, true, true, true, true);
        TestUtilities.assignLicense(user1.username, true, true, true, true, true);
    }

	/*
        This Method will test the constructor for the 4 default panels, meaning there is no Configuration saved
        The user is part of the teams   
     */
	@isTest static void loadWorkManagerDefault() {
        setupTestDataDML();
        User u1 = [select id from user where username = 'copado-test-1+SCA1@test.org'];

        //Create Team and team members for user assigned to the sprint
        Team__c tTest = new Team__c();
        tTest.Active__c = true;
        insert tTest;

        Team_Member__c tm = new Team_Member__c();
        tm.Team__c = tTest.Id;
        tm.Member__c = u1.Id;
        insert tm;

        //Sprint To Use
        List<Sprint__c> sToInsert = new List<Sprint__c>();
        Sprint__c s = new Sprint__c();
        s.Start_Date__c = date.today().addDays(-8);
        s.End_Date__c = date.today().addDays(8);
        s.Team__c = tTest.Id;
        sToInsert.add(s);

        Sprint__c nextS = new Sprint__c();
        nextS.Start_Date__c = date.today().addDays(20);
        nextS.End_Date__c = date.today().addDays(28);
        nextS.Team__c = tTest.Id;
        sToInsert.add(nextS);

        insert sToInsert;

        Git_Repository__c gitRepo = new Git_Repository__c(name = 'gitRepo');
        insert gitRepo;   

        Environment__c env1 = new Environment__c(Name='Dev1 Environment',Type__c='Sandbox');
        insert env1;

        Org__c testOrg1 = CMTestMethodUtilities.createOrg('MyOrg1', 'Sandbox', null, 'SFDC_OrgId', null, null, system.now(), env1.Id);
        testOrg1.Default_Credential__c = true;
        insert testOrg1; 

        Deployment_Flow__c flowCBM = CMTestMethodUtilities.createCBMFlow('CBM flow', true, gitRepo.Id, 'master');
        insert flowCBM;          

        Project__c testProject = CMTestMethodUtilities.createProject('test project');
        testProject.Deployment_Flow__c = flowCBM.Id;
        insert testProject;       

        Epic__c e = new Epic__c();
        insert e;

        List<User_Story__c> usList = new  List<User_Story__c>();
        //First User Story, in Backlog, no Sprint
        User_Story__c userStory = CMTestMethodUtilities.createUserStory('Backlog US');
        userStory.Environment__c = env1.Id;
        userStory.Org_Credential__c = testOrg1.Id;
        userStory.Project__c = testProject.Id;
        userStory.Sprint__c = null;
        userStory.Status__c = 'Backlog';
        userStory.Epic__c = e.Id;
        usList.add(userStory);

        //User Story In Sprint
        User_Story__c userStory2 = CMTestMethodUtilities.createUserStory('Draft US');
        userStory2.Environment__c = env1.Id;
        userStory2.Org_Credential__c = testOrg1.Id;
        userStory2.Project__c = testProject.Id;
        userStory2.Sprint__c = s.Id;
        userStory2.Status__c = 'Draft';
        usList.add(userStory2);

        //Add two extra us for backlog and backburner to Apply Ranks
        User_Story__c userStory3 = CMTestMethodUtilities.createUserStory('Stay at Backlog US');
        userStory3.Environment__c = env1.Id;
        userStory3.Org_Credential__c = testOrg1.Id;
        userStory3.Project__c = testProject.Id;
        userStory3.Sprint__c = null;
        userStory3.Status__c = 'Backlog';
        usList.add(userStory3);

        User_Story__c userStory4 = CMTestMethodUtilities.createUserStory('Stay at Backburner US');
        userStory4.Environment__c = env1.Id;
        userStory4.Org_Credential__c = testOrg1.Id;
        userStory4.Project__c = testProject.Id;
        userStory4.Sprint__c = null;
        userStory4.Status__c = 'Backburner';
        usList.add(userStory4);        

        insert usList;        

        Test.startTest();
            Test.setCurrentPageReference(ApexPages.currentPage()); 
            System.runAs(u1) {
                WorkManager wM = new WorkManager();
                //4 Panels must have been rendered
                system.assertEquals(4,wM.wpList.size());
                //now let's add an epic panel
                System.currentPageReference().getParameters().put('newPanelId', String.valueOf(e.Id));
                System.currentPageReference().getParameters().put('newPanelName', Settings.ns+'Epic__c');
                wM.createNewPanel();
                system.assertEquals(5,wM.wpList.size());
                //try to add it again,
                wM.createNewPanel(); 
                //Should not be added
                system.assertEquals(5,wM.wpList.size());
                //Now Add Draft Panel:
                System.currentPageReference().getParameters().put('newPanelId', '');
                wM.statusSelected = 'Draft';
                wM.createNewPanel();
                system.assertEquals(6,wM.wpList.size());
                //Hide Draft Panel
                System.currentPageReference().getParameters().put('panelId', 'Draft');
                System.currentPageReference().getParameters().put('panelType', Settings.ns+'Status__c');
                wM.hidePanel();
                // Panel is removed, if needed now will be queried
                system.assertEquals(5,wM.wpList.size());
                //Show Draft Panel, Let's start moving User Stories
                System.currentPageReference().getParameters().put('newPanelId', '');
                wM.statusSelected = 'Draft';
                wM.createNewPanel();
                //Add Cancelled Panel
                System.currentPageReference().getParameters().put('newPanelId', '');
                wM.statusSelected = 'Cancelled';
                wM.createNewPanel();
                system.assertEquals(6,wM.wpList.size());
                system.debug(wM.wpList);
                //Update Ranks = Json example:
                String rankJS = '{"logIds":["'+userStory3.Id+'"],"burnerIds":["'+userStory4.Id+'"]}';
                System.currentPageReference().getParameters().put('jsrank', rankJS);
                wM.updateRanks();                
                //Save State JSON looks Like:
                String jState = '{"pName":"","pWrappers":[{"pId":"Backlog","pType":"'+Settings.ns+'Status__c"},{"pId":"Backburner","pType":"'+Settings.ns+'Status__c"},{"pId":"'+s.Id+'","pType":"'+Settings.ns+'Sprint__c"},{"pId":"'+nextS.Id+'","pType":"'+Settings.ns+'Sprint__c"},{"pId":"'+e.Id+'","pType":"'+Settings.ns+'Epic__c"},{"pId":"Draft","pType":"'+Settings.ns+'Status__c"},{"pId":"Cancelled","pType":"'+Settings.ns+'Status__c"}]}';
                System.currentPageReference().getParameters().put('jsstate', jState);
                wM.savePanelState();
                //Static Json: this is how it should be looking like:
                String jsonMockUpdate = '{"sId":"Backlog","tId":"Cancelled","stype":"'+Settings.ns+'Status__c","ttype":"'+Settings.ns+'Status__c","usIds":["'+userStory.Id+'"]}';
                System.currentPageReference().getParameters().put('jsonUpdate', jsonMockUpdate);
                wM.updatePanels();
                system.debug(wM.wpList);
                //Now Let's move same one from one Cancelled to next Sprint
                jsonMockUpdate = '{"sId":"Cancelled","tId":"'+nextS.Id+'","stype":"'+Settings.ns+'Status__c","ttype":"'+Settings.ns+'Sprint__c","usIds":["'+userStory.Id+'"]}';
                System.currentPageReference().getParameters().put('jsonUpdate', jsonMockUpdate);
                wM.updatePanels();
                system.debug(wM.wpList);
                //Let's add a new Config and remove it
                System.currentPageReference().getParameters().put('sName', 'Test Config');
                wM.addNewConfig();
                wM.pTypeSelected = 'Test Config';
                wM.removeConfig();

            }
        Test.stopTest();


	}
	
}