objects/Deployment_Flow__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Deployment Flow. All branches of the Deployment Flow Steps must exist in this Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Deployment Flows</relationshipLabel>
        <relationshipName>Deployment_Flows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enable_as_Scratch_Org_Destination__c</fullName>
        <label>Enable as Scratch Org Target</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Default DX Target</fullName>
                </value>
                <value>
                    <fullName>DX Target</fullName>
                </value>
                <value>
                    <fullName>DX Patch Target</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Hub_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If working with Copado Change Management, the Project must be linked to a Deployment Flow.</inlineHelpText>
        <label>Deployment Flow</label>
        <referenceTo>Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts (User Story)</relationshipLabel>
        <relationshipName>Test_Scripts_UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScratchOrgCompletionController.cls
/**
 * Created by mertyalti on 15/01/2018.
 */

public with sharing class ScratchOrgCompletionController extends ScratchOrgWizardComponentBase {
    public SfdxAPIHelper.sfdxProject artifactProject { get; set; }
    public List<SfdxAPIHelper.sfdxProjectArtifacts> artifactDirectories { get; set; }
    public SfdxAPIHelper.ScratchOrgDefinition orgDefinition { get; set; }
    public String parentId { get; set; }
    public String selectedStep { get; set; }
    private Map<Id, Deployment_Flow_Step__c> flowStepsMap { get; set; }
    public String deploymentFlowName { get; set; }
    public String selectedPermissions { get; set; }
    public List<SelectOption> dxTargetFlowSteps { get; set; }
    public Boolean showDeploymentFlow { get; set; }
    public Boolean showPermissionsPanel { get; set; }
    public Boolean showSetup { get; set; }
    public String depFlowId { get; set; }
    public String depFlowGitRepoId { get; set; }
    public String completionMessage { get; set; }
    public String sourceBranch { get; set; }
    public String sourceArtifacts { get; set; }
    public String sourceOrg { get; set; }
    public SfdxAPIHelper.ObjectLevelSecurity deploymentFlowSecurity { get; set; }
    public SfdxAPIHelper.ObjectLevelSecurity deploymentFlowStepSecurity { get; set; }
    public Test_Run__c tRun {get;set;}

    public ScratchOrgCompletionController() {
        deploymentFlowSecurity = SfdxAPIHelper.checkOLS(Schema.sObjectType.Deployment_Flow__c);
        deploymentFlowStepSecurity = SfdxAPIHelper.checkOLS(Schema.sObjectType.Deployment_Flow_Step__c);
        showDeploymentFlow = deploymentFlowSecurity.updateable && deploymentFlowStepSecurity.creatable;
        showPermissionsPanel = true;
        showSetup = true;
        flowStepsMap = new Map<Id, Deployment_Flow_Step__c>();

    }

    public PageReference createFullScratchOrg() {
        if(tRun != null && String.isNotBlank(tRun.Id)){
            String devHubId = tRun.Test_Script__r.User_Story__r.Org_Credential__r.Developer_Hub_Org__c;
            String sourceBranch = SfdxAPIHelper.DX_PROJECT_BRANCH+String.valueOf(tRun.Test_Script__r.User_Story__r.Org_Credential__c).substring(3,15);
            String soName = tRun.Name+' Scratch Org';
            String orgId = tRun.Test_Script__r.User_Story__r.Org_Credential__c;
            List<Attachment> attDefinition = [SELECT Body FROM Attachment WHERE ParentId =:orgId AND Name =: SfdxAPIHelper.DX_DEFINITION_FILE];
            String definitionBody = '';
            if(!attDefinition.isEmpty()){
                definitionBody = attDefinition[0].Body.toString();
            }
            List<Attachment> metadataSources = [SELECT Body FROM Attachment WHERE ParentId =:orgId AND Name =: SfdxAPIHelper.DX_METADATA_SOURCES];
            SfdxAPIHelper.ScratchOrgDefinition orgTemplate = (SfdxAPIHelper.ScratchOrgDefinition) JSON.deserialize(definitionBody, SfdxAPIHelper.ScratchOrgDefinition.class);
            orgTemplate.orgName = tRun.Name+' Scratch Org';
            orgTemplate.username = '';
            String oT = JSON.serialize(orgTemplate);
            String mdSource = '';
            if(metadataSources.size()>0){
                metadataSources[0].Body.toString();
            }
            System.debug(LoggingLevel.INFO,'***mdSource :'+mdSource);
            //DevHub // to calculate
            // Org Name Scratch Org Name
            //Source Branch should be dx branch

            SfdxAPI.fullScratchOrg(oT,devHubId,soName, 1,null,null, null, null, sourceBranch, null,null,mdSource,null,null,'false');
        } else{
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, Label.Test_Run_Is_Empty));
        }

        return null;
    }

    public String getFlowDXDestination(){
        return flowStepsMap.containsKey(selectedStep) && flowStepsMap.get(selectedStep) != null ? flowStepsMap.get(selectedStep).Source_Environment__c : null;
    }

    public void deploymentFlowOperations() {
        system.debug('ScratchOrgCompletionController_deploymentFlowOperations: '+ showDeploymentFlow);
        if (!showDeploymentFlow) return;
        depFlowId = String.valueOf(findDeploymentFlowId());
        if (depFlowId == null) showDeploymentFlow = false;
        Deployment_Flow__c depFlow = [
                SELECT Id, Name, (
                        SELECT Id,Name,Enable_as_Scratch_Org_Destination__c,Destination_Environment__c,
                                Destination_Environment__r.Name,Source_Environment__c,Source_Environment__r.Name
                        FROM Deployment_Flow_Steps__r
                        WHERE Enable_as_Scratch_Org_Destination__c != NULL
                )
                FROM Deployment_Flow__c
                WHERE Id = :depFlowId
                LIMIT 1
        ];
        deploymentFlowName = depFlow.Name;
        dxTargetFlowSteps = new List<SelectOption>();
        Id addedDefaultTarget;
        for (Deployment_Flow_Step__c dfs : depFlow.Deployment_Flow_Steps__r) {
            if(dfs.Enable_as_Scratch_Org_Destination__c == 'Default DX Target') {
                addedDefaultTarget = dfs.Id;
                String optionName = dfs.Source_Environment__r.Name + '-->' + dfs.Destination_Environment__r.Name;
                selectedStep = dfs.Source_Environment__c;
                dxTargetFlowSteps.add(new SelectOption(dfs.Source_Environment__c, optionName));
                flowStepsMap.put(dfs.Source_Environment__c,dfs);
                break;
            }
        }
        dxTargetFlowSteps.add(new SelectOption('', '-- None --'));
        for (Deployment_Flow_Step__c dfs : depFlow.Deployment_Flow_Steps__r) {
            if(addedDefaultTarget == dfs.Id) continue;
            String optionName = dfs.Source_Environment__r.Name + '-->' + dfs.Destination_Environment__r.Name;
            dxTargetFlowSteps.add(new SelectOption(dfs.Source_Environment__c, optionName));
            flowStepsMap.put(dfs.Source_Environment__c,dfs);
        }

    }

    private Id findDeploymentFlowId() {
        system.debug('ScratchOrgCompletionController_findDeploymentFLowId: '+ parentStandardControllerId);
        if (parentStandardControllerId == null) return null;
        if (parentStandardControllerType == Schema.SObjectType.User_Story__c.getSobjectType()) {
            User_Story__c us = [SELECT Id,Project__c,Project__r.Deployment_Flow__c,Project__r.Deployment_Flow__r.Git_Repository__c,Release__c,Release__r.Project__r.Deployment_Flow__c,Release__r.Project__r.Deployment_Flow__r.Git_Repository__c FROM User_Story__c WHERE Id = :parentStandardControllerId LIMIT 1];

            if (us.Project__r.Deployment_Flow__c != null) {
                depFlowGitRepoId = us.Project__r.Deployment_Flow__r.Git_Repository__c;
                system.debug('ScratchOrgCompletionController_depFlowGitRepoId: '+ depFlowGitRepoId);
                return us.Project__r.Deployment_Flow__c;
            } else if (us.Release__r.Project__r.Deployment_Flow__c != null) {
                depFlowGitRepoId = us.Release__r.Project__r.Deployment_Flow__r.Git_Repository__c;
                system.debug('ScratchOrgCompletionController_depFlowGitRepoId: '+ depFlowGitRepoId);
                return us.Release__r.Project__r.Deployment_Flow__c;
            }
        }
        return null;
    }
}