objects/Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Environmental_Variable__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipName>Environmental_Variables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Environment Variable</label>
    <nameField>
        <label>Environment Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environment Variables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EnvironmentalVariableTriggerHelpler.cls
public class EnvironmentalVariableTriggerHelpler {
    
    public static Map<String,Boolean> MexistingEv {get;set;}
    
    public static void prepareData () {
        
        MexistingEv = new Map<String,Boolean>();
        
        for (Environmental_Variable__c ev :[SELECT Name, Environment__c FROM Environmental_Variable__c]) {
            MexistingEv.put(ev.Name + '' + ev.Environment__c, true);
        }
    }
    
    public static void checkForDuplicates (Environmental_Variable__c evIn) {

        if (MexistingEv.containsKey(evIn.Name + '' + evIn.Environment__c)) {
            evIn.addError(Label.DUPLICATED_ENVIRONMENTAL_VARIABLE);
        }
    }
}