objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Org ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</description>
        <inlineHelpText>Environment records are created automatically when Org Credentials are authenticated. The Environment may have multiple Org Credentials which correspond to different users of the same Environment.</inlineHelpText>
        <label>Environment</label>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oauth_Signature__c</fullName>
        <description>This value is automatically set and updated by Copado.</description>
        <inlineHelpText>This value is automatically set and updated by Copado.</inlineHelpText>
        <label>Oauth Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EnvironmentTriggerHelper.cls
public with sharing class EnvironmentTriggerHelper {
    public static Map<Id, Id> envsToUpdate; // map of environment id -> new Org_ID__c to update

    public static void prepareData(){
        envsToUpdate = new Map<Id, Id>();
        if(Trigger.newmap != null && Trigger.oldmap != null ) {
            for( Id envId : Trigger.newMap.keySet() ) {
                Id orgId = ((Environment__c)Trigger.newMap.get( envId )).Org_ID__c;
                if( String.isNotEmpty(orgId) && orgId != ((Environment__c)Trigger.oldMap.get( envId )).Org_ID__c ) {
                    envsToUpdate.put(envId, orgId);
                }
            }
        }
    }

    public static void updateOrgCredentials(){
        if(envsToUpdate==null) return;
        List<Org__c> orgsToUpdate = [SELECT Id, Environment__c, SFDC_Org_ID__c, Validated_Date__c FROM Org__c WHERE Environment__c IN :envsToUpdate.keySet()];
        for(Org__c org : orgsToUpdate) {
            List<String> ts = org.SFDC_Org_ID__c.split('_', 2);
            org.Validated_Date__c = null;
            org.oauth_signature__c = null;
            if(ts.size()>0) {
                ts[0] = envsToUpdate.get(org.Environment__c);
                org.SFDC_Org_ID__c = String.join(ts, '_');
            }else{
                System.debug('WARNING: an org credential had an invalid SFDC_Org_ID__c '+org.Id+' '+org.SFDC_Org_ID__c);
            }
        }
        Utilities.Secure_DML(orgsToUpdate, Utilities.DML_Action.UPS, schema.Sobjecttype.Org__c);
    }
}