objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Commit_Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Commit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Commits</relationshipLabel>
        <relationshipName>Git_Org_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the commit. This value is updating automatically by Copado.</description>
        <inlineHelpText>The status of the commit. This value is updating automatically by Copado.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Commit undone</fullName>
                </value>
                <value>
                    <fullName>Commit not in branch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Last_Git_Backup_Datetime__c</fullName>
        <label>Last Git Backup Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Git_Backup_Status__c</fullName>
        <label>Last Git Backup Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>OK</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestGitOrgCommitTriggerHandler.cls
@isTest
private class TestGitOrgCommitTriggerHandler {

    static testMethod void test_after_insert() {
        Integer BATCH_SIZE = 3;
        List<Org__c> testOrgs = new List<Org__c>();
        for (Integer i = 0; i < BATCH_SIZE; i++) {
            Org__c testOrg = testMethodUtilities.create('My test org' + i, 'Production', '', 'testOrgId' + i, '', '', null);
            testOrg.Last_Git_Backup_Datetime__c = null;
            testOrg.Last_Git_Backup_Status__c = '';
            testOrgs.add(testOrg);
        }
        insert testOrgs;

        List<Git_Org_Commit__c> testGOCs = new List<Git_Org_Commit__c>();
        for (Integer i = 0; i < BATCH_SIZE; i++) {
            Git_Org_Commit__c testGoc = new Git_Org_Commit__c(
            Status__c = 'In Progress');
            testGoc.Org__c = testOrgs[i].Id;
            
            testGOCs.add(testGoc);
        }
        User_Story__c testUserStory = CMTestMethodUtilities.createUserStory('test');
        insert testUserStory;


        Test.startTest();
        insert testGOCs;
        List<Git_Org_Commit__c> updateGOCs = new List<Git_Org_Commit__c>();
        List<User_Story_Commit__c> usCommits = new List<User_Story_Commit__c>();
        for (Integer i = 0; i < BATCH_SIZE; i++) {
            User_Story_Commit__c usCommit = new User_Story_Commit__c(

                User_Story__c = testUserStory.Id,
                Snapshot_Commit__c = testGOCs[i].Id
            );
            usCommits.add(usCommit);
            Git_Org_Commit__c temp = testGOCs[i];
            temp.Status__c = 'Complete';
            temp.Commit_ID__c = '213234283748243' + i;
            updateGOCs.add(temp);
        }
        insert usCommits;
        
        update updateGOCs;
        Test.stopTest();

        Set<Id> resultIdSet = new Set<Id>();
        for (Git_Org_Commit__c g : testGOCs) {
            resultIdSet.add(g.Id);
        }

        List<Git_Org_Commit__c> results = [select Id, Commit_Date__c, Org__c, Org__r.Last_Git_Backup_Status__c, Org__r.Last_Git_Backup_Datetime__c from Git_Org_Commit__c where Id IN :resultIdSet];
        system.assertEquals(3, results.size());
        for (Git_Org_Commit__c g : results) {
            system.assert(g.Org__r.Last_Git_Backup_Datetime__c != null);
            system.assertEquals('OK', g.Org__r.Last_Git_Backup_Status__c);
            system.assertNotEquals(null, g.Commit_Date__c);
        }
    }
}