objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Commit_Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Commit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Commit_Message__c</fullName>
        <label>Commit Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Git_Backup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Snapshot</label>
        <referenceTo>Git_Backup__c</referenceTo>
        <relationshipName>Git_Org_Commits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Commits</relationshipLabel>
        <relationshipName>Git_Org_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the commit. This value is updating automatically by Copado.</description>
        <inlineHelpText>The status of the commit. This value is updating automatically by Copado.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Commit undone</fullName>
                </value>
                <value>
                    <fullName>Commit not in branch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestUserStoryImportSetController.cls
@isTest
public class TestUserStoryImportSetController {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }
    public class testData {
        public List<User_Story__c> userStories = new List<User_Story__c>();
        public User_Story__c usResult = new User_Story__c();
        public List<User_Story_Commit__c> usCommits = new List<User_Story_Commit__c>();
        public List<Git_Org_Commit__c> commits = new List<Git_Org_Commit__c>();
        public List<Attachment> commitAttachments = new List<Attachment>();
        User_Story__c usWithoutcommits;
    }
    
    static testData generateData() {
        testData D = new testData();
        Org__c o = new Org__c(name = 'test');
        insert o;
        
        Git_Repository__c r = new Git_Repository__c(name='test');
        insert r;
        
        Git_Backup__c bk = new Git_Backup__c(Git_Repository__c = r.id, Org__c = o.id);
        insert bk;
        
        Git_Org_Commit__c c1 = new Git_Org_Commit__c(Git_Backup__c = bk.id, Org__c = o.id, Commit_Id__c='b7adccf3937495e8928d1023c5a5c644198b8974', Commit_Date__c=Date.today(),Commit_Message__c='test', Status__c ='Complete');
        insert c1;

        Git_Org_Commit__c c2 = new Git_Org_Commit__c(Git_Backup__c = bk.id, Org__c = o.id, Commit_Id__c='b7adccf3937495e8928d1023c5a5c644198b8975', Commit_Date__c=Date.today(),Commit_Message__c='test 2', Status__c ='Complete');
        insert c2;

        // Metadata selections via the grid
        Attachment att1 = new Attachment(ParentId=c1.Id, Name='Metadata', Body=Blob.valueOf('[{"t":"EmailTemplate","n":"Template1","s":true,"r":true}, {"t":"EmailTemplate","n":"Template2","s":false}]'));
        insert att1;
        // insert separately, so it is the latest attachment
        Attachment att2 = new Attachment(ParentId=c2.Id, Name='Metadata', Body=Blob.valueOf('[{"t":"EmailTemplate","n":"Template1","s":true,"r":false}, {"t":"EmailTemplate","n":"a_Template","s":true}]'));
        insert att2;
        D.commitAttachments.add(att1);
        D.commitAttachments.add(att2);
        
	    User_Story__c us = new User_Story__c();
        insert us;
	    User_Story__c us2 = new User_Story__c();
        insert us2;
        D.userStories.add(us);
        D.userStories.add(us2);

	    D.usWithoutcommits = new User_Story__c();
        insert D.uswithoutcommits;
        
        // user story that will hold the results
        insert D.usResult;
        
        String usName = [select Name from User_Story__c where id=:us.Id].Name;
        User_Story_Commit__c uc1 = new User_Story_Commit__c(User_Story__c = us.id, Snapshot_Commit__c = c1.id);
        insert uc1;
        D.usCommits.add(uc1);
        User_Story_Commit__c uc2 = new User_Story_Commit__c(User_Story__c = us2.id, Snapshot_Commit__c = c2.id);
        insert uc2;
        D.usCommits.add(uc2);
        return D;
	}
    
    static testMethod void test_empty(){
        testData D = generateData();
        
        // now "select" a few US in "userStories", and test the controller
        PageReference pageRef = Page.UserStoryAssignment;
        Test.setCurrentPage(pageRef);
        
        List<User_Story__c> empties = new List<User_Story__c>();
        empties.add(D.usWithoutcommits);
        
        ApexPages.StandardSetController con = new ApexPages.StandardSetController(empties);
        UserStoryImportSetController ext = new UserStoryImportSetController(con);
        ext.records = empties;
        ext.initPage();
        
        Test.startTest();
        ext.dummy.User_Story__c = D.usResult.Id;
        PageReference result = ext.assign();
        system.assertEquals( null, result, 'User stories without metadata should show an error message');
        Test.stopTest();
    }
    
    static testMethod void test_with_commits(){
        testData D = generateData();
        
        // now "select" a few US in "userStories", and test the controller
        PageReference pageRef = Page.UserStoryAssignment;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardSetController con = new ApexPages.StandardSetController(D.userStories);
        UserStoryImportSetController ext = new UserStoryImportSetController(con);
        ext.records = D.userStories;
        ext.initPage();
        System.assertEquals(2, D.userStories.size());
        System.assertEquals(2, ext.records.size());
        
        Test.startTest();
        ext.dummy.User_Story__c = D.usResult.Id;
        PageReference result = ext.assign();

        PageReference pref = Page.UserStoryCommitIntermediary;
        String expected = pref.getUrl();

        system.assertNotEquals( null, result, 'User stories with metadata should be able to advance, but it threw an error');
        system.assert( result.getUrl().startsWith(expected), 'got: '+result.getUrl()+' expected: '+expected+';' );
        system.assertEquals( result.getParameters().get('id'), D.usResult.Id );
        system.assertNotEquals( result.getParameters().get('MetadataPreselectionId'), '' );
        
        String aid = result.getParameters().get('MetadataPreselectionId');
        Attachment a = [SELECT Id, Body FROM Attachment WHERE id = :aid];
        System.debug('Body='+a.Body.toString());
        List<UserStoryImportSetController.MetaDataItem> metadata = (List<UserStoryImportSetController.MetaDataItem>)JSON.deserialize(a.Body.toString(), List<UserStoryImportSetController.MetaDataItem>.class);
        integer timesFound = 0;
        for(UserStoryImportSetController.MetaDataItem mi : metadata) {
            System.debug('-rs: '+mi.s+' '+mi.r+' '+mi.n+' '+mi+' ; '+mi.t.equals('EmailTemplate') +','+ mi.n.equals('Template1'));
            if(mi.t.equals('EmailTemplate') && mi.n.equals('Template1') ) {
		        system.assertNotEquals( true, mi.r );
                timesFound++;
            }
        }
        system.assertEquals( 1, timesFound );
        Test.stopTest();        
    }
}