objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Schedule automatic metadata backups. With the frequency set, Copado will automatically commit the metadata components of the Org into the Branch.</description>
        <inlineHelpText>Schedule automatic metadata backups. With the frequency set, Copado will automatically commit the metadata components of the Org into the Branch.</inlineHelpText>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSettings.cls
@isTest
public class TestSettings {
    @testSetup static void setupData() {
        TestUtilities.setTestSettingsEE();
    }
    @testSetup static void setupDataDML() {
        testMethodUtilities.upsertOrgwideSettings();
    }
    @isTest static void testFull(){   	

    	Test.startTest();

        Settings con = new Settings();
        System.assertNotEquals(null,con.urlBase);
        System.assertNotEquals(null,Settings.ns);
        System.assertNotEquals(null,Settings.copado_site);
        System.assertNotEquals(null,Settings.server_url);

        Test.stopTest();

    }
    static testMethod void testConstructors(){
        Settings s1 = new Settings(new ApexPages.StandardController(new Org__c()));
        Settings s2 = new Settings(new GitCommitLookupController());
        System.assert(s1 != s2);
    }
    
    static testMethod void testGitCommitChangesControllerInit(){
        Org__c o1 = testMethodUtilities.create('test', 'Production/Developer', null, null, null, null, System.now());
        insert o1;
        Git_Repository__c gr = testMethodUtilities.create('Test repo', 'test', 'test', 'testUri');
        insert gr;
        
        Git_Backup__c gitBackup = new Git_Backup__c(Name='test', Frequency__c='none', Org__c=o1.Id, Git_Repository__c=gr.Id);
        insert gitBackup;
        User_Story__c us = CMTestMethodUtilities.createUserStory('test');
        insert us;
        
        PageReference pref = new PageReference('/apex/test');
		pref.getParameters().put('snapshotId', gitBackup.Id);
        pref.getParameters().put('userStoryId', us.Id);
		Test.setCurrentPage(pref);
        
        Settings s = new Settings(new GitCommitChangesController());
        s.userStoryObj = us;
        String result = s.getUserStoryAsJSON();
                
        System.assertEquals(true, result.contains('User_Story__c'));        
    }

    static testMethod void testLicenseWrapper(){
        Settings.LicenseWrapper s = new Settings.LicenseWrapper(true,true,true,true,true,true);
        System.assertEquals(true,s.hasCAD);
        String currentLicenses = Settings.getCurrentUserLicenses();

    }
}