objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserStoryCommitTriggerHelper.cls
public without sharing class UserStoryCommitTriggerHelper {
	public static Map<String,String> cmMap = new Map<String,String>();
    public static Map<String,String> usMap = new Map<String,String>();
    public static void prepareData(){
        if(Trigger.isInsert){
         	for(SObject so:Trigger.new){
                User_Story_Commit__c uc = (User_Story_Commit__c)so;
                cmMap.put(uc.Snapshot_Commit__c,null);
                usMap.put(uc.User_Story__c, null);
            }
            for(Git_Org_Commit__c c:[Select Id,Commit_Id__c from Git_Org_Commit__c where id in:cmMap.keySet()]){
                cmMap.put(c.Id, c.Commit_Id__c);
            }
            for(User_Story__c us:[Select Id,Name from User_Story__c where id in:usMap.keySet()]){
                usMap.put(us.Id, us.Name);
            }   
        }
    }
    public static void setNewDefaults(User_Story_Commit__c c){
        if(!(usMap.get(c.User_Story__c) !=null && cmMap.get(c.Snapshot_Commit__c)!=null && cmMap.get(c.Snapshot_Commit__c).length() >30))return;
        c.Name = usMap.get(c.User_Story__c) + ' ' + cmMap.get(c.Snapshot_Commit__c).substring(0,7);
        c.External_Id__c = c.User_Story__c + '_' + cmMap.get(c.Snapshot_Commit__c);
    }
}