objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GitCommitLookupController.cls
public with sharing class GitCommitLookupController{
    public String selectedRepository {get;set;}
    //public Git_Backup__c dummyBackup {get;set;}
    
    public GitCommitLookupController(){
        selectedRepository = '';
    }
    public static List<SelectOption> getRepositories(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','-- Select --'));
        for(Git_Repository__c r : [select Id, Name from Git_Repository__c order by Name DESC limit 200]){
            options.add(new SelectOption(r.Id, r.Name));
        }
        return options;
    }
    public string getFormTag() {
        return System.currentPageReference().getParameters().get('frm');
    }
    public string getTextBox() {
        return System.currentPageReference().getParameters().get('txt');
    }
}