objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <defaultValue>&quot;master&quot;</defaultValue>
        <description>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</description>
        <inlineHelpText>Branch of the selected Git Repository (e.g. master). Snapshots and Commits done in the Git Snapshot will affect the specified branch.</inlineHelpText>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commit_Date__c</fullName>
        <label>Commit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Commit_Message__c</fullName>
        <label>Commit Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Commits</relationshipLabel>
        <relationshipName>Git_Commits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Git Commit</label>
    <nameField>
        <displayFormat>Commit-{0000}</displayFormat>
        <label>Git Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Git Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Commit_Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Commit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Commit_Message__c</fullName>
        <label>Commit Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Git_Backup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Snapshot</label>
        <referenceTo>Git_Backup__c</referenceTo>
        <relationshipName>Git_Org_Commits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the commit. This value is updating automatically by Copado.</description>
        <inlineHelpText>The status of the commit. This value is updating automatically by Copado.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Commit undone</fullName>
                </value>
                <value>
                    <fullName>Commit not in branch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GitHelper.cls
public class GitHelper {
    public static Map<String,ACommit>  commitMap = new Map<String,ACommit>();
    
    public static List<ACommit> getCommits(String repositoryId, String branch, Date fromDate, Date toDate, String startCommit, String endCommit, Integer lim){
        System.debug('Commit filter repositoryId = ' + repositoryId);
        System.debug('Commit from date = ' + fromDate);
        System.debug('Commit to date = ' + toDate);
        commitMap = new Map<String,ACommit>();
        List<ACommit> res = new List<ACommit>();
        
        List<Git_Org_Commit__c> list1 = new List<Git_Org_Commit__c>();
        if(String.isNotBlank(branch)){
            list1 = [select Commit_Id__c, Commit_Date__c, Commit_Message__c, Git_Backup__r.Branch__c from 
                                 Git_Org_Commit__c where 
                                 Git_Backup__r.Git_Repository__c=:repositoryId and
                                 Git_Backup__r.Branch__c=:branch and
                                 Commit_Date__c >=:fromDate and 
                                 Commit_Date__c <=:toDate and
                                 Status__c = 'Complete'
                                 order by Commit_Date__c desc, CreatedDate desc limit :lim];
        }
        else{
            list1 = [select Commit_Id__c, Commit_Date__c, Commit_Message__c, Git_Backup__r.Branch__c from 
                                 Git_Org_Commit__c where 
                                 Git_Backup__r.Git_Repository__c=:repositoryId and
                                 Commit_Date__c >=:fromDate and 
                                 Commit_Date__c <=:toDate and
                                 Status__c = 'Complete'
                                 order by Commit_Date__c desc, CreatedDate desc limit :lim];
        }
        for(Git_Org_Commit__c t:list1){
			//add commit without dupes
			if(!commitMap.containsKey(t.Commit_Id__c)){
                ACommit z = new ACommit(t.Commit_Id__c,t.Commit_Message__c,t.Commit_Date__c, t.Git_Backup__r.Branch__c);
				commitMap.put(t.Commit_Id__c,z);
                res.add(z);
            } 
        }
        System.debug('found ' + res.size() + ' git org commits for repository ' + repositoryId);
        List<Git_Commit__c> list2 = new List<Git_Commit__c>();
        if(String.isNotBlank(branch)){
            list2 = [select Commit_Id__c, Commit_Date__c, Commit_Message__c, Branch__c from 
                                 Git_Commit__c where 
                                 Git_Repository__c=:repositoryId and
                             	 Branch__c=:branch and
                                 Commit_Date__c >=:fromDate and 
                                 Commit_Date__c <=:toDate
                                 order by Commit_Date__c desc, CreatedDate desc limit :lim];
        }
        else{
            list2 = [select Commit_Id__c, Commit_Date__c, Commit_Message__c, Branch__c from 
                                 Git_Commit__c where 
                                 Git_Repository__c=:repositoryId and
                                 Commit_Date__c >=:fromDate and 
                                 Commit_Date__c <=:toDate
                                 order by Commit_Date__c desc, CreatedDate desc limit :lim];
        }
        for(Git_Commit__c t:list2){
			//add commit without dupes
			if(!commitMap.containsKey(t.Commit_Id__c)){
                ACommit z = new ACommit(t.Commit_Id__c,t.Commit_Message__c,t.Commit_Date__c, t.Branch__c);
				commitMap.put(t.Commit_Id__c, z);
                res.add(z);
            }
        }
        System.debug('total found ' + res.size() + ' git org commits and git commits for repository ' + repositoryId);
        res.sort();
        if(String.isNotBlank(startCommit) && String.isBlank(endCommit)){
            List<ACommit> t = new List<ACommit>();
            for(ACommit c:res){
                t.add(c);
                if(c.id == startCommit)break;
            }
            res = t;
        }
        return res;
    }
    
    public class ACommit implements Comparable{
        public String id{get;set;}
        public String message{get;set;}
        public DateTime cdate{get;set;}
        public String branch{get;set;}
        public ACommit(String id, String message, DateTime cdate, String branch){
            this.id = id;
            this.message = message;
            this.cdate = cdate;
            this.branch = branch;
        }
        public Integer compareTo(Object o){
            ACommit c = (ACommit)o;
            if(c.cdate > this.cdate)return 1;
            if(c.cdate < this.cdate)return -1;
            return 0;
        }
    }
}