objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Commit_Date__c</fullName>
        <label>Commit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Commits</relationshipLabel>
        <relationshipName>Git_Commits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Git Commit</label>
    <nameField>
        <displayFormat>Commit-{0000}</displayFormat>
        <label>Git Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Git Commits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>Commit_Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <label>Commit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Commit_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Commit Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Git_Backup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Git Snapshot</label>
        <referenceTo>Git_Backup__c</referenceTo>
        <relationshipName>Git_Org_Commits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Snapshot Commits</relationshipLabel>
        <relationshipName>Git_Org_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the commit. This value is updating automatically by Copado.</description>
        <inlineHelpText>The status of the commit. This value is updating automatically by Copado.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Commit undone</fullName>
                </value>
                <value>
                    <fullName>Commit not in branch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestDeployCommits.cls
@isTest
private class TestDeployCommits {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }
    static testMethod void sortList(){
        List<GitHelper.ACommit> li = new List<GitHelper.ACommit>();
        li.add(new GitHelper.ACommit('today','today', DateTime.now(), 'master'));
        DateTime yest = DateTime.now().addDays(-1);
		li.add(new GitHelper.ACommit('yesterday','yesterday', yest, 'master'));
        DateTime tomw = DateTime.now().addDays(1);
		li.add(new GitHelper.ACommit('tomorrow','tomorrow', tomw, 'master'));
        System.assertEquals('today', li.get(0).id);
        System.assertEquals('yesterday', li.get(1).id);
        System.assertEquals('tomorrow', li.get(2).id);
        li.sort();
        System.assertEquals('tomorrow', li.get(0).id);
        System.assertEquals('today', li.get(1).id);
        System.assertEquals('yesterday', li.get(2).id);
    }
    static testMethod void getCommits(){
        DateTime yest = DateTime.now().addDays(-1);
        DateTime lasty = DateTime.now().addYears(-2);
        DateTime tomw = DateTime.now().addDays(1);
        Git_Repository__c repo = new Git_Repository__c(name='test repo');
        insert repo;
        Git_Commit__c c1 = new Git_Commit__c(Commit_Id__c = 'today', Commit_Date__c = DateTime.now().date(), Git_Repository__c = repo.Id);
        insert c1;
        Git_Commit__c c2 = new Git_Commit__c(Commit_Id__c = 'yesterday', Commit_Date__c = yest.date(), Git_Repository__c = repo.Id);
        insert c2;
        Git_Commit__c c3 = new Git_Commit__c(Commit_Id__c = 'tomorrow', Commit_Date__c = tomw.date(), Git_Repository__c = repo.Id);
        insert c3;
        
        Org__c o = new Org__c (name='test org');
        insert o;
        Git_Backup__c snap = new Git_Backup__c(name='test snapshot', git_repository__c = repo.id, org__c = o.id);
        insert snap;
        Git_Org_Commit__c c22 = new Git_Org_Commit__c(Commit_Id__c = 'yesterday', Commit_Date__c = yest.date(), Git_Backup__c = snap.Id, org__c = o.id, Status__c='Complete');
        insert c22;
        Git_Org_Commit__c c4 = new Git_Org_Commit__c(Commit_Id__c = 'last 2 year', Commit_Date__c = lasty.date(), Git_Backup__c = snap.Id, org__c = o.id, Status__c='Complete');
        insert c4;
        
        DeployCommits dc = new DeployCommits();
        dc.repositoryId = repo.Id;
        
        List<GitHelper.ACommit> li = dc.getCommits();
        System.assertEquals(3, li.size());
        System.assertEquals('tomorrow', li.get(0).id);
        System.assertEquals('today', li.get(1).id);
        System.assertEquals('yesterday', li.get(2).id);
        
        dc.dateFrom.Commit_Date__c = lasty.date();
        li = dc.getCommits();
        System.assertEquals(4, li.size());
        System.assertEquals('tomorrow', li.get(0).id);
        System.assertEquals('today', li.get(1).id);
        System.assertEquals('yesterday', li.get(2).id);
        System.assertEquals('last 2 year', li.get(3).id);
    }
}