objects/Git_Backup__c.object
<CustomObject>
    <fields>
        <fullName>Git_Repository__c</fullName>
        <description>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</description>
        <inlineHelpText>Git Repository linked to the Git Snapshot. The specified Branch must exist in the Git Repository.</inlineHelpText>
        <label>Git Repository</label>
        <referenceTo>Git_Repository__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</description>
        <inlineHelpText>A validated Org Credential used to retrieve the metadata that will be committed to the specified Branch in the Git Snapshot.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Git Snapshots</relationshipLabel>
        <relationshipName>Git_Backups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Git Snapshot</label>
    <nameField>
        <label>Git Snapshot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Git_Repository__c.object
<CustomObject>
    <description>Connection to a git repository like github.com or bitbuckets.org</description>
    <label>Git Repository</label>
    <nameField>
        <label>Git Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Git Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestGitBackupTrigger.cls
@isTest
private class TestGitBackupTrigger {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }
    static testMethod void test_OrgTrigger() {
        BatchHelper.enforceScheduler();
        CronJobDetail cjd = [select id from CronJobDetail where Name ='Copado' and JobType='7' limit 1];
    	if(BatchHelper.isCopadoScheduled()){
    		System.abortJob([select id from CronTrigger where CronJobDetailId =:cjd.Id limit 1].Id);
    	}
	    System.assertEquals(false, BatchHelper.isCopadoScheduled());

        Org__c org = testMethodUtilities.create('OrgName','Production','PASSWORD','SFDC_OrgId2','SFDC_TOKEN','USERNAME', System.now());
        insert org;
        update org;
        Git_Repository__c gitRepo = testMethodUtilities.create('test','username','password','http://www.test.uri');
        insert gitRepo;
        update gitRepo;
        Git_Backup__c gitBackup = testMethodUtilities.create('backupname', 'branchName', 'Daily', gitRepo, null, org);
        insert gitBackup;
        update gitBackup;
        System.assertEquals(true,FeatureHelper.isFeatureEnabled('Git Backup'));
        System.assertEquals(true, BatchHelper.isCopadoScheduled());

        /*

        //TODO: this must be refactored or separated on another test class without lics


        Test.startTest();
        TestUtilities.exceedCopadoLicenses();
        try {
            update gitBackup;
            System.assert(false,'this must fail');
        } catch(Exception e){
            System.assert(true, e.getMessage().contains(Label.LICENSES_EXCEEDED));
        }
        TestUtilities.enableLicenses(2, 2, 2);

        try {
            update gitBackup;
            System.assert(false,'this must fail');
        } catch(Exception e){
            System.assert(true, e.getMessage().contains(Label.FEATURE_NOT_SUPPORTED + ': Git Backup'));
        }
        Test.stopTest();
        */

    }
}