objects/Kanban_Board__c.object
<CustomObject>
    <description>The Kanban board editor allows admins to define the Kanban board definition, giving users complete flexibility on the Kanban board function and usage.  Any object can be queried and any picklist or lookup field can be updated.</description>
    <fields>
        <fullName>Columns_SOQL__c</fullName>
        <inlineHelpText>SOQL Query to retrieve the columns. Id and Name fields will be used to generate the list.</inlineHelpText>
        <label>Columns from SOQL</label>
        <length>20480</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field_to_read_update__c</fullName>
        <inlineHelpText>Field to read/update for each Item. In &quot;object.field&quot; format</inlineHelpText>
        <label>Field to read/update</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JSON_Settings__c</fullName>
        <label>JSON Settings</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOQL_Query__c</fullName>
        <inlineHelpText>SOQL Query to retrieve each Id, Title (second field in the query), and the &quot;Status&quot; field, as defined in Field to read/update. Every other field will be shown as the text content of the item.</inlineHelpText>
        <label>SOQL Query</label>
        <length>20480</length>
        <type>LongTextArea</type>
    </fields>
    <label>Kanban Board</label>
    <nameField>
        <label>Kanban Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kanban Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/KanbanBoard.cls
public with sharing class KanbanBoard {
    private Kanban_Board__c obj;
    private Map<String, String> myMap;

    public KanbanBoard(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String> {
                'Name',
                'SOQL_Query__c',
                'Field_to_read_update__c',
                'Description__c',
                'Columns_SOQL__c',
                'JSON_Settings__c'
            });
        }
        this.obj = (Kanban_Board__c)stdController.getRecord();        
        getJSonRecord();
    }

    public String getJSonRecord() {
        // NOTE: needed due to namespacing
        if (myMap != null) {
            return JSON.serialize(myMap);
        } else {
            myMap = new Map<String, String> {
                'Id' => obj.Id,
                'Name' => obj.Name,
                'SOQL_Query__c' => obj.SOQL_Query__c,
                'Field_to_read_update__c' => obj.Field_to_read_update__c,
                'JSON_Settings__c' => obj.JSON_Settings__c,
                'Columns_SOQL__c' => obj.Columns_SOQL__c,
                'Description__c' => obj.Description__c
            };

            return JSON.serialize(myMap);
        }
    }
}