objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scratch_Org_Status__c</fullName>
        <label>Scratch Org Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DXTestOrgIntermediaryController.cls
/**
 * Created by ferhatozsavran on 3/14/18.
 */

public with sharing class DXTestOrgIntermediaryController {

    private final Test_Run__c testRun;

    public DXTestOrgIntermediaryController(ApexPages.StandardController stdController) {
        if(!Test.isRunningTest()){
            stdController.addFields(new List<String>{'Name'});
        }
        this.testRun = (Test_Run__c)stdController.getRecord();
    }

    public PageReference redirectPage(){
        if(String.isNotBlank(testRun.Name)){
            String orgName = testRun.Name + ' Scratch Org';
            List<Org__c> orgList = [Select Id From Org__c Where Name =: orgName And Org_Type__c = 'Scratch Org - Test Only' And Scratch_Org_Status__c = 'Active' Order By CreatedDate DESC Limit 1];

            if(!orgList.isEmpty()){
                PageReference pRef = Page.DXOperation;
                pRef.getParameters().put('id',orgList.get(0).Id);
                pRef.setRedirect(true);
                return pRef;
            } else{
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, Label.Test_Run_Error));
                return null;
            }
        } else{
            return null;
        }
    }
}