objects/Org__c.object
<CustomObject>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Selenium_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Webdriver_URL__c</fullName>
        <inlineHelpText>Eg for Browserstack:
http://USER:TOKEN@hub.browserstack.com:80/wd/hub

Eg for Saucelabs:
http://USER:TOKEN@ondemand.saucelabs.com:80/wd/hub/</inlineHelpText>
        <label>Webdriver URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Selenium Settings</label>
    <nameField>
        <label>Selenium Test Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Group__c.object
<CustomObject>
    <fields>
        <fullName>Manage_Test_Runs_manually__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this option is unchecked, Copado will automatically create/update/remove Test Runs for each Suite/Org Credential.

Check it to manage the Test Runs in this group manually, then go to a Test Run list view, and use the &quot;Add to Test Group&quot; option.</inlineHelpText>
        <label>Manage Test Runs manually</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Selenium_Settings__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>All tests runs belonging to this Test Group will use these Selenium Settings.</inlineHelpText>
        <label>Selenium Settings</label>
        <referenceTo>Selenium_Settings__c</referenceTo>
        <relationshipLabel>Selenium Test Groups</relationshipLabel>
        <relationshipName>Selenium_Test_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Selenium Test Group</label>
    <nameField>
        <label>Selenium Test Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Run__c.object
<CustomObject>
    <fields>
        <fullName>Selenium_Settings__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Copado will run the Test Suites for each of the selected Platforms in these Settings.</inlineHelpText>
        <label>Selenium Settings</label>
        <referenceTo>Selenium_Settings__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selenium_Test_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field should not be populated.  The value is automatically maintained.</inlineHelpText>
        <label>Selenium Test Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Selenium_Test_Group__c.Manage_Test_Runs_manually__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Selenium_Test_Group__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selenium_Test_Suite__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Selenium Test Suite</label>
        <referenceTo>Selenium_Test_Suite__c</referenceTo>
        <relationshipLabel>Selenium Test Runs</relationshipLabel>
        <relationshipName>Selenium_Test_Runs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Selenium Test Run</label>
    <nameField>
        <label>Selenium Test Run Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Selenium_Test_Suite__c.object
<CustomObject>
    <label>Selenium Test Suite</label>
    <nameField>
        <label>Selenium Test Suite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Suites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestMassAddRunsToGroup.cls
@isTest
public class TestMassAddRunsToGroup {
    @testSetup static void setupTestData(){
        TestUtilities.enableLicenses(10, 10, 10);
    }
    private static testMethod void TestMyLeadsController(){
        CMTestMethodUtilities.enableSelenium();
        Selenium_Settings__c s = new Selenium_Settings__c(Name = 'test settings', Webdriver_URL__c='http://drive.me');
        insert s;
        Selenium_Test_Group__c g = new Selenium_Test_Group__c(Name = 'test group', Selenium_Settings__c = s.id, Manage_Test_Runs_manually__c=true);
        insert g;
        Org__c org1 = testMethodUtilities.create('Test org1', 'sandbox', '', 'org-id-1', 'tk-1', 'test1@test.com', System.now());
        insert org1;
        Selenium_Test_Suite__c ts1 = new Selenium_Test_Suite__c(name='test suite1');
        insert ts1;

        Selenium_Test_Run__c tr = new Selenium_Test_Run__c(Name='test1',
                                                           Selenium_Test_Suite__c=ts1.Id,
                                                           Selenium_Settings__c=s.Id);
        List<Selenium_Test_Run__c> sels = new List<Selenium_Test_Run__c>();
        sels.add(tr);
            
		ApexPages.StandardSetController std = new ApexPages.StandardSetController(sels);
	    MassAddRunsToGroup custom  = new MassAddRunsToGroup(std);
		
		custom.Cancel();
		custom.add();
    }
}