objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CheckFeaturesController.cls
global with sharing class CheckFeaturesController {

	/**
	 * returns the static namespacevi
	 * @return [description]
	 */
	public String getNamespace(){
		return Settings.ns; 
	}

    /**
     * Async call to update features in custom settings if needed 
     */
    @RemoteAction
    global static void checkFeatures(){
        DeployAPI.checkSyncFeatures();
    }

    /**
     * Async call to check setup Org 
     */
    @RemoteAction
    global static Boolean checkSetup(){
        if (LicenseHelper.actionIsLicenseEnabled('viewSetupWarning')){
            String orgId = Userinfo.getOrganizationId()+'_'+Userinfo.getUserId();
            Org__c[] org = [SELECT ID FROM Org__c WHERE  Validated_Date__c != null AND SFDC_Org_ID__c = :orgId LIMIT 1];
            return !org.isEmpty();
        } 
        return true;
    	//String orgId = Userinfo.getOrganizationId()+'_'+Userinfo.getUserId();
    	//Org__c[] org = [SELECT ID FROM Org__c WHERE  Validated_Date__c != null AND SFDC_Org_ID__c = :orgId LIMIT 1];
     //   return !org.isEmpty();
    }
    
    /**
     * Async call to update features in custom settings if needed 
     */
    @RemoteAction
    global static void checkLicenses(){
        DeployAPI.checkSyncLicenses();
    }
}