objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>SFDC_Org_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Organization Id for the Environment.</description>
        <externalId>true</externalId>
        <inlineHelpText>Organization Id for the Environment.</inlineHelpText>
        <label>SFDC Org ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Validated_Date__c</fullName>
        <description>Latest OAuth authentication validation date.</description>
        <inlineHelpText>Latest OAuth authentication validation date.</inlineHelpText>
        <label>Validated Date</label>
        <type>DateTime</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCheckFeaturesController.cls
@isTest
private class TestCheckFeaturesController{
	@testSetup static void setupTestData(){
		TestUtilities.setTestSettingsEE();
	}
	static testMethod void testCheckFeatures(){
        
        String b = '{"features":[{"feature":"myname","enabled":true,"expirationDate":null}]}';
        //String b = '{"ok":"Git validated"}';
	    Test.setMock(HttpCalloutMock.class, new testHttpCalloutMock(b, null));
        
		Test.startTest();
		CheckFeaturesController.checkFeatures();
		Test.stopTest();

	}

	static testMethod void testCheckSetup(){
        
        Test.startTest();
        
		Boolean exists = CheckFeaturesController.checkSetup();
		System.assertEquals(false, exists);

		Org__c o = new Org__c(
			name = 'test', 
			SFDC_Org_ID__c = Userinfo.getOrganizationId()+'_'+Userinfo.getUserId(),
			Validated_Date__c = Datetime.now()
		);
		insert o;

		exists = CheckFeaturesController.checkSetup();
		System.assertEquals(true, exists);

		Test.stopTest();

	}
	/*
	 * These tests test the code on the FeatureHelper class.  
	 * As a test class does not exist for it, we will test the code here and later
	 * move it into the new test class so we can push this out to customers.		
	*/
    static testMethod void testGitBackupEnabled_CopadoUser(){
		System.assertEquals(true, FeatureHelper.isFeatureEnabled('Git Backup'));
    }
}