objects/Org__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Hub_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Hub Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Org__c.is_Developer_Hub_Org__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Type__c</fullName>
        <label>Org Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                    <default>true</default>
                    <label>Production/Developer</label>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
                <value>
                    <fullName>Scratch Org - Test only</fullName>
                </value>
                <value>
                    <fullName>Scratch Org</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scratch_Org_Expiration_Date__c</fullName>
        <label>Scratch Org Expiration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scratch_Org_Status__c</fullName>
        <label>Scratch Org Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Missing</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <fields>
        <fullName>Org__c</fullName>
        <label>Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts (User Story)</relationshipLabel>
        <relationshipName>Test_Scripts_UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DynamicScratchOrgController.cls
/**
 * Created by mertyalti on 01/02/2018.
 */

public with sharing class DynamicScratchOrgController extends ScratchOrgWizardPageBase {
    public Test_Run__c testRun {get;set;}
    private Id stdObjectId;
    private String sourceBranch;
    public String initialPageMessage {get;set;}
    public Boolean showInitialPageMessage {get;set;}
    public Boolean showComponent {get;set;} //only allowed for Scratch Org Related User Stories
    public DynamicScratchOrgController(ApexPages.StandardController std) {
        showComponent = true;
        showInitialPageMessage = true;
        stdObjectId = std.getId();
        Schema.sObjectType parentObject = stdObjectId.getSObjectType();

        if (parentObject == Schema.SObjectType.Test_Run__c.getSobjectType()) {
            testRunOperation();
        } else if (parentObject == Schema.SObjectType.Promotion__c.getSobjectType()) {

        } else {
            // TODO: page is not supported.
        }
    }
    private void testRunOperation(){
        testRun = [SELECT Id, Name, Test_Script__r.User_Story__r.Org_Credential__r.Org_Type__c , Test_Script__r.User_Story__r.Org_Credential__r.Developer_Hub_Org__c, Test_Script__r.User_Story__r.Org_Credential__c,Test_Script__r.User_Story__r.Name FROM Test_Run__c WHERE Id = :stdObjectId LIMIT 1];
        if (testRun.Test_Script__c != null && testRun.Test_Script__r.User_Story__c != null && testRun.Test_Script__r.User_Story__r.Org_Credential__c != null && testRun.Test_Script__r.User_Story__r.Org_Credential__r.Org_Type__c == 'Scratch Org' && testRun.Test_Script__r.User_Story__r.Org_Credential__r.Developer_Hub_Org__c != null) {
            Id orgId = testRun.Test_Script__r.User_Story__r.Org_Credential__c;
            Org__c usOrg = [SELECT Id,Org_Type__c,Scratch_Org_Expiration_Date__c,Scratch_Org_Status__c,Developer_Hub_Org__c FROM Org__c WHERE Id=:orgId];
            wizardDevHubId = usOrg.Developer_Hub_Org__c;
            sourceBranch = SfdxAPIHelper.DX_PROJECT_BRANCH+String.valueOf(testRun.Test_Script__r.User_Story__r.Org_Credential__c).substring(3,15);
            initialPageMessage = 'Test Scratch org will be created out of '+sourceBranch;
            try {
                Attachment attDefinition = getOrgAttachment(orgId,SfdxAPIHelper.DX_DEFINITION_FILE);
                Attachment attProject = getOrgAttachment(orgId,SfdxAPIHelper.DX_PROJECT_FILE);
                orgTemplate = (SfdxAPIHelper.ScratchOrgDefinition) JSON.deserialize(attDefinition.Body.toString(), SfdxAPIHelper.ScratchOrgDefinition.class);
                orgTemplate.orgName = testRun.Name+' Scratch Org';
                orgTemplate.username = '';
                artifactProject = (SfdxAPIHelper.sfdxProject) JSON.deserialize(attProject.Body.toString(), SfdxAPIHelper.sfdxProject.class);
            } catch(Exception ex) {
            	System.debug(loggingLevel.Error,'*** ERROR : '+ex.getMessage()); // TODO: Add page message
            }

        } else {
            showComponent = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'No org credentials found or missing configuration.'));
        }
    }

    private Attachment getOrgAttachment(Id ParentId, String attName){
        return [SELECT Id,Body,ParentId,Name FROM Attachment WHERE ParentId =:ParentId AND Name =: attName];
    }

    public PageReference loadReviewData() {
        if(orgTemplate != null && artifactProject != null){
            ScratchOrgCompletionController completionController = ((ScratchOrgCompletionController) getComponentController('ScratchOrgCompletion'));
            completionController.orgDefinition = orgTemplate;
            completionController.artifactProject = artifactProject;
            completionController.artifactDirectories = new List<SfdxAPIHelper.sfdxProjectArtifacts>();
            for (SfdxAPIHelper.sfdxProjectArtifacts art : artifactProject.packageDirectories) {
                Boolean defaultArtifact = art.defaultArtifact != null ? art.defaultArtifact : art.path == 'force-app' ? true : false;
                completionController.artifactDirectories.add(new SfdxAPIHelper.sfdxProjectArtifacts(art.path,defaultArtifact));
            }
            completionController.parentId = stdObjectId;
            completionController.devHubOrgId = wizardDevHubId;
            completionController.showPermissionsPanel = false;
            completionController.sourceBranch = sourceBranch;
            completionController.showSetup = false;
        }
        return null;
    }

    public PageReference jobStatusNotification() {
        Boolean jobFinished = ApexPages.currentPage().getParameters().get('jobFinished') == 'true' ? true : false;
        Boolean jobSuccess = ApexPages.currentPage().getParameters().get('jobSuccess') == 'true' ? true : false;
        String jobMessage = ApexPages.currentPage().getParameters().get('jobMessage');
        String jobType = ApexPages.currentPage().getParameters().get('jobType');

        if (jobFinished && jobSuccess && String.isNotBlank(jobType)) {
            if (jobType == CopadoNotificationHelper.DX_CREATE_FULL_ORG) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, Label.Scratch_Org_Created_Success));
                PageReference pRef = Page.DXTestOrgIntermediary;
                pRef.getParameters().put('id',testRun.Id);
                pRef.setRedirect(true);
                return pRef;
            }
        } else if (jobFinished && !jobSuccess && String.isNotBlank(jobMessage)) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, jobMessage));
        }
        return null;
    }

}