objects/OrgDiff__c.object
<CustomObject>
    <fields>
        <fullName>From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Source Org for which you would like to compare the Metadata. This Org will be the Org from which you would like to migrate Metadata.</inlineHelpText>
        <label>Source Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Org Differences (From Org)</relationshipLabel>
        <relationshipName>FromOrgDiffs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Metadata_Types__c</fullName>
        <inlineHelpText>Empty means all types. Select one or more types to limit the Org Difference only to selected items.</inlineHelpText>
        <label>Metadata Types</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Destination Org for which you would like to compare the Metadata and would like to migrate Metadata to. The resulting grid will show a list of differences with &apos;create&apos;, &apos;update&apos; and &apos;delete&apos; which apply to this Org.</inlineHelpText>
        <label>Destination Org</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>Org Differences (To Org)</relationshipLabel>
        <relationshipName>ToOrgDiffs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Difference</label>
    <nameField>
        <label>Org Difference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Differences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OrgDiffExtension.cls
public with sharing class OrgDiffExtension {
    public string diff_url{get;set;}
    public string deploy_url{get;set;}
    private OrgDiff__c orgdiff;
    public boolean withCreate{get;set;}
    public boolean withUpdate{get;set;}
    public boolean withDelete{get;set;}
    public String errorLevel {get; set;}
    public String messageName {get; set;}
    public boolean isShareable{get;set;}
    public Boolean showError {get;set;} 
    public Boolean showOptions {get;set;}

    public void showMessage() {
        ApexPages.Severity level = ApexPages.Severity.ERROR;
        if(errorLevel == 'WARNING') {
            level = ApexPages.Severity.Warning;
        }else{
            if(errorLevel == 'CONFIRM') {
                level = ApexPages.Severity.CONFIRM;
            }
        }
        ApexPages.addMessage(new ApexPages.Message(level, messageName));
        
    }
    
    public OrgDiffExtension(ApexPages.StandardController stdController) {
        // Add ALL the fields of the sobject to the list of queried fields, to avoid " SObject row was retrieved via SOQL without querying..."
        if (!Test.isRunningTest()) {
            stdController.addFields(new List<String>(Schema.SObjectType.OrgDiff__c.fields.getMap().keySet()));
        }
        showOptions = true;
        showError = false;
        orgdiff = (OrgDiff__c) stdController.getRecord();
        setUrls();
        Map<String, Schema.SObjectType> tokens = Schema.getGlobalDescribe();
		isShareable = tokens.containsKey('OrgDiff__Share');
        isLicenseEnabled();
    }

    public void setUrls(){
        //TODO: move this to external util method in order to use it in other classes 
        String urlParameters = '?nosid=1';
        String herokuServer = settings.Server_URL;
        String urlBase = herokuServer + '/json/v1/'; 
        diff_url = urlBase + 'diff/'+EncodingUtil.urlEncode(orgdiff.Id,'UTF-8') + urlParameters;
        if(orgdiff.Metadata_Types__c != null && orgdiff.Metadata_Types__c !='')diff_url += '&filter='+EncodingUtil.urlEncode(orgdiff.Metadata_Types__c,'UTF-8');
        
        withCreate = ApexPages.currentPage().getParameters().get('withCreate')+''=='true';
        withUpdate = ApexPages.currentPage().getParameters().get('withUpdate')+''=='true';
        withDelete = ApexPages.currentPage().getParameters().get('withDelete')+''=='true';
        deploy_url = urlBase + 'diffDeployment/'+EncodingUtil.urlEncode(orgdiff.Id,'UTF-8')+urlParameters+'&withCreate='+withCreate+'&withUpdate='+withUpdate+'&withDelete='+withDelete;
    }
    public PageReference validateOrgs(){
        if(!DeployAPI.validateOrg(orgdiff.From_Org__c)){
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error,Schema.OrgDiff__c.fields.From_Org__c.getDescribe().getLabel()+': '+Label.WRONG_CREDENTIALS));
        }
        if(!DeployAPI.validateOrg(orgdiff.To_Org__c)){
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error,Schema.OrgDiff__c.fields.To_Org__c.getDescribe().getLabel()+': '+Label.WRONG_CREDENTIALS));
        }
        return null;
    }
    public PageReference deploy(){
        if(LicenseHelper.isLicensesExceeded()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error,Label.LICENSES_EXCEEDED));
            return null;
        }
        if(!withCreate && !withUpdate && !withDelete){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.error,Label.SELECT_AT_LEAST_ONE_RECORD));
            return null;
        }
        if(!DeployAPI.validateOrg(orgdiff.From_Org__c)){
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error,Schema.OrgDiff__c.fields.From_Org__c.getDescribe().getLabel()+': '+Label.WRONG_CREDENTIALS));
            return null;
        }
        if(!DeployAPI.validateOrg(orgdiff.To_Org__c)){
            Apexpages.addMessage(new apexpages.Message(apexpages.severity.error,Schema.OrgDiff__c.fields.To_Org__c.getDescribe().getLabel()+': '+Label.WRONG_CREDENTIALS));
            return null;
        }
        PageReference pr = Page.OrgDiffDeployment;
        pr.setRedirect(true);
        pr.getParameters().put('Id',orgdiff.Id);
        pr.getParameters().put('withCreate',withCreate+'');
        pr.getParameters().put('withUpdate',withUpdate+'');
        pr.getParameters().put('withDelete',withDelete+'');
        return pr;
    }
        public void isLicenseEnabled(){
        if (!LicenseHelper.actionIsLicenseEnabled('viewEditOrgDifferences')){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, Label.CAD_License_Restriction));
            showError = true;
            showOptions = false;
        }
        return;
    }
}