objects/Persona__c.object
<CustomObject>
    <label>Persona</label>
    <nameField>
        <label>Persona Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Persona_Permission__c.object
<CustomObject>
    <fields>
        <fullName>Permission_Set_Name__c</fullName>
        <label>Permission Set Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Persona__c</fullName>
        <label>Persona</label>
        <referenceTo>Persona__c</referenceTo>
        <relationshipLabel>Persona Permissions</relationshipLabel>
        <relationshipName>Persona_Permissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Persona Permission</label>
    <nameField>
        <displayFormat>PP-{0000000}</displayFormat>
        <label>Persona Permission Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persona Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Persona_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Persona__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Persona</label>
        <referenceTo>Persona__c</referenceTo>
        <relationshipLabel>User Persona Assignments</relationshipLabel>
        <relationshipName>User_Persona_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Permissions Assigned</fullName>
                </value>
                <value>
                    <fullName>Permissions Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>User Persona Assignments</relationshipLabel>
        <relationshipName>User_Persona_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Persona Assignment</label>
    <nameField>
        <displayFormat>UPA-{000000000}</displayFormat>
        <label>User Persona Assignment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Persona Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestPermissionSetExplorerExt.cls
@isTest
public class TestPermissionSetExplorerExt {

	@testSetup 
    static void setupData() {
		createPermissionSets();
        insertUser();
	}
	
	static testMethod void TestExplorer() {

		Persona__c releaseManager= createPersona('Test Release Manager');
        List<Persona_Permission__c> releaseManagerPermissions=createPersonaPermissions(releaseManager.Id, 'UnitTest_A_CopadoTest,UnitTest_B_CopadoTest,UnitTest_C_CopadoTest');
        
        User_Persona_Assignment__c ppa=new User_Persona_Assignment__c(Persona__c=releaseManager.Id, User__c=getTestUser().Id, Status__c='Draft');
        insert ppa;

		Test.startTest();
        PermissionSetExplorerExt pse=new PermissionSetExplorerExt();
        PermissionSetExplorerExt.PersonaId=releaseManager.Id;
        List<SelectOption> personas=pse.getPersonas();
		PermissionSetExplorerExt.LoadPermissions();
		Test.stopTest();
	}

	private static User getTestUser(){
        return [select Id from User where username ='futureuser777@test-copado.org'];
    }
    @Future
    public static void insertUser() {
        Profile p=[SELECT Id FROM Profile WHERE Name='System Administrator'];
        //removed chatter dependency
        User futureUser=new User(firstname='Future', lastname='User',
            alias='future', 
            email='test@test.org',
            emailencodingkey='UTF-8', 
			languagelocalekey='en_US', 
            localesidkey='en_US', 
			profileid=p.Id, 
            timezonesidkey='America/Los_Angeles',
            username='futureuser777@test-copado.org'
            );
        insert(futureUser);
    }
    
    @Future
    private static void createPermissionSets(){
        List<PermissionSet> perms=new List<PermissionSet>();
        perms.add(new PermissionSet(Name='UnitTest_A_CopadoTest', Label='UnitTest_A_CopadoTest'));
        perms.add(new PermissionSet(Name='UnitTest_B_CopadoTest', Label='UnitTest_B_CopadoTest'));
        perms.add(new PermissionSet(Name='UnitTest_C_CopadoTest', Label='UnitTest_C_CopadoTest'));
        System.debug('inserting Permission sets: ' + perms);
        insert perms;

        List<FieldPermissions> Lfp=new List<FieldPermissions>();
        Lfp.add(new FieldPermissions(Field='Account.Rating',ParentId=perms[0].Id,PermissionsEdit=false,PermissionsRead=true,SobjectType='Account'));
		Lfp.add(new FieldPermissions(Field='Account.Rating',ParentId=perms[1].Id,PermissionsEdit=true,PermissionsRead=true,SobjectType='Account'));
		insert Lfp;

		List<ObjectPermissions> Lop=new List<ObjectPermissions>();
		Lop.add(new ObjectPermissions(ParentId=perms[0].Id,PermissionsCreate=false,PermissionsDelete=false,PermissionsEdit=false,PermissionsModifyAllRecords=false,PermissionsRead=true,PermissionsViewAllRecords=false,SobjectType='Account'));
		Lop.add(new ObjectPermissions(ParentId=perms[1].Id,PermissionsCreate=true,PermissionsDelete=false,PermissionsEdit=true,PermissionsModifyAllRecords=false,PermissionsRead=true,PermissionsViewAllRecords=false,SobjectType='Account'));
		insert Lop;
	}
    private static Persona__c createPersona(String n){
        Persona__c x=new Persona__c(Name=n);
        insert x;
        return x;
    }
    private static List<Persona_Permission__c> createPersonaPermissions(Id personaId, String perms){
        List<Persona_Permission__c> pps=new List<Persona_Permission__c>();
        for(String s : perms.split(',')){
            pps.add(new Persona_Permission__c(Persona__c=personaId, Permission_Set_Name__c=s));
        }
        insert pps;
        return pps;
    }
}