objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sprint__c.object
<CustomObject>
    <description>If a project is broken down into multiple sprints this object should be used.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Run__c.object
<CustomObject>
    <description>The execution of the test script.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for testing</fullName>
                    <default>true</default>
                    <label>Ready for testing</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with comments</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipName>Test_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Test Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Run_Step__c.object
<CustomObject>
    <description>The execution of each templated test script step.</description>
    <fields>
        <fullName>Action_Description__c</fullName>
        <formula>Script_Step__r.Action_Description__c</formula>
        <label>Action/Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <formula>Script_Step__r.Expected_Result__c</formula>
        <label>Expected Result</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guidance_notes__c</fullName>
        <formula>Script_Step__r.Guidance_notes__c</formula>
        <label>Guidance notes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with comments</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test Run Step</label>
    <nameField>
        <displayFormat>TRS-{000000}</displayFormat>
        <label>Test Run Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Run Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <label>Introduction</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Outcome__c</fullName>
        <label>Overall Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with comments</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Peer_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Peer Reviewer</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Test Scripts</relationshipLabel>
        <relationshipName>Test_Scripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prerequisites__c</fullName>
        <label>Prerequisites</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>User_Story__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>User_Story__r.Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Description__c</fullName>
        <label>Test Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Title__c</fullName>
        <label>Test Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Test Scripts (User Story)</relationshipLabel>
        <relationshipName>Test_Scripts_UserStory</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Script_Step__c.object
<CustomObject>
    <description>The individual template step for a test script</description>
    <fields>
        <fullName>Action_Description__c</fullName>
        <label>Action/Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guidance_notes__c</fullName>
        <label>Guidance notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Passed with comments</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Script Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sprint where the User Story is planned.</description>
        <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CMUtilities.cls
public with sharing class CMUtilities {

    public static Test_Script__c getTestScriptById(String recordId){
        return [SELECT CreatedById, CreatedDate, IsDeleted, Expected_Result__c, Introduction__c, LastModifiedById, LastModifiedDate, Overall_Outcome__c, OwnerId, Peer_Reviewer__c, Prerequisites__c, Project__c, Id, Sprint__c, Status__c, SystemModstamp, Test_Description__c, Name, Test_Title__c, User_Story__c FROM Test_Script__c WHERE Id =:recordId limit 1];
    }
    public static List<Test_Script__c> getTestScripts(Set<Id> thisSet){
        return [SELECT CreatedById, CreatedDate, IsDeleted, Expected_Result__c, Introduction__c, LastModifiedById, LastModifiedDate, Overall_Outcome__c, OwnerId, Peer_Reviewer__c, Prerequisites__c, Project__c, Id, Sprint__c, Status__c, SystemModstamp, Test_Description__c, Name, Test_Title__c, User_Story__c, (SELECT Action_Description__c, CreatedById, CreatedDate, IsDeleted, Expected_Result__c, Guidance_notes__c, LastModifiedById, LastModifiedDate, Order__c, Id, Result__c, Name, Step_Title__c, SystemModstamp, Test_Script__c FROM Script_Steps__r) FROM Test_Script__c WHERE Id =:thisSet limit 1];
    }
    public static List<Test_Script_Step__c> getTestScriptStepsByTest(String testScriptId){
        return [SELECT Action_Description__c, CreatedById, CreatedDate, IsDeleted, Expected_Result__c, Guidance_notes__c, LastModifiedById, LastModifiedDate, Order__c, Id, Result__c, Name, Step_Title__c, SystemModstamp, Test_Script__c FROM Test_Script_Step__c WHERE Test_Script__c =:testScriptId order by Order__c ASC];
    }
    public static List<Test_Run__c> getTestRuns(Set<Id> thisSet){
        return [SELECT Id, Name, Test_Script__c FROM Test_Run__c WHERE Id IN:thisSet];
    }
    public static List<Test_Run_Step__c> getTestRunStepsByTestRun(String testRunId){
        return [SELECT Action_Description__c, Actual_Result__c, CreatedById, CreatedDate, IsDeleted, Expected_Result__c, Guidance_notes__c, LastModifiedById, LastModifiedDate, Id, Script_Step__c, Script_Step__r.Order__c, Status__c, SystemModstamp, Test_Run__c, Name FROM Test_Run_Step__c WHERE Test_Run__c =:testRunId order by Script_Step__r.Order__c ASC];
    }
    public static List<Deployment_Flow_Step__c> getFlowStepsByFlow(String parentId){
        return [SELECT Id, Name, Source_Environment__c, Destination_Environment__c, Deployment_Flow__c FROM Deployment_Flow_Step__c WHERE Deployment_Flow__c = :parentId];
    }
}