objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Index_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this field is checked, Copado will index the metadata selected against the user stories into the User Story Metadata custom object. Indexed metadata can be used for reporting and compliance, and it&apos;s also used by Copado overlap awareness feature.</inlineHelpText>
        <label>Index Metadata</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_API_Name__c</fullName>
        <label>Metadata API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Conflict</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Conflict Resolved</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Back Promoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestUserStoryMetadataExt.cls
@isTest
private class TestUserStoryMetadataExt {
    @testSetup static void setupTestData(){
        TestUtilities.setTestSettingsEE();
    }
    static testMethod void test(){
    	Project__c testProject = CMTestMethodUtilities.createProject('my project');
        testProject.Index_Metadata__c = true;
        insert testProject;


        List<User_Story__c> uList = new List<User_Story__c>();
        User_Story__c testUserStory1 = CMTestMethodUtilities.createUserStory('test');
        testUserStory1.Project__c = testProject.Id;
        uList.add(testUserStory1);
        User_Story__c testUserStory2 = CMTestMethodUtilities.createUserStory('test2');
        testUserStory2.Project__c = testProject.Id;
        uList.add(testUserStory2);
        User_Story__c testUserStory3 = CMTestMethodUtilities.createUserStory('test3');
        testUserStory2.Project__c = testProject.Id;
        uList.add(testUserStory3);
        insert uList;


        List<User_Story_Metadata__c> uMList = new List<User_Story_Metadata__c>();
        User_Story_Metadata__c usm1 = new User_Story_Metadata__c(Name='US-0006186 CustomObject.Account',Metadata_API_Name__c='CustomObject.Account',User_Story__c=testUserStory1.Id,Status__c='Potential Conflict');
        uMList.add(usm1);
        User_Story_Metadata__c usm2 = new User_Story_Metadata__c(Name='US-0000777 CustomObject.Account',Metadata_API_Name__c='CustomObject.Account',User_Story__c=testUserStory2.Id,Status__c='Potential Conflict');
        uMList.add(usm2);
        User_Story_Metadata__c usm3 = new User_Story_Metadata__c(Name='US-0000567 CustomObject.Account',Metadata_API_Name__c='CustomObject.Account',User_Story__c=testUserStory3.Id,Status__c='Potential Conflict');
        uMList.add(usm3);
        User_Story_Metadata__c usm4 = new User_Story_Metadata__c(Name='US-0006186 CustomLabel.VALIDATE',Metadata_API_Name__c='CustomLabel.VALIDATE',User_Story__c=testUserStory1.Id,Status__c='On Hold');
        uMList.add(usm4);
        User_Story_Metadata__c usm5 = new User_Story_Metadata__c(Name='US-0000777 ApexClass.Helper',Metadata_API_Name__c='ApexClass.Helper',User_Story__c=testUserStory2.Id,Status__c='In Review');
        uMList.add(usm5);
        User_Story_Metadata__c usm6 = new User_Story_Metadata__c(Name='US-0000567 CustomField.Account.XYZ__c',Metadata_API_Name__c='CustomField.Account.XYZ__c',User_Story__c=testUserStory3.Id,Status__c='');
        uMList.add(usm6);
        insert uMList;

        System.assertEquals(6, [select count() from User_Story_Metadata__c]);
        System.assertEquals(3, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict']);
        System.assertEquals(3, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict' and Metadata_API_Name__c='CustomObject.Account']);     

        Test.startTest(); 

        ApexPages.currentPage().getParameters().put('Status','Conflict Resolved');
        ApexPages.currentPage().getParameters().put('metadataId',usm3.Id);

        UserStoryMetadataExt ext = new UserStoryMetadataExt(new ApexPages.StandardController(usm3));
        system.debug('#### UserStoryMetadata:"'+ext.usMetadata);
        system.assertEquals('Potential Conflict', ext.usMetadata.Status__c);
        system.assertEquals(2, ext.usMetadatas.size());
        system.assertEquals(5, ext.getStatuses().size());//JG: now we "Back Promoted"

        ext.updateStatus();
        system.assertEquals('Conflict Resolved', ext.usMetadata.Status__c);

        ext.metadataId = '';
		ext.updateStatuses();

        Test.stopTest();

        System.assertEquals(0, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict']);
        System.assertEquals(3, [select count() from User_Story_Metadata__c where Status__c='Conflict Resolved' AND Metadata_API_Name__c='CustomObject.Account']);
        ext.deleteJob();
    }
}