objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Index_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this field is checked, Copado will index the metadata selected against the user stories into the User Story Metadata custom object. Indexed metadata can be used for reporting and compliance, and it&apos;s also used by Copado overlap awareness feature.</inlineHelpText>
        <label>Index Metadata</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_API_Name__c</fullName>
        <label>Metadata API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Conflict</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Conflict Resolved</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Back Promoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestIndexMetadataJob.cls
@isTest
private class TestIndexMetadataJob {
    @testSetup static void setupData() {
        insert TestUtilities.getTestSettings();
    }
    static testMethod void test(){
        Project__c testProject = CMTestMethodUtilities.createProject('my project');
        testProject.Index_Metadata__c = true;
        insert testProject;
                
        User_Story__c testUserStory1 = CMTestMethodUtilities.createUserStory('test');
        testUserStory1.Project__c = testProject.Id;
        insert testUserStory1;
        Attachment at1 = new Attachment();
        at1.Name = 'MetaData';
        at1.ParentId = testUserStory1.Id;
        at1.Body = Blob.valueOf('[{"t":"CustomObject","n":"Account"},{"t":"CustomObject","n":"Contact"},{"t":"CustomField","n":"Account.Number__c"}]');
        insert at1;
        
        User_Story__c testUserStory2 = CMTestMethodUtilities.createUserStory('test');
        testUserStory2.Project__c = testProject.Id;
        insert testUserStory2;
        Attachment at2 = new Attachment();
        at2.Name = 'Git MetaData';
        at2.ParentId = testUserStory2.Id;
        //dupes are: CustomObject.Account for US1 and US2
        at2.Body = Blob.valueOf('[{"t":"CustomObject","n":"Account"},{"t":"CustomObject","n":"Opportunity"},{"t":"CustomField","n":"Account.XYZ__c"}]');
        insert at2;
        
        Attachment at3 = new Attachment();
        at3.Name = 'Delete MetaData';
        at3.ParentId = testUserStory2.Id;
        //dupes are: CustomObject.Account for US1,US2 and US3 - CustomField.Account.XYZ__c for US1 and US3
        at3.Body = Blob.valueOf('[{"t":"CustomObject","n":"Account"},{"t":"CustomObject","n":"OpportunityLineItem"},{"t":"CustomField","n":"Account.XYZ__c"}]');
        insert at3;
        
        Test.startTest();
        Database.executeBatch(new IndexMetadataJob(), 50);
        Test.stopTest();
        for (User_Story_Metadata__c md:[select Status__c, Metadata_API_Name__c from User_Story_Metadata__c])System.debug('**** ' + md);
        System.assertEquals(9, [select count() from User_Story_Metadata__c]);
        System.assertEquals(5, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict']);
        System.assertEquals(3, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict' and Metadata_API_Name__c='CustomObject.Account']);
        System.assertEquals(2, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict' and Metadata_API_Name__c='CustomField.Account.XYZ__c']);
    }
    static testMethod void testWithUserStory() {
        Project__c testProject = CMTestMethodUtilities.createProject('my project');
        testProject.Index_Metadata__c = true;
        insert testProject;
                
        User_Story__c testUserStory1 = CMTestMethodUtilities.createUserStory('test');
        testUserStory1.Project__c = testProject.Id;
        insert testUserStory1;
        User_Story__c testUserStory2 = CMTestMethodUtilities.createUserStory('test');
        testUserStory2.Project__c = testProject.Id;
        insert testUserStory2;

        Test.startTest();

        Attachment at1 = new Attachment();
        at1.Name = 'MetaData';
        at1.ParentId = testUserStory1.Id;
        at1.Body = Blob.valueOf('[{"t":"CustomObject","n":"Account"},{"t":"CustomObject","n":"Contact"},{"t":"CustomField","n":"Account.Number__c"}]');
        insert at1;
                
        Attachment at2 = new Attachment();
        at2.Name = 'Git MetaData';
        at2.ParentId = testUserStory2.Id;
        //dupes are: CustomObject.Account for US1 and US2
        at2.Body = Blob.valueOf('[{"t":"CustomObject","n":"Account"},{"t":"CustomObject","n":"Opportunity"},{"t":"CustomField","n":"Account.XYZ__c"}]');
        insert at2;
        
        Attachment at3 = new Attachment();
        at3.Name = 'Delete MetaData';
        at3.ParentId = testUserStory2.Id;
        //dupes are: CustomObject.Account for US1,US2 and US3 - CustomField.Account.XYZ__c for US1 and US3
        at3.Body = Blob.valueOf('[{"t":"CustomObject","n":"Account"},{"t":"CustomObject","n":"OpportunityLineItem"},{"t":"CustomField","n":"Account.XYZ__c"}]');
        insert at3;

        Attachment at4 = new Attachment();
        at4.Name = 'Delete MetaData';
        at4.ParentId = testUserStory1.Id;
        //dupes are: CustomObject.Account for US1,US2 and US3 - CustomField.Account.XYZ__c for US1 and US3
        at4.Body = Blob.valueOf('[{"t":"CustomField","n":"Account.Number__c"}]');
        insert at4;
        delete at4;
        
        Test.stopTest();//Comments for Git Refresh

        for (User_Story_Metadata__c md:[select Status__c, Metadata_API_Name__c from User_Story_Metadata__c])System.debug('**** ' + md);
        System.assertEquals(9, [select count() from User_Story_Metadata__c]);
        System.assertEquals(5, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict']);
        System.assertEquals(3, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict' and Metadata_API_Name__c='CustomObject.Account']);
        System.assertEquals(2, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict' and Metadata_API_Name__c='CustomField.Account.XYZ__c']);
        System.assertEquals(0, [select count() from User_Story_Metadata__c where Status__c='Potential Conflict' and Metadata_API_Name__c='CustomField.Account.Number__c']);
    }
}