objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Index_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this field is checked, Copado will index the metadata selected against the user stories into the User Story Metadata custom object. Indexed metadata can be used for reporting and compliance, and it&apos;s also used by Copado overlap awareness feature.</inlineHelpText>
        <label>Index Metadata</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stop_Indexing_Metadata__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</description>
        <inlineHelpText>If checked, the User Story will not be indexed for Copado&apos;s Overlap Awareness.</inlineHelpText>
        <label>Stop Indexing Metadata</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story_Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Metadata_API_Name__c</fullName>
        <label>Metadata API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Potential Conflict</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Conflict Resolved</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Back Promoted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>User Story Metadata</relationshipLabel>
        <relationshipName>User_Story_Metadata</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Metadata</label>
    <nameField>
        <label>User Story Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IndexMetadataJob.cls
global with sharing class IndexMetadataJob implements Database.batchable<sObject>, Schedulable {
    public String userstoryId {get;set;}
	global Database.QueryLocator start(Database.BatchableContext BC){
		if(userstoryId != null) {
            return Database.getQueryLocator([select id from User_Story__c where Id = :userstoryId
                            AND Stop_Indexing_Metadata__c = false  AND Project__r.Index_Metadata__c = true]);
        } else return Database.getQueryLocator([select id from User_Story__c where Stop_Indexing_Metadata__c = false  
                                                AND Project__r.Index_Metadata__c=true]);
	}
	global void execute(Database.BatchableContext BC, List<User_Story__c> scope){
		Set<Id> uids = new Set<Id>();
		for(User_Story__c us : scope){
            uids.add(us.id);
		}
        Map<String,User_Story_Metadata__c> toBeUpserted = new Map<String,User_Story_Metadata__c>();
        for (Attachment att:[select Id, Name, Body, ParentId, Parent.Name from Attachment where parentId in :uids and name in ('MetaData','Delete MetaData', 'Git MetaData')]){
            try{
                String jsonInput = att.body.toString();
                List<Object> l = (List<Object>)JSON.deserializeUntyped(jsonInput);                
                for(Object o:l){
                    Map<String, Object> m = (Map<String, Object>)o;
                    User_Story_Metadata__c um = new User_Story_Metadata__c();
                    um.User_Story__c = att.ParentId;
                    um.Metadata_API_Name__c = m.get('t') + '.' + m.get('n');
                    um.Metadata_API_Name__c = um.Metadata_API_Name__c.left(255);
                    um.Unique_ID__c = att.ParentId + (att.Name=='Delete Metadata'?' _delete_':'_') + um.Metadata_API_Name__c;
                    um.Unique_ID__c = um.Unique_ID__c.left(255);
                    um.Name = att.Parent.Name + (att.Name=='Delete Metadata'?' Delete ':' ') + um.Metadata_API_Name__c;
                    um.Name = um.Name.left(80);
                    toBeUpserted.put(um.Unique_ID__c, um);
                }
            }
            catch(Exception e){
                System.debug('ERROR while parsing attachment ' + att.Name + ' - ' + att.Id + ' exception: ' + e.getMessage());
            }
        }
        Utilities.Secure_DML(toBeUpserted.values(), Utilities.DML_Action.UPS, schema.Sobjecttype.User_Story_Metadata__c, schema.sObjectType.User_Story_Metadata__c.fields.Unique_ID__c);     
	}
	global void finish(Database.BatchableContext BC){
        Set<String> dupes = new Set<String>();
        AggregateResult[] groupedResults = [SELECT Metadata_API_Name__c, count(Id) FROM User_Story_Metadata__c WHERE Status__c='' 
        and User_Story__r.Project__r.Index_Metadata__c=true AND User_Story__r.Stop_Indexing_Metadata__c = false GROUP BY Metadata_API_Name__c HAVING Count(Id) > 1];
        for (AggregateResult ar : groupedResults){
            String gname = Settings.ns+'Metadata_API_Name__c';
            String gr = ''+ar.get(gname);
            System.debug('***** grouped result name: ' + gname + ' value: ' + gr + ' all: ' + ar);
            dupes.add(gr);
        }
        List<User_Story_Metadata__c> toBeUpdated = new List<User_Story_Metadata__c>();
        for(User_Story_Metadata__c um : [Select Id from User_Story_Metadata__c where Metadata_API_Name__c in:dupes and Status__c='' 
            and User_Story__r.Project__r.Index_Metadata__c=true AND User_Story__r.Stop_Indexing_Metadata__c = false]){
            um.Status__c='Potential Conflict';
            toBeUpdated.add(um);
        }
        Utilities.Secure_DML(toBeUpdated, Utilities.DML_Action.UPD, schema.Sobjecttype.User_Story_Metadata__c);
	}
    global void execute(SchedulableContext sc) {
		IndexMetadataJob b = new IndexMetadataJob(); 
		database.executebatch(b,50);
   }
}