objects/Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Release__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sprint__c.object
<CustomObject>
    <description>If a project is broken down into multiple sprints this object should be used.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project where the User Story belongs.</description>
        <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product version or release where this User Story will be released.</description>
        <inlineHelpText>Product version or release where this User Story will be released.</inlineHelpText>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sprint where the User Story is planned.</description>
        <inlineHelpText>Sprint where the User Story is planned.</inlineHelpText>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Current status of the implementation of the User Story.</description>
        <inlineHelpText>Current status of the implementation of the User Story.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Backburner</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Story_Title__c</fullName>
        <description>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</description>
        <inlineHelpText>Short description of the User Story or requirement. Technical and non-technical team members should be able to understand the description.</inlineHelpText>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestMassAddToReleaseExtension.cls
@isTest
private class TestMassAddToReleaseExtension {

    static testMethod void massAddBySprint() {
        Project__c testProject = CMTestMethodUtilities.createProject('My Project');
        insert testProject;
        Release__c testRelease = CMTestMethodUtilities.createRelease('My Release');
        testRelease.Project__c = testProject.Id;
        insert testRelease;
        Sprint__c sprint1 = CMTestMethodUtilities.createSprint('Sprint1');
       	sprint1.Project__c = testProject.Id;
        insert sprint1;
        Sprint__c sprint2 = CMTestMethodUtilities.createSprint('Sprint2');
       	sprint2.Project__c = testProject.Id;
        insert sprint2;
        
        List<User_Story__c> sprint_stories = new List<User_Story__c>();
        for(Integer i=1; i<=5; i++){
        	User_Story__c us1 = new User_Story__c(Project__c=testProject.Id, Sprint__c=sprint1.Id, User_Story_Title__c='Title'+i, Status__c = 'Approved');
        	User_Story__c us2 = new User_Story__c(Project__c=testProject.Id, Sprint__c=sprint2.Id, User_Story_Title__c='Title'+i, Status__c = 'Approved');
        	if(i>3){
        		sprint_stories.add(us1);
        	}
        	else{
        		sprint_stories.add(us1);
        		sprint_stories.add(us2);
        	}
        }
        // We added 5 User Stories to Sprint 1
        // We added 3 User Stories to Sprint 2
        insert sprint_stories;
        System.debug(loggingLevel.Error, '*** sprint_stories: ' + sprint_stories);
        PageReference pref = Page.MassAddToRelease;
	    pref.getParameters().put('id',testRelease.id);
	    Test.setCurrentPage(pref);
	    
        MassAddToReleaseExtension ext = new MassAddToReleaseExtension(new ApexPages.StandardController(testRelease));
        
        List<MassAddToReleaseExtension.sprintWrapper> sprintsList = ext.wrapSprints(ext.sprints);
        system.assertEquals(2, sprintsList.size());
        Integer s1counter = 0;
        Integer s2counter = 0;
        System.debug(loggingLevel.Error, '*** sprintsList: ' + sprintsList);
        for(MassAddToReleaseExtension.sprintWrapper s : sprintsList){
        	if(s.sprint.Name==sprint1.Name)s1counter=s.usWrapper.size();
        	if(s.sprint.Name==sprint2.Name)s2counter=s.usWrapper.size();
        }
        system.assertEquals(5, s1counter);
        system.assertEquals(3, s2counter);
        
        // try to update (none selected) and expect error
        ext.massAdd_BySprint();
        CMTestMethodUtilities.hasMessage('You must select at least 1 User Story to add to the Release');
        
        // now we select 2 user stories (1 from each sprint) and add them to the release
        Boolean selected1 = false;
        Boolean selected2 = false;
        
        for(MassAddToReleaseExtension.sprintWrapper sw : ext.wrappedSprints){	
			for(MassAddToReleaseExtension.userStoryWrapper usw : sw.usWrapper){
				if(sw.sprint.Name==sprint1.Name && selected1==false){
					selected1=true;
					usw.selected=true;
				}
				if(sw.sprint.Name==sprint2.Name && selected2==false){
					selected1=true;
					usw.selected=true;
				}
			}
		}
        ext.massAdd_BySprint();
        CMTestMethodUtilities.hasMessage('Your selected User Stories have been added to the Release');
        for(MassAddToReleaseExtension.sprintWrapper sw : ext.wrappedSprints){	
			for(MassAddToReleaseExtension.userStoryWrapper usw : sw.usWrapper){
				system.assertEquals(false, usw.selected);
			}
		}
    }
}