objects/Selenium_Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Previous_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Version</label>
        <referenceTo>Selenium_Test_Case__c</referenceTo>
        <relationshipLabel>Next Version</relationshipLabel>
        <relationshipName>Selenium_Test_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <label>Version</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Selenium Test Case</label>
    <nameField>
        <label>Selenium Test Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selenium Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloneSeleniumTestCaseExtension.cls
public with sharing class CloneSeleniumTestCaseExtension {
    public final Selenium_Test_Case__c tc{get;set;}
    public Selenium_Test_Case__c clonedTC{get;set;}
    public CloneSeleniumTestCaseExtension(ApexPages.StandardController stdController) {
        tc = [select id, name, Version__c from Selenium_Test_Case__c where id = :stdController.getId()];
        clonedTC = tc.clone();
        // A new version must be created.
        Integer next = 1;
        try{
            System.debug('tc.Version__c='+tc.Version__c);
            next = Integer.valueOf(tc.Version__c.replace('v','')) + 1;
        }catch(Exception e) {
            System.debug('Error parsing the attachment name for the next version '+e);
            next = 2;
        }
        clonedTC.Version__c = ''+next;
        clonedTC.Previous_Version__c = tc.Id;
        clonedTC.Name = clonedTC.Name.replaceAll('-v[0-9]+$', '')+'-v'+clonedTC.Version__c;
    }

    public PageReference doClone(){
        Utilities.Secure_DML(clonedTC, Utilities.DML_Action.INS, schema.Sobjecttype.Selenium_Test_Case__c);

        Attachment[] sobs;
        List<Id> doneIds = new List<Id>();
        do {
            sobs = [
                    select Id, ParentId, Name, Description, Body, ContentType
                    from Attachment
                    where ParentId = :tc.Id
                    and Id not in :doneIds
                    limit 1
                    ];
            if (sobs.size() == 1) {
                Attachment sob = sobs[0];
                if( sob.Name == 'Copado.SeleniumTestCase.json' ) {
                    Map<String, Object> tc = (Map<String, Object>)JSON.deserializeUntyped(sob.Body.toString());
                    tc.put('name', (String)clonedTC.Name);
                    sob.Body = Blob.valueOf(JSON.serialize(tc));
                }
                Utilities.Secure_DML(new Attachment(
                        ParentId = clonedTC.Id,
                        Name = sob.Name,
                        Description = sob.Description,
                        Body = sob.Body,
                        ContentType = sob.ContentType
                        ), Utilities.DML_Action.INS, schema.Sobjecttype.Attachment);
                doneIds.add(sob.Id);
                System.debug('>>> loop heap=' + Limits.getHeapSize());
            }
        } while (sobs.size() == 1);


        return new PageReference('/'+clonedTC.Id);
    }
}