objects/Static_Code_Analysis_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <description>Priority of the rule, where 1 is the highest, and 5 the lowest.</description>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Static_Code_Analysis_Settings__c</fullName>
        <label>Static Code Analysis Settings</label>
        <referenceTo>Static_Code_Analysis_Settings__c</referenceTo>
        <relationshipLabel>Static Code Analysis Rules</relationshipLabel>
        <relationshipName>Static_Code_Analysis_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Static Code Analysis Rule</label>
    <nameField>
        <displayFormat>SCAR-{0000}</displayFormat>
        <label>Static Code Analysis Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Static Code Analysis Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Static_Code_Analysis_Settings__c.object
<CustomObject>
    <label>Static Code Analysis Settings</label>
    <nameField>
        <label>Static Code Analysis Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Static Code Analysis Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestGenerateStaticCodeAnalysisRuleSet.cls
@isTest
public with sharing class TestGenerateStaticCodeAnalysisRuleSet {

	static testMethod void testGenerate() {

		Static_Code_Analysis_Settings__c scas = new Static_Code_Analysis_Settings__c(Name='Test PMD');
		Utilities.Secure_DML(scas, Utilities.DML_Action.INS, schema.Sobjecttype.Static_Code_Analysis_Settings__c); 

		testMethodUtilities.upsertOrgwideSettings();

		Test.startTest();
		GenerateStaticCodeAnalysisRuleSet gscars = new GenerateStaticCodeAnalysisRuleSet(new ApexPages.StandardController(scas));
		GenerateStaticCodeAnalysisRuleSet.generateDefaultRuleSet();
		List<Static_Code_Analysis_Rule__c> rules = [SELECT Priority__c FROM Static_Code_Analysis_Rule__c WHERE Static_Code_Analysis_Settings__c = :scas.Id];
		System.assertEquals(34, rules.size());
		System.assertEquals('3', rules[0].Priority__c);
		gscars.back();
		Test.stopTest();
	}


}