objects/Test_Script__c.object
<CustomObject>
    <description>The template test script.</description>
    <label>Test Script</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Test Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Script_Step__c.object
<CustomObject>
    <description>The individual template step for a test script</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Script__c</fullName>
        <label>Test Script</label>
        <referenceTo>Test_Script__c</referenceTo>
        <relationshipName>Script_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Script Step</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Script Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Script Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateTestScriptStepsController.cls
public with sharing class CreateTestScriptStepsController {
    public Test_Script__c testScript {get;set;}
    public String testScriptId {get;set;}
    public List<stepRow> scriptSteps {get;set;}
    public Integer rowCount {get;set;}
    public Test_Script_Step__c dummyStep {get;set;}
    public Settings settings {get;set;}
    
    public CreateTestScriptStepsController(){
        settings = new Settings();
        testScriptId = ApexPages.currentPage().getParameters().get('tId');
        testScript = CMUtilities.getTestScriptById(testScriptId);
        getSteps();
        dummyStep = new Test_Script_Step__c();
    }
    public PageReference returnToTestScript(){
        return new PageReference('/'+testScriptId);
    }
    public void addRow(){
        scriptSteps = new List<stepRow>();
        dummyStep.Test_Script__c = testScriptId;
        dummyStep.Order__c = rowCount+1;
        Utilities.Secure_DML(dummyStep, Utilities.DML_Action.INS, schema.Sobjecttype.Test_Script_Step__c);
        dummyStep = new Test_Script_Step__c();
        scriptSteps = getSteps();
    }
    public List<stepRow> getSteps(){
        scriptSteps = new List<stepRow>();
        rowCount = 0;
        List<Test_Script_Step__c> tmp = new List<Test_Script_Step__c>();
        tmp = CMUtilities.getTestScriptStepsByTest(testScriptId);
        if(tmp == null)return null;
        for(Test_Script_Step__c s : tmp){
            scriptSteps.add(new stepRow(s));
            rowCount++;
        }
        return scriptSteps;
    }
        
    public class stepRow {
        public Test_Script_Step__c step {get;set;}
        
        public stepRow(Test_Script_Step__c s){
            step = s;
        }
        public void saveStep(){
            try{
                Utilities.Secure_DML(step, Utilities.DML_Action.UPD, schema.Sobjecttype.Test_Script_Step__c);
            }
            catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, ''+e.getMessage()));
            }
        }
        public void deleteStep(){
            Utilities.Secure_DML(step, Utilities.DML_Action.DEL, schema.Sobjecttype.Test_Script_Step__c);
        }
    }
}