objects/User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</description>
        <inlineHelpText>Org Credential used to add or commit metadata and to promote and deploy the User Story to the next Environment.</inlineHelpText>
        <label>Org Credential</label>
        <referenceTo>Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserStoryComplianceScanController.cls
public with sharing class UserStoryComplianceScanController {
    public User_Story__c userStory {get; set;}
    
    public UserStoryComplianceScanController(ApexPages.StandardController std) {
        userStory = [SELECT Id, Org_Credential__c FROM User_Story__c WHERE Id = :std.getId() LIMIT 1];        
    }
    
    public void requestComplianceScan() {
        if(FeatureHelper.isComplianceHubEnabled()){
            if(LicenseHelper.actionIsLicenseEnabled('requestComplianceScan')){
                try {
                    DeployAPI.usComplianceScan(userStory.Org_Credential__c, userStory.Id);
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM, Label.COMPLIANCE_SCAN_REQUESTED));
                } catch (Exception e) {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
                }
            } else {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, Label.CAD_License_Restriction));
            }
        } else {
            Apexpages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, Label.FEATURE_NOT_SUPPORTED+' Compliance Hub'));
        }
    }
}